### ISSUE TITLE
Can oatpp server and client run with same set of threads ?

### ISSUE THREAD

**Issue by bnnk** [oatpp/oatpp#107]
Hi,

    I want to have client and server running as a part of same set of I/O , Data-Processing and time threads. Please let us know if this can be done ?.

rgds
Balaji K

**Comment by lganzzzo** [comment]
Hello @bnnk ,

This is not a problem,- just share your `async::Executor` between server and a client.

For example like in [this test](https://github.com/oatpp/oatpp/blob/master/test/oatpp/web/FullAsyncClientTest.cpp) async executor is shared between client and a server.

Best Regards,
Leonid

**Comment by bnnk** [comment]
Thanks Leonid,

I have added below changes in my server code and the same working fine. Want to make sure I am not missing something here. Modified existing Async Client example to work with async server..

  auto objectMapper = oatpp::parser::json::mapping::ObjectMapper::createShared();
  auto requestExecutor = createCurlExecutor();
  auto client = PWApiClient::createShared(requestExecutor, objectMapper);
  g_executor = components.executor.getObject().get();
  AsyncExample::runExample(client);

oatpp::async::Executor *g_executor = NULL;

void AsyncExample::runExample(const std::shared_ptr<PWApiClient>& client) {


  if (g_executor == NULL) {
  oatpp::async::Executor executor(1, 1, 1);
  executor.execute<SendDtoCoroutine>(client, "message1", 10000);
  executor.execute<SendDtoCoroutine>(client, "message2", 10000);
  executor.execute<SendDtoCoroutine>(client, "message3", 10000);
  executor.waitTasksFinished();
  executor.stop();
  executor.join();
  } else {
  g_executor->execute<SendDtoCoroutine>(client, "message1", 10000);
  g_executor->execute<SendDtoCoroutine>(client, "message2", 10000);
  g_executor->execute<SendDtoCoroutine>(client, "message3", 10000);
  g_executor->waitTasksFinished();
  }
}

Regards
Shri Nandhan

**Comment by lganzzzo** [comment]
@bnnk ,
Please let me know in case you have more questions.

**Comment by bnnk** [comment]
Thanks this helps..
