### ISSUE TITLE
How to set http_content_type to JSON when using requestExecutor?

### ISSUE THREAD

**Issue by puneetugru** [oatpp/oatpp#108]
Hi Leonid,

I'm using RequestExecutor to initiate POST command from the server.

```c++
auto objectMapper = oatpp::parser::json::mapping::ObjectMapper::createShared();
auto requestExecutor = oatpp::curl::RequestExecutor::createShared(URL);
auto client = MyClient::createShared(requestExecutor, objectMapper);

auto dto = PostReadingDto::createShared();
dto->sensorID = sensorID.c_str();
dto->timestamp = timeStamp;
dto->temperature = temperature;
auto data = client->doPostWithDto(URL, dto)->readBodyToString();

The client definition is as below,

class MyClient : public oatpp::web::client::ApiClient {
public:
#include OATPP_CODEGEN_BEGIN(ApiClient)
    
  API_CLIENT_INIT(MyClient)
    
  API_CALL("POST", "{parameter}", doPostAnything, PATH(String, parameter), BODY_STRING(String, body))
  API_CALL("POST", "{parameter}", doPostWithDto, PATH(String, parameter), BODY_DTO(PostReadingDto::ObjectWrapper, body))
#include OATPP_CODEGEN_END(ApiClient)
};

```

But, I see that content-type is not set to JSON in the sent POST request.

I would like to know what is missing in the initialisation or in the usage part.

- Thanks,
Puneet

**Comment by lganzzzo** [comment]
Hello @puneetugru ,

In case you use `BODY_DTO` in `API_CALL` or `API_CALL_ASYNC` - 
`Content-Type` header will be set according to `ObjectMapper` specified in the constructor of `ApiClient`. So in your case this api-call should contain `Content-Type: application/json` header.

```
API_CALL("POST", "{parameter}", doPostWithDto, PATH(String, parameter), BODY_DTO(PostReadingDto::ObjectWrapper, body))
```

If content-type header is not present in the request, then it should be a bug. Please double-check this.

---

You may also add a custom header like this:

```cpp
API_CALL("POST", "{parameter}", doPostWithDto, PATH(String, parameter), HEADER(String, myHeader, "X-My-Header"), BODY_DTO(PostReadingDto::ObjectWrapper, body))
```

---

Please use markdown code snippets.
See [markdown cheatsheet](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet) for more info.

Because it is very hard to read unformatted code.

Best Regards,
Leonid

**Comment by puneetugru** [comment]
Hi Leonid,

Thank you for highlighting the code issue, I searched a lot to post proper formatted code, but could not find it.

Apologies for the inconvenience. I've added proper formatting the code now.

I actually did packet capture and saw that application-type was not set.

Let me see how I can attach it here.

**Comment by puneetugru** [comment]
Hi Leonid,

I've uploaded the packet capture at the link - [https://packettotal.com/app/analysis?id=368d45a17e5264c80829853f5e5a0651&name=conn](url)

**Comment by lganzzzo** [comment]
Hey @puneetugru ,

Thanks for the detailed report!

It must be a bug in `oatpp::curl::RequestExecutor`.

If you change it to oatpp-native `oatpp::web::client::HttpRequestExecutor` - it should work properly.
https://github.com/oatpp/oatpp/blob/master/src/oatpp/web/client/HttpRequestExecutor.hpp

Please let me know if it worked for you.

Best Regards,
Leonid

**Comment by puneetugru** [comment]
Hi Leonid,

I'll make the change and get back to you.

- Thanks,
Puneet

**Comment by lganzzzo** [comment]
Hey @puneetugru ,

I am closing this issue.

Please feel free to reopen it in case you have not resolved it yet.

Regards,
Leonid
