### ISSUE TITLE
Reg: Reading response as string and using de-serializer!

### ISSUE THREAD

**Issue by bkannadassan** [oatpp/oatpp#110]
Hi Leonid,

   I am reading the response via Async read in client

`response->readBodyToStringAsync().callbackTo(&MyCoroutine::onBody);`

Now I want to pass this to the deserializer and get it converted. I have defined the format in DTO file, is there an example which I can refer to for the same ?.

rgds
Balaji Kamal Kannadassan

**Comment by lganzzzo** [comment]
Hello @bkannadassan ,

You can do it like this:

```cpp
class MyDto : public oatpp::data::mapping::type::Object {
  
  DTO_INIT(MyDto, Object)
  
  DTO_FIELD(String, text);
  
};

...

oatpp::String body = "{\"text\":\"value\"}";
auto obj = mapper->readFromString<MyDto>(body);

```
You can use `controller->getDefaultObjectMapper()` method to obtain object mapper in controller.

Best Regards,
Leonid

**Comment by bkannadassan** [comment]
Thanks Leonid,

That did work great, I do have in some case "[{.....}]", Looks like if square brackets in begining it drops though I can drop the first and last character is there any betterway you would suggest for the mapper to parse ?. Like can I give some regexp to drop these characters ?.

rgds
Balaji Kamal Kannadassan

**Comment by bkannadassan** [comment]
:-) I wrapped it around oatpp::data::mapping::type::List< and it worked great, your framework is so modular I can take take individual module and adapt it to how I want. 

rgds
Balaji Kamal Kannadassan
