### ISSUE TITLE
Building from source instructions are missing

### ISSUE THREAD

**Issue by adimallikarjunareddy** [oatpp/oatpp#115]
Is it possible to document how to build this repo from source including the supported toolset needed with any dependencies?

**Comment by lganzzzo** [comment]
Hey @adimallikarjunareddy ,

Thank you for the tip! 
There is really no "build" info in the readme.

With cmake you can build this repo like follows...

From the root of this repository execute:
```bash
$ mkdir build && cd build/ 
$ cmake ..
$ make install
```

After executing this commands you will have oatpp built and installed on your system.

---

I will add this info to the readme!

Best Regards,
Leonid

**Comment by surfingtomchen** [comment]
how to windows platform? Do I need to create a new project in visual studio and drag all the source code into it?

**Comment by lganzzzo** [comment]
Hello @surfingtomchen ,

Just let cmake generate a Visual Studio project for you.

From the root of this repository execute:

```bash
$ MD build       # - create build folder
$ cd build\      # - go to build folder
$ cmake ..       # - generate VS project
```

Regards,
Leonid

**Comment by surfingtomchen** [comment]
Thanks @lganzzzo . Successfully build in Windows vs2015.  Awesome framework!

**Comment by lganzzzo** [comment]
@surfingtomchen , 
Thanks for letting me know!
Please let me know in case of any questions
