### ISSUE TITLE
HttpRequest readBodyToString empty

### ISSUE THREAD

**Issue by nicolaslopez15** [oatpp/oatpp#120]
Hello

I cannot get the bodystring of my HttpRequestExecutor response. it is always empty. (getStatusCode and getStatusDescription are working so I know that the request have been well executed)
when I use oatpp::url it works fine but when I use HttpRequestExecutor it's empty.

can you please help me find what am i doing wrong?

I am expecting a json response from the called API.

here my oattp HttpRequestExecutor declaration:

```cpp
 std::shared_ptr<oatpp::web::client::RequestExecutor> createOatppExecutor() {
   auto config = oatpp::libressl::Config::createShared();
   tls_config_insecure_noverifycert(config->getTLSConfig());
   tls_config_insecure_noverifyname(config->getTLSConfig());
   auto connectionProvider = oatpp::libressl::client::ConnectionProvider::createShared(config, "monurl", 443);
   return oatpp::web::client::HttpRequestExecutor::createShared(connectionProvider);
 }
```

my instanciation:

```cpp
 auto objectMapper = oatpp::parser::json::mapping::ObjectMapper::createShared();
 //auto requestExecutor = createCurlExecutor();
 auto requestExecutor = createOatppExecutor();
 auto client = ApiClient::createShared(requestExecutor, objectMapper);
```

my ApiClient function:

```cpp
API_CALL("GET", "mypath?myparameter={parameter}", doGettokeninfoheader,HEADER(String, myHeader1, "Content-type"),HEADER(String, myHeader2, "Accept"), PATH(String, parameter))
```

and my call

```cpp
auto data3 = client->doGettokeninfoheader("application/x-www-form-urlencoded","application/json","PHOkrUhrhE-kz-ljWw5ci2SExSg");
OATPP_LOGD("Api call", "string='%s'", data3->readBodyToString()->c_str());  --> empty when HttpRequestExecutor :-( 
```

thanks for your help

**Comment by lganzzzo** [comment]
Hello @nicolaslopez15 ,

Thanks for reporting the issue!

So when you have all the above declarations, and when you use:
- `auto requestExecutor = createCurlExecutor();` - **everything works fine.**
- `auto requestExecutor = createOatppExecutor();` - **body is empy.**

AM I correct?

**Comment by nicolaslopez15** [comment]
hi,

yes i did not succeed to get the body with my createOatppExecutor.

thanks for your answer

**Comment by lganzzzo** [comment]
```cpp
auto connectionProvider = oatpp::libressl::client::ConnectionProvider::createShared
```

Is it a publicly accessible resource, can you share the exact url?

**Comment by nicolaslopez15** [comment]
no unfortunately it's not public i cannot share it

**Comment by nicolaslopez15** [comment]
and url from basic example (httpbin.org) is not opened from my company so I cannot even test it :-(

**Comment by lganzzzo** [comment]
Ok, I will check this. And will get back to you.
Once again, thanks for the report!

**Comment by lganzzzo** [comment]
Hey @nicolaslopez15 ,

Can you please dump the raw response from your url - just everything that outputs the command:

```bash
curl "https://<your-url>/" -v -raw
```

Just put it here.

Thank you

**Comment by lganzzzo** [comment]
And one more question:

So when you have:
```cpp
auto requestExecutor = createOatppExecutor();
```

and you do
```cpp
auto data3 = client->doGettokeninfoheader("application/x-www-form-urlencoded","application/json","PHOkrUhrhE-kz-ljWw5ci2SExSg");

data->getStatusCode() // <-- is it 200 ??? 

```

Is `getStatusCode()` returns 200 for you?

**Comment by nicolaslopez15** [comment]
thanks for your reactivity.

yes I have status code 200

here the result of curl command as requested:

` curl "https://myurl" -v -raw
Warning: Invalid character is found in given range. A specified range MUST
Warning: have only digits in 'start'-'stop'. The server's response to this
Warning: request is uncertain.
* About to connect() to myurl port 443 (#0)
*   Trying 192.163.162.165...
* Connected to myurl (192.163.162.165) port 443 (#0)
* Initializing NSS with certpath: sql:/etc/pki/nssdb
*   CAfile: /etc/pki/tls/certs/ca-bundle.crt
  CApath: none
* SSL connection using TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
* Server certificate:
*       subject: CN=myurl,OU=XXXXX-ARC,O=GROUPE MYCOMPANY,L=Paris,ST=Ile de France,C=FR
*       start date: Apr 26 09:37:31 2018 GMT
*       expire date: Jun 27 09:37:31 2022 GMT
*       common name: myurl
*       issuer: CN=UniPass Server Authentication 2016 CA,O=GROUPE MYCOMPANY
> GET / HTTP/1.1
> Range: bytes=aw
> User-Agent: curl/7.29.0
> Host: myurl
> Accept: */*
>
< HTTP/1.1 416 Requested Range Not Satisfiable
< Date: Fri, 13 Sep 2019 13:30:48 GMT
< Content-Type: text/html;charset=utf-8
< Content-Length: 957
< Connection: keep-alive
< Cache-Control: private
< Expires: Thu, 01 Jan 1970 01:00:00 CET
< Accept-Ranges: bytes
< Content-Range: bytes */2073
< Content-Language: en
< Server: unknown
<
* Connection #0 to host myurl left intact
<!DOCTYPE html><html><head><title> - Error report</title><style type="text/css">H1 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:22px;} H2 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:16px;} H3 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:14px;} BODY {font-family:Tahoma,Arial,sans-serif;color:black;background-color:white;} B {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;} P {font-family:Tahoma,Arial,sans-serif;background:white;color:black;font-size:12px;}A {color : black;}A.name {color : black;}.line {height: 1px; background-color: #525D76; border: none;}</style> </head><body><h1>HTTP Status 416 - </h1><div class="line"></div><p><b>type</b> Status report</p><p><b>message</b> <u></u></p><p><b>description</b> <u>The requested byte range cannot be satisfied.</u></p><hr class="line"><h3></h3></body></html>`

**Comment by lganzzzo** [comment]
@nicolaslopez15 ,

Is it possible to dump the successful response? So that it will be 200.
I want to the body of the response - possible it contains some unexpected for oatpp client stuff.

```bash
$ curl "https://<host>/mypath?myparameter=<param>" -v --raw -H "Content-Type: application/x-www-form-urlencoded" - H "Accept: application/json"
```

Thanks

**Comment by nicolaslopez15** [comment]
here the result:

`curl "https://myurl/openam/oauth2/tokeninfo?access_token=yyCX8Nw__hZCrMq737GH17lSnBU" -v --raw -H "Content-Type: application/x-www-form-urlencoded" -H "Accept: application/json"
* About to connect() to myurl port 443 (#0)
*   Trying 192.163.162.165...
* Connected to myurl (192.163.162.165) port 443 (#0)
* Initializing NSS with certpath: sql:/etc/pki/nssdb
*   CAfile: /etc/pki/tls/certs/ca-bundle.crt
  CApath: none
* SSL connection using TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
* Server certificate:
*       subject: CN=myurl,OU=XXXXX-ARC,O=GROUPE MYCOMPANY,L=Paris,ST=Ile de France,C=FR
*       start date: Apr 26 09:37:31 2018 GMT
*       expire date: Jun 27 09:37:31 2022 GMT
*       common name: myurl
*       issuer: CN=UniPass Server Authentication 2016 CA,O=GROUPE MYCOMPANY
> GET /openam/oauth2/tokeninfo?access_token=yyCX8Nw__hZCrMq737GH17lSnBU HTTP/1.1
> User-Agent: curl/7.29.0
> Host: myurl
> Content-Type: application/x-www-form-urlencoded
> Accept: application/json
>
< HTTP/1.1 200 OK
< Date: Fri, 13 Sep 2019 13:48:56 GMT
< Content-Type: application/json
< Connection: close
< Cache-Control: private
< Expires: Thu, 01 Jan 1970 01:00:00 CET
< X-Frame-Options: SAMEORIGIN
< Cache-Control: no-cache, no-store
< Accept-Ranges: bytes
< Vary: Accept-Charset, Accept-Encoding, Accept-Language, Accept
< Server: unknown
< Set-Cookie: SGR_tid=73e52bea9e1c5ff4fff7d92f5e9a0443; Domain=.world.xxxxxx; Path=/; Max-Age=1577840200
<
* Closing connection 0
{"access_token":"yyCX8Nw__hZCrMq737GH17lSnBU","api.sitirestapi.v1":"","grant_type":"client_credentials","auditTrackingId":"32493dd1-c2a3-41b2-9e4d-b02560e82088-15746442","scope":["api.sitirestapi.v1","xxx@@origin_network@@LAN"],"origin_network":"LAN","realm":"/","token_type":"Bearer","expires_in":508,"client_id":"40b05227-c9cb-499c-ba6b-0632f4f887b5"}`

**Comment by lganzzzo** [comment]
Hello @nicolaslopez15 ,

I have made a fully working "Github Client" example for you *(as I don't have access to your server)*.

```cpp

#include "oatpp-libressl/client/ConnectionProvider.hpp"
#include "oatpp-libressl/Config.hpp"
#include "oatpp-libressl/Callbacks.hpp"

#include "oatpp/web/client/HttpRequestExecutor.hpp"
#include "oatpp/web/client/ApiClient.hpp"
#include "oatpp/parser/json/mapping/ObjectMapper.hpp"
#include "oatpp/core/macro/codegen.hpp"

#include <csignal>

namespace {

#include OATPP_CODEGEN_BEGIN(ApiClient)

class GithubClient : public oatpp::web::client::ApiClient {

  API_CLIENT_INIT(GithubClient)

  API_CALL("GET", "users/{name}", getUser, PATH(String, name), HEADER(String, userAgent = "curl", "User-Agent"))

};

#include OATPP_CODEGEN_END(ApiClient)

}

void run() {
  
  /* set lockingCallback for libressl */
  oatpp::libressl::Callbacks::setDefaultCallbacks();
  
  /* ignore SIGPIPE */
  std::signal(SIGPIPE, SIG_IGN);

  auto config = oatpp::libressl::Config::createShared();
  auto connectionProvider = oatpp::libressl::client::ConnectionProvider::createShared(config, "api.github.com", 443);

  auto objectMapper = oatpp::parser::json::mapping::ObjectMapper::createShared();
  auto requestExecutor = oatpp::web::client::HttpRequestExecutor::createShared(connectionProvider);

  /* Create Client */
  auto client = GithubClient::createShared(requestExecutor, objectMapper);

  /* Make an API call */
  auto response = client->getUser("oatpp");

  OATPP_ASSERT(response);

  OATPP_LOGD("API_CALL", "status code=%d", response->getStatusCode());

  auto bodyText = response->readBodyToString();

  OATPP_LOGD("API_CALL", "string size=%d", bodyText->getSize());
  OATPP_LOGD("Api call", "string='%s'", bodyText->getData());
  
}

int main(int argc, const char * argv[]) {
  oatpp::base::Environment::init();
  run();
  oatpp::base::Environment::destroy();
  return 0;
}
```

Please note the default `HEADER(String, userAgent = "curl", "User-Agent")` header. Turns out that github API always responds with `403` and an empty body if there is no `user-agent` specified.

**Maybe** it is the case for your servers' API also - that it requires the `user-agent` to be set. (this is my best guess)

At least you have this example now, so you can try to debug the issue.

**Please let me know if it helped!**

Best Regards,
Leonid

**Comment by nicolaslopez15** [comment]
hi,

thanks for your answer, I'll try this!

i will revert to you if it solve my issue.

regards

**Comment by nicolaslopez15** [comment]
hello

i cannot contact github.com from my linux machine so i cannot run the exact same test.

Anyway it is still not working for me, error code 200 but string empty.
When i call an invalid url I have a body in the response but in HTML... as soon as i am supposed to receive JSON it is emtpy.

one question : is it possible to specify the HTTP version of the request?

thanks an regards

**Comment by lganzzzo** [comment]
Hey @nicolaslopez15 ,

The HTTP version is set by `oatpp::web::client::HttpRequestExecutor` and it is always `HTTP/1.1` - 
the same as used in your successful curl request.

Can you please dump all the headers that you obtain in the response - like this:
```cpp
  auto response = client->doGettokeninfoheader("application/x-www-form-urlencoded","application/json","PHOkrUhrhE-kz-ljWw5ci2SExSg");

  OATPP_ASSERT(response);

  for(auto& pair : response->getHeaders()) {
    auto key = pair.first.toString();
    auto value = pair.second.toString();
    OATPP_LOGD("Header", "key='%s', value='%s'", key->getData(), value->getData());
  }
```

And just curious what oatpp version do you use?

Regards,
Leonid

**Comment by nicolaslopez15** [comment]
Hi,
 
thanks for your support

i have cloned master last week, i am using version oatpp-0.19.8

response's headers:
```
 D | 1568627067541324| Header:key='Vary', value='Accept-Charset, Accept-Encoding, Accept-Language, Accept'
 D | 1568627067541401| Header:key='Accept-Ranges', value='bytes'
 D | 1568627067541411| Header:key='Set-Cookie', value='SGR_tid=d00e029a03704f552fd2255a5618c62d; Domain=.world.cpy; Path=/; Max-Age=1577840200'
 D | 1568627067541419| Header:key='Server', value='unknown'
 D | 1568627067541426| Header:key='Expires', value='Thu, 01 Jan 1970 01:00:00 CET'
 D | 1568627067541434| Header:key='Cache-Control', value='no-cache, no-store'
 D | 1568627067541456| Header:key='X-Frame-Options', value='SAMEORIGIN'
 D | 1568627067541471| Header:key='Connection', value='close'
 D | 1568627067541485| Header:key='Content-Type', value='application/json'
 D | 1568627067541494| Header:key='Date', value='Mon, 16 Sep 2019 09:44:27 GMT'
 D | 1568627067598227| temporary test for http  - oAuthConnect call:Status 200
```

**Comment by lganzzzo** [comment]
Hey @nicolaslopez15 ,

I identified what causes the issue:

- Server does-not send the `Content-Length` header.
- And current implementation of oatpp client requires `Content-Length` or `Transfer-Encoding: chunked` headers.

Thus it reads nothing from the response.

---

**It is a bug on oatpp side.**
**It should be fixable pretty simple.**

Will keep you updated on the progress.

Best Regards,
Leonid

**Comment by nicolaslopez15** [comment]
Hi Leonid

thanks!! it is a very good news to find the root cause of the issue. I am looking forward for the resolution.

thank you very much for your time.

regards

**Comment by lganzzzo** [comment]
Hello @nicolaslopez15 ,

I made a fix for this issue in the branch - https://github.com/oatpp/oatpp/tree/fix_120

Please checkout and verify it on your side.
Once verified I'll merge the PR to master.

Thanks you,
Leonid

**Comment by nicolaslopez15** [comment]
Hi Leonid,

it works fine! it can be merged
thanks a lot for your support, your library is very helpful.

regards,

**Comment by lganzzzo** [comment]
Hey @nicolaslopez15 ,

Cool, nice to hear that! Closing the issue...

You are also welcome to join devs-chat on Gitter for further discussions - https://gitter.im/oatpp-framework/Lobby

Best Regards,
Leonid
