### ISSUE TITLE
Is there an example using redis connection pool?

### ISSUE THREAD

**Issue by zjsxwc** [oatpp/oatpp#127]
I need to use redis in my project.
Is there an example using redis connection pool?

**Comment by lganzzzo** [comment]
Hello @zjsxwc ,

You may take one of the Redis C++ clients available and use them with oatpp. Just take the one that satisfies your needs the most. I guess it might be a connection pool functionality in some of these libraries. https://redis.io/clients#c--

Unfortunately there is no Redis example available in oatpp repositories. But it should not be a problem to use Redis with oatpp.

Best Regards,
Leonid

**Comment by madkote** [comment]
@lganzzzo I understand it is obvious, but having an example would simplify moving to oat++ a lot.

**Comment by lganzzzo** [comment]
Hello @madkote ,

Yes, it's a good idea to have an example with Redis, and we probably will add it in the future.
However, it's not in the current scope and I don't think it will be scheduled in the near future.

Regards,
Leonid
