### ISSUE TITLE
can our application response actively

### ISSUE THREAD

**Issue by wujinghe** [oatpp/oatpp#154]
my business application has own thread model. 
1. A thread is translating received messages to the internal structure, and put the request (the internal structure) into the inputing queue; 
2. the other thread which read the request from inputing queue  is responsible for business logical, and put the result into an outputting queue;
3. the third thread will read the result from the out queue, and call the send method to response to the client.

oatpp provide executor to execute business logical, and response directly. but we want to response in our thread. can oatpp support like this scenario?

**Comment by lganzzzo** [comment]
Hello @wujinghe ,

Thanks for the question!

Oat++ creates its threads to operate (receive a request and send back the response).

If you received the request on some endpoint `E` handled by the thread `T`, you should send back the response as the result of an endpoint `E` managed by the thread `T`.

If you have some queues in your business logic, then you can do like this (Simple API),
in your endpoint:

1. Receive Request
2. Enqueue Request 
3. Block and wait until the request is processed
4. Get a response from the queue 
5. Send the Response back to the Client.

Regards,
Leonid

**Comment by wujinghe** [comment]
Thank you so much!
Your advice is a good way. I think I can modify the source code to support my requirement, but it is not easy when I read the source code.
