### ISSUE TITLE
Any plans to support Content-Encoding gzip/deflate (ie. compression)?

### ISSUE THREAD

**Issue by jfixemer** [oatpp/oatpp#157]
Looking at different libraries to implement a server to support 250,000+ records (divided across pages of perhaps 10K records per page)  in XML or JSON data.  Boost::Beast is lower level (no endpoints, or DTO), no Swagger/OpenAPI, but does support compression. 

It looks like Beast did a port of zlib to C++...   

Perusing the Chunked, Mutipart and Simple web/*MessageBody files it doesn't look like there is any hook to add this cleanly as a module. 

Or do you expect application to see the header and decode the binary encoded compressed data block later?

**Comment by lganzzzo** [comment]
Hello @jfixemer ,

### Brief

Currently, in order to add support for `Content-Encoding` header on the framework level (so that the user gets it almost for free), we have to add a new abstraction layer for data processing, plus the dependency on the `zlib` in the main `oatpp` module. 
While adding an abstraction layer to make `Content-Encoding` feature pluggable may be a good idea. `zlib` should not go as a dependency of the main `oatpp` module. Instead, it should be added as an oatpp module ex. `oatpp-zlib`  (as you've mentioned).

### Effort

- Creating a new convenience abstraction layer in `oatpp` to make `Content-Encoding` feature pluggable is a matter of discussion and investigation.
- Creating a C++ wrapper for `zlib` should be pretty simple and straightforward. It depends on the functionality that should be covered.

### Workaround

Let's say that we don't have the convenience abstraction layer, but we do have the `oatpp-zlib` module (or whatever convenience API over zlib).
Then the endpoint code could look something like:

```cpp
#include "oatpp-zlib.hpp"

...

/* It is a hypothetical code. NOT a real example. */
ENDPOINT("GET", "/huge-document", getHugeDocument) {
  auto compressedData = oatpp::zlib::compress("my-huge-data", "gzip");
  auto response = createResponse(Status::CODE_200, compressedData);
  response->putHeader("Content-Encoding", "gzip");
  return response;
}
```

---

So this is the current situation.
Please let me know if you have any questions.

Regards,
Leonid

**Comment by jfixemer** [comment]
so for receiving data:
```C++
...
ENDPOINT( POST, "/data", setData,
    HEADER(String, encoding, "Content-Encoding"),
    BODY_STRING(String, input))
{
    if(toLower(encoding) == "gzip")
         content = gzip::uncompress(input);
    elseif(endcoding == "deflate")
         content = deflate::uncompress(input);
    else
         content = input;

     processes(content);
}

```

I guess the big downside is that if I wanted to use DTO mapping to parse JSON then I have to do so explicitly after the decompression  (I can't use the BODY_DTO(...))

Thanks for the pseudo-code example!

**Comment by jfixemer** [comment]
Thanks for the hints and feedback!

**Comment by lganzzzo** [comment]
Yes, you are correct.

Or the same but with `if`s moved to `decompress` method:

```cpp
#include "oatpp-zlib.hpp" // Unimplemented module.

...


ENDPOINT("POST", "/data", setData,
         HEADER(String, encoding, "Content-Encoding"),
         BODY_STRING(String, input))
{

  auto content = oatpp::zlib::decompress(imput->toLowerCase(), encoding); // hypothetical call
  // TODO - process content. Ex.: map content to DTO with ObjectMapper.
  return createResponse(Status::CODE_200, "OK");
}
```

> I guess the big downside is that if I wanted to use DTO mapping to parse JSON then I have to do so explicitly after the decompression (I can't use the BODY_DTO(...))

Yes, you are right. Unfortunately, in this case, you won't be able to use `BODY_DTO`.

Regards,
Leonid

**Comment by bhorn** [comment]
Wouldn't a call like
```
#include "oatpp-zlib.hpp" // Unimplemented module.

...


ENDPOINT("GET", "/zip", zip)
{

  auto content = "huge data";
  return createZippedResponse(Status::CODE_200, content);
}
```

Provided as a convenience function by oatpp-zlib more intuitive? Less prone to error by users.

However, having the abstraction layer to intercept and iE decompress the data sounds great.

**Comment by lganzzzo** [comment]
Hey!

The full support for `Content-Encoding` and `Accept-Encoding` headers is added.- commit https://github.com/oatpp/oatpp/commit/8a4fd7e57e440766b882ed5e497c83a2fe634189 .

The additional data-processing layer was introduced, so No changes should be done for user endpoints.

### The API

In the `AppComponents` file:

```cpp
#include "oatpp-zlib/EncoderProvider.hpp"

...

  OATPP_CREATE_COMPONENT(std::shared_ptr<oatpp::network::server::ConnectionHandler>, serverConnectionHandler)([] {

    OATPP_COMPONENT(std::shared_ptr<oatpp::web::server::HttpRouter>, router); // get Router component

    /* Create HttpProcessor::Components */
    auto components = std::make_shared<oatpp::web::server::HttpProcessor::Components>(router);

    /* Add content encoders */
    auto encoders = std::make_shared<oatpp::web::protocol::http::encoding::ProviderCollection>();

    encoders->add(std::make_shared<oatpp::zlib::DeflateEncoderProvider>());
    encoders->add(std::make_shared<oatpp::zlib::GzipEncoderProvider>());

    components->contentEncodingProviders = encoders;

    /* Add content decoders */
    auto decoders = std::make_shared<oatpp::web::protocol::http::encoding::ProviderCollection>();

    decoders->add(std::make_shared<oatpp::zlib::DeflateDecoderProvider>());
    decoders->add(std::make_shared<oatpp::zlib::GzipDecoderProvider>());

    components->bodyDecoder = std::make_shared<oatpp::web::protocol::http::incoming::SimpleBodyDecoder>(decoders);

    /* return HttpConnectionHandler */
    return std::make_shared<oatpp::web::server::HttpConnectionHandler>(components);
    
  }());

...

```

**Comment by bhorn** [comment]
Great work as always Leonid!

**Comment by lganzzzo** [comment]
Thanks!

**Comment by jfixemer** [comment]
Excellent!! 

Much better API than the workaround.

Thanks
