### ISSUE TITLE
install issue

### ISSUE THREAD

**Issue by pengtangtang** [oatpp/oatpp#161]
在我安装oatpp过程中出现以下错误。请帮忙解决
*English - I got the following error during my installation of oatpp. Please help*

![7`JD2G}%(B78XMJ_QQI0W3Y](https://user-images.githubusercontent.com/52857569/70435394-afe12680-1ac1-11ea-929c-bca841ab722a.png)

**Comment by bhorn** [comment]
Your compiler seems to be very old (4.6).
Please upgrade to a newer one (gcc8 would be best).

**Comment by pengtangtang** [comment]
thanks🌸🌸------------------ 原始邮件 ------------------
发件人: "Benedikt-Alexander Mokro&#xDF;"<notifications@github.com>
发送时间: 2019年12月10日(星期二) 上午10:11
收件人: "oatpp/oatpp"<oatpp@noreply.github.com>;
抄送: "pengtangtang"<pengtangtang@foxmail.com>;"Author"<author@noreply.github.com>;
主题: Re: [oatpp/oatpp] install issue (#161)



Your compiler seems to be very old (4.6).
 Please upgrade to a newer one (gcc8 would be best).
 
&mdash;

**Comment by lganzzzo** [comment]
Closing issue.
Please feel free to open another issue in case of any questions
