### ISSUE TITLE
How to make server port Configurable in runtime environment?

### ISSUE THREAD

**Issue by BossZou** [oatpp/oatpp#163]
I noticed that the `serverConnectionProvider` is created by "use Dependency Injection" like:

```cpp
class AppComponent {
public:

  /**
   *  Create ConnectionProvider component which listens on the port
   */
  OATPP_CREATE_COMPONENT(std::shared_ptr<oatpp::network::ServerConnectionProvider>, serverConnectionProvider)([] {
    return oatpp::network::server::SimpleTCPConnectionProvider::createShared(8000);
  }());

 ..........
```

However, I think that the server port must be specified in the way of "hard code". It's true? I want the port can be Configurable in runtime. How can I do?

**Comment by lganzzzo** [comment]
Hello @BossZou ,

As an example, you can provide port as the command line argument:

#### AppComponent.hpp
```cpp
#include "oatpp/core/base/CommandLineArguments.hpp"
#include "oatpp/core/utils/ConversionUtils.hpp"

...

class AppComponent {
private:
  oatpp::base::CommandLineArguments m_cmdArgs;
public:
  AppComponent(const oatpp::base::CommandLineArguments& cmdArgs)
    : m_cmdArgs(cmdArgs)
  {}
public:

  /**
   *  Create ConnectionProvider component which listens on the port
   */
  OATPP_CREATE_COMPONENT(std::shared_ptr<oatpp::network::ServerConnectionProvider>, serverConnectionProvider)([] {
    v_int32 port = oatpp::utils::conversion::strToInt32(m_cmdArgs.getNamedArgumentValue("--port", "8000" /* default value */));
    return oatpp::network::server::SimpleTCPConnectionProvider::createShared(port);
  }());

 ..........
```

#### App.cpp

```cpp
void run(const oatpp::base::CommandLineArguments& args) {
  
  /* Create app components configurable with command line args */
  AppComponent components(args); 

  ...

}

int main(int argc, const char * argv[]) {

  oatpp::base::Environment::init();

  /* Pass command line args */
  run(oatpp::base::CommandLineArguments(argc, argv));

  oatpp::base::Environment::destroy();
  
  return 0;
}
```

Please let me know if you have more questions.

Regards,
Leonid

**Comment by BossZou** [comment]
Thank you. I solved it.

**Comment by YundongGai** [comment]
> 

Hello lganzzzo,
I have tried this code segment for configuring IP address and port. However, I find there is an bug when compiling. It reports "'this' was not captured for this lambda function" not detected. If I add "&" in the '[]' which represents the capture list of lambda function, it compiles successfully.

**Comment by lganzzzo** [comment]
Hello @YundongGai ,

It's an old code.
Now you should do it like this:

https://github.com/oatpp/example-crud/blob/2cba24c250ce5a9c4247e271dec870ed32a580d0/src/AppComponent.hpp#L48

**Comment by YundongGai** [comment]
> 

Hello @lganzzzo,

Thanks for your reply. For me, after the revision I mentioned before, the old code can work. However, I do not know how to configure IP address and port using the new code.

**Comment by lganzzzo** [comment]
Hello @YundongGai ,

The same way as in old example:

```cpp
v_int32 port = oatpp::utils::conversion::strToInt32(m_cmdArgs.getNamedArgumentValue("--port", "8000" /* default value */));
return oatpp::network::tcp::server::ConnectionProvider::createShared({"0.0.0.0", port, oatpp::network::Address::IP_4});
```

**Comment by YundongGai** [comment]
> 



> Hello @YundongGai ,
> 
> The same way as in old example:
> 
> ```c++
> v_int32 port = oatpp::utils::conversion::strToInt32(m_cmdArgs.getNamedArgumentValue("--port", "8000" /* default value */));
> return oatpp::network::tcp::server::ConnectionProvider::createShared({"0.0.0.0", port, oatpp::network::Address::IP_4});
> ```

Hello, @lganzzzo ,
Thanks for your reply. It seems that there is a SwaggerComponent and a DatabaseComponent added in the new AppComponent.hpp file. One more question, what are these new components for?

**Comment by shaiquie-zieye** [comment]
@lganzzzo I'm confused by your replies... what @YundongGai says about lambda capturing still holds. Moreover I wanted to stress that the `m_cmdArgs` declaration order is important, it must happens before the `OATPP_CREATE_COMPONENT` definition that uese it.

**Comment by lganzzzo** [comment]
Hello guys, @shaiquie-zieye ,

Now I'm confused too:)
Please post some code example to make sure we are all talking the same thing
