### ISSUE TITLE
How to run in swagger ui?

### ISSUE THREAD

**Issue by BossZou** [oatpp/oatpp#165]
I used your framework to generate a swagger website. After started the service locally, I find out that there are some problems about the end point. I input some parameters and press the execute button but nothing happens. Is there any necessary step that I missed account to this situation? Here is my code: 
```cpp
/**
 *  Swagger ui is served at
 *  http://host:port/swagger/ui
 */
class SwaggerComponent {
 public:

    /**
     *  General API docs info
     */
    OATPP_CREATE_COMPONENT(std::shared_ptr<oatpp::swagger::DocumentInfo>, swaggerDocumentInfo)([] {

        oatpp::swagger::DocumentInfo::Builder builder;

        builder
            .setTitle("Milvus web service")
            .setDescription("Milvus API Example project with swagger docs")
            .setVersion("0.1")
            .setContactName("Ivan Ovsyanochka")
            .setContactUrl("https://oatpp.io/")

            .setLicenseName("Apache License, Version 2.0")
            .setLicenseUrl("http://www.apache.org/licenses/LICENSE-2.0")

            .addServer("http://0.0.0.0:9999", "server on all client");

        return builder.build();

    }());

    OATPP_CREATE_COMPONENT(std::shared_ptr<oatpp::swagger::Resources>, swaggerResources)([] {
        return oatpp::swagger::Resources::loadResources(OATPP_SWAGGER_RES_PATH);
    }());
};
```

And i launch my server:
```cpp
Config& config = Config::GetInstance();
    std::string port;
    Status status;

    status = config.GetServerConfigWebPort(port);
    AppComponent components(atoi(port.c_str()));

    /* create ApiControllers and add endpoints to router */
    auto router = components.httpRouter.getObject();

    auto doc_endpoints = oatpp::swagger::Controller::Endpoints::createShared();

    auto user_controller = WebController::createShared();
    user_controller->addEndpointsToRouter(router);

    doc_endpoints->pushBackAll(user_controller->getEndpoints());

    auto swaggerController = oatpp::swagger::Controller::createShared(doc_endpoints);
    swaggerController->addEndpointsToRouter(router);

    /* create server */
    server_ptr_ = std::make_unique<oatpp::network::server::Server>(components.serverConnectionProvider.getObject(),
                                                                   components.serverConnectionHandler.getObject());

    // start asynchronously
    server_ptr_->run();
```

**Comment by lganzzzo** [comment]
Hello @BossZou ,

Please make sure that the server address and port that you've passed to the `.addServer("http://0.0.0.0:9999", "server on all client");` call is the same address/port that your actual server is running on. Swagger-UI will make calls on the server that you provided.

Swagger UI selected server:
<img width="278" alt="Screenshot 2019-12-18 at 10 55 50" src="https://user-images.githubusercontent.com/5940640/71071444-4e861b00-2185-11ea-9158-07f243c86916.png">

Browser address bar:
<img width="176" alt="Screenshot 2019-12-18 at 10 56 15" src="https://user-images.githubusercontent.com/5940640/71071481-5fcf2780-2185-11ea-8bf3-1cc284cf371d.png">

---

If it's not the case, then make sure that your server is actually returning any response.
Also, you can play with the working Swagger-UI example - https://github.com/oatpp/example-crud

---

Please let me know if it helped.

Best Regards,
Leonid

**Comment by lganzzzo** [comment]
Closing issue. 
Feel free to reopen in case you have more questions on this matter.

**Comment by BossZou** [comment]
I tried working Swagger-UI example, but it dosen't work also.

Here is the result:
![Screenshot from 2019-12-19 20-13-19](https://user-images.githubusercontent.com/40255591/71172796-29d09700-229c-11ea-9a83-94f456f16293.png)

the version of oatpp is latest.

**Comment by bhorn** [comment]
For CORS, 'localhost' is not '127.0.0.1'!
In your screenshot you opened '127.0.0.1', but your API is located at 'localhost'. Thus, your browser blocks the AJAX-Call to 'localhost' because you are on '127.0.0.1' (they are two different address for your browser!)

So either set your API-Url to '127.0.01' or just open 'localhost:8000' in your browser.

Also please read some REST-API handbooks that cover the most basic problems like CORS and other related stuff. This way your progress will be much quicker then waiting for replies.

**Comment by BossZou** [comment]
Thanks. I add CORS in end points and the swagger ui work well.

**Comment by clarkholdham** [comment]
@lganzzzo Is there any way to host the swagger on every interface IP? The same way one can create a server::ConnectionProvider in the core oatpp. Basically we are running on a machine with multiple interfaces all connected via DHCP so we just want to host swagger on all ports as we do for our main endpoint.
