### ISSUE TITLE
Is there any comparetion with microsoft cpprestsdk

### ISSUE THREAD

**Issue by laoshanxi** [oatpp/oatpp#167]
I used cpprestsdk before that is a little bit heavy, is there any difference between those two ?

https://github.com/Microsoft/cpprestsdk

Thanks a lot.

**Comment by lganzzzo** [comment]
Hello @laoshanxi ,

Thanks for the question!

In brief, Oat++ is one of its kind. 
It provides unique features that none of the other C++ frameworks do:

- Advanced REST controllers and request mappings - see [Api Controller](https://oatpp.io/docs/components/api-controller/)
- Auto-generated Swagger-UI for API Controllers - see [Endpoint Annotation and API Documentation](https://oatpp.io/docs/components/api-controller/#endpoint-annotation-and-api-documentation)
- Retrofit/Feign like client - see [Api Client](https://oatpp.io/docs/components/api-client/)
- Object mapping and DTOs - see [DTO](https://oatpp.io/docs/components/dto/)

Also, Oat++ is focused on performance.

You are welcome to join Oat++ dev community on Gitter - https://gitter.im/oatpp-framework/Lobby#
There you might find people who tried/migrated from CPP REST SDK.

Cheers,
Leonid

**Comment by laoshanxi** [comment]
Cool, I used cpprestsdk in a C++ backend REST app, and I am looking for reduce the 3rd party dependencies.
https://github.com/laoshanxi/app-manager

Thanks for the explain.

> 
> 
> Hello @laoshanxi ,
> 
> Thanks for the question!
> 
> In brief, Oat++ is one of its kind.
> It provides unique features that none of the other C++ frameworks do:
> 
>     * Advanced REST controllers and request mappings - see [Api Controller](https://oatpp.io/docs/components/api-controller/)
> 
>     * Auto-generated Swagger-UI for API Controllers - see [Endpoint Annotation and API Documentation](https://oatpp.io/docs/components/api-controller/#endpoint-annotation-and-api-documentation)
> 
>     * Retrofit/Feign like client - see [Api Client](https://oatpp.io/docs/components/api-client/)
> 
>     * Object mapping and DTOs - see [DTO](https://oatpp.io/docs/components/dto/)
> 
> 
> Also, Oat++ is focused on performance.
> 
> You are welcome to join Oat++ dev community on Gitter - https://gitter.im/oatpp-framework/Lobby#
> There you might find people who tried/migrated from CPP REST SDK.
> 
> Cheers,
> Leonid

Cool, I used cpprestsdk in a C++ backend REST app, and I am looking for reduce the 3rd party dependencies.
https://github.com/laoshanxi/app-manager

Thanks for the explain.
