### ISSUE TITLE
Server crashed when the request body is incorrect

### ISSUE THREAD

**Issue by BossZou** [oatpp/oatpp#172]
I define a Dto as:
```cpp
class TableRequestDto : public oatpp::data::mapping::type::Object {

    DTO_INIT(TableRequestDto, Object)

    DTO_FIELD(String, table_name, "table_name");
    DTO_FIELD(Int64, dimension, "dimension");
    DTO_FIELD(Int64, index_file_size, "index_file_size");
    DTO_FIELD(Int64, metric_type, "metric_type");
};
```

And my endpoint is as follow:
```cpp
ENDPOINT("POST", "/tables", CreateTable,
         BODY_DTO(TableRequestDto::ObjectWrapper, table_schema)) {

        auto status_dto = handler_->CreateTable(table_schema);
        std::shared_ptr<OutgoingResponse> response;
        if (0 != status_dto->code) {
            response = createDtoResponse(Status::CODE_400, status_dto);
        } else {
            response = createDtoResponse(Status::CODE_201, status_dto);
        }

        CORS_SUPPORT(response);
        return response;

    }
```

When I send a request which request body doesn't contains field `metric_type`, just like:
```
{
  "table_name": "string",
  "dimension": 0,
  "index_file_size": 0
}
```
However, my server crashed.

![segmentfault](https://user-images.githubusercontent.com/40255591/71508579-3cae2180-28c3-11ea-86d0-137c3747532d.png)

And the console print:
```
Signal: SIGSEGV (Segmentation fault)
```

Why. And how to catch the exception

**Comment by lganzzzo** [comment]
Hello @BossZou ,

According to your stack-trace you have a crash in your user code:

```
milvus::server::web::WebRequestHandler::CreateTable line: 313
```

I guess you have to check `metric_type` for `nullptr` in WebRequestHandler.

Regards,
Leonid

**Comment by BossZou** [comment]
Oh, I see.  Thank you

**Comment by bhorn** [comment]
One note:
It seems like you have an custom macro or function called CORS_SUPPORT.
Did you know oatpp already provides an full-featured solution compatible with oatpp-swagger, that generates the necessary OPTION-endpoints, too? 

Take a look at the [Controller-Tests](https://github.com/oatpp/oatpp/blob/master/test/oatpp/web/app/Controller.hpp) where the CORS-macro is used.
