### ISSUE TITLE
How to disable message  output in console ?

### ISSUE THREAD

**Issue by BossZou** [oatpp/oatpp#174]
I found the server output a message to console when I try to close it:
```
 D |2020-01-05 19:18:49 1578223129596260| Server:Already stopped. Closing connection...
```

How to disable it?

**Comment by lganzzzo** [comment]
Hey @BossZou ,

You can disable all debug level logs for your release build.
To do this, you can build the main `oatpp` module with `-DOATPP_DISABLE_LOGD` flag enabled.

Add the following to the oatpp/CMakeLists.txt file

```cmake
add_definitions (
  -DOATPP_DISABLE_LOGD
)
```

I guess we have to include this as an option in the cmake build script...

Regards,
Leonid

**Comment by BossZou** [comment]
I see. But `oatpp` is a third party in  my project, I have no access to change oatpp/CMakeLists.txt adding any cmake definitions. Any workaround here ?

**Comment by lganzzzo** [comment]
Hello @BossZou ,

I can see that you've added this in your fork https://github.com/BossZou/oatpp/commit/5f90b312899b09fbc1efae4c64e1521d11dee755 .
That's exactly what you need.

Later I'll add an option to CMakeLists.txt for this.

Regards,
Leonid
