### ISSUE TITLE
Which content-type support in oatpp?

### ISSUE THREAD

**Issue by BossZou** [oatpp/oatpp#175]
I found content-type `application/json` `text/plain` and so on. Is there any diagram or sheet to list whole content-type supported in project ? And any examples to show how to use with them?

**Comment by lganzzzo** [comment]
Hello @BossZou ,

The `content-type` HTTP header hints the client what type of content is included in the response.

In oatpp, when you create a response with `createDtoResponse()` method, the `ObjectMapper` injected in the `Controller` knows what kind of the content it produces during the serialization, and will include the 
`content-type` header in the response automatically.

In other cases, you have to include `content-type` manually or, just let the client guess what the content type of the response.

To include `content-type` header in the response:

```cpp
ENDPOINT("GET", "/", root) {
  auto response = createResponse(Status::CODE_200, "Hello World!!!");
  response->putHeader(Header::CONTENT_TYPE, "text/plain");
  return response;
}
```

The list of possible content types you can find [here](https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/MIME_types)

Best Regards,
Leonid

**Comment by BossZou** [comment]
I see. Thank you.
