### ISSUE TITLE
Does async endpoint support CORS ?

### ISSUE THREAD

**Issue by BossZou** [oatpp/oatpp#176]
Now I'm using async endpoint in my server, I add `ADD_CORS(...)` in the front of every async endpoint, but it seems not work. How should I do ?

**Comment by lganzzzo** [comment]
Hello @BossZou ,

`ADD_CORS` is not supported for Async endpoints.
`ADD_CORS_ASYNC` should be added for Async endpoint - but this feature is not implemented yet.

Workarounds may be:
- Add CORS specific logic manually.
- Contribute `ADD_CORS_ASYNC` - by analogy with `ADD_CORS` see [cors_define.hpp](https://github.com/oatpp/oatpp/blob/master/src/oatpp/codegen/api_controller/cors_define.hpp)
- Wait for `ADD_CORS_ASYNC`

Regards,
Leonid

**Comment by BossZou** [comment]
I add CORS manually by invoking `putHeaderIfNotExists()` and `putHeader`,  but my server crash directly and output anything in console. I have no idea .

**Comment by lganzzzo** [comment]
Please share the code snippet

**Comment by BossZou** [comment]
Here is my CORS macros:
```
    do {                                                                                                    \
        response->putHeaderIfNotExists("Access-Control-Allow-Methods", "GET, POST, PUT, OPTIONS, DELETE");  \
        response->putHeaderIfNotExists("Access-Control-Allow-Origin", "*");                                 \
        response->putHeaderIfNotExists("Access-Control-Max-Age", "1728000");                               \
    } while(false);
```

I found when I place 
```
response->putHeader("access-control-allow-headers",                                     \
            "DNT, User-Agent, X-Requested-With, If-Modified-Since, "                            \
            "Cache-Control, Content-Type, Range, Authorization");                               \
```

my server exit directly.

**Comment by BossZou** [comment]
I found the server will exit directly as long as you add field `access-control-*` into response header. I have removed field `access-control-allow-headers` but the server still crash. I think it's a bug.

**Comment by lganzzzo** [comment]
Can you share the whole endpoint code?

This is an example of working endpoint - I just created:

```cpp
  ENDPOINT_ASYNC("GET", "/hello", Root) {
    
    ENDPOINT_ASYNC_INIT(Root)
    
    Action act() override {

      auto dto = MessageDto::createShared();
      dto->statusCode = 200;
      dto->message = "Hello World Async!";

      auto response = controller->createDtoResponse(Status::CODE_200, dto);

      response->putHeaderIfNotExists("Access-Control-Allow-Methods", "GET, POST, PUT, OPTIONS, DELETE");
      response->putHeaderIfNotExists("Access-Control-Allow-Origin", "*");
      response->putHeaderIfNotExists("Access-Control-Max-Age", "1728000");

      return _return(response);
    }
    
  };
```

**Comment by lganzzzo** [comment]
@BossZou ,

// I found the server will exit directly as long as you add field access-control-* into response header. I have removed field access-control-allow-headers but the server still crash. I think it's a bug.

Please share the whole macro.

I guess at the moment when you call `response->...` the response in `nullptr`

**Comment by lganzzzo** [comment]
Also, if you have Async endpoint you should use `ENDPOINT_INTERCEPTOR_ASYNC` as a base for your macro, not the `ENDPOINT_INTERCEPTOR`.

**Comment by BossZou** [comment]
Here is my CORS macros:
```
# define CORS_SUPPORT(RESPONSE)                                                                             \
    do {                                                                                                    \
        response->putHeaderIfNotExists("Access-Control-Allow-Methods", "GET, POST, PUT, OPTIONS, DELETE");  \
        response->putHeaderIfNotExists("Access-Control-Allow-Origin", "*");                                 \
        response->putHeaderIfNotExists("Access-Control-Max-Age", "1728000");                               \
    } while(false);
```

And here is one of my async endpoint:
```
    ENDPOINT_INFO(CreateTable) {
        info->summary = "Create table";

        info->addConsumes<TableRequestDto::ObjectWrapper>("application/json");

        info->addResponse<TableFieldsDto::ObjectWrapper>(Status::CODE_201, "application/json");
        info->addResponse<StatusDto::ObjectWrapper>(Status::CODE_400, "application/json");
    }

    ENDPOINT_ASYNC("POST", "/tables", CreateTable) {
     ENDPOINT_ASYNC_INIT(CreateTable);

        Action
        act()
        override {
            return request->readBodyToDtoAsync<TableRequestDto>(controller->getDefaultObjectMapper())
                .callbackTo(&CreateTable::returnResponse);
        }

        Action returnResponse(const TableRequestDto::ObjectWrapper& body) {
            WebRequestHandler handler = WebRequestHandler();
            handler.RegisterRequestHandler(::milvus::server::RequestHandler());

            auto status_dto = handler.CreateTable(body);
            std::shared_ptr<OutgoingResponse> response;
            if (0 != status_dto->code) {
                response = controller->createDtoResponse(Status::CODE_400, status_dto);
            } else {
                response = controller->createDtoResponse(Status::CODE_201, status_dto);
            }

            CORS_SUPPORT(response);
            return _return(response);
        }
    };
```

**Comment by lganzzzo** [comment]
Is there any stack-trance?

**Comment by BossZou** [comment]
It's strange that the bug occurred when I only complie my code on release mode. It doesn't appear when I compile on debug mode. So there is no  stack-trance.

**Comment by lganzzzo** [comment]
Strange...

Try to modify your macro like this:

```cpp
# define CORS_SUPPORT(RESPONSE) \
    do { \
        RESPONSE->putHeaderIfNotExists(oatpp::String("Access-Control-Allow-Methods"), oatpp::String("GET, POST, PUT, OPTIONS, DELETE"));  \
        RESPONSE->putHeaderIfNotExists(oatpp::String("Access-Control-Allow-Origin"), oatpp::String("*")); \
        RESPONSE->putHeaderIfNotExists(oatpp::String("Access-Control-Max-Age"), oatpp::String("1728000")); \
    } while(false);
```
- Add - `oatpp::String("")` so that it will copy the constant in it's own memory.
- Change `response` to `RESPONSE` to use the actual macro variable

**Comment by BossZou** [comment]
I try change `response` to `RESPONSE` and bug still exists on release mode.

**Comment by lganzzzo** [comment]
Hey @BossZou ,

I've also mentioned some points that might be helpful for you on Gitter in private chat.

**Comment by lganzzzo** [comment]
Convenience macro `ADD_CORS_ASYNC` should be added 
based on the `ENDPOINT_INTERCEPTOR_ASYNC`

**Comment by lganzzzo** [comment]
Starting from `1.2.5` the [Enable Global CORS](https://github.com/oatpp/oatpp/blob/master/changelog/1.2.5.md#enable-global-cors) option is available for any kind of endpoints.
