### ISSUE TITLE
Does this project support listen IPv6 address?

### ISSUE THREAD

**Issue by laoshanxi** [oatpp/oatpp#177]
Thanks so much.

**Comment by lganzzzo** [comment]
Hello @laoshanxi ,

Currently, the `SimpleTCPConnectionProvider` provides no option to choose the address to bind to. It defaults to localhost - see the [code](https://github.com/oatpp/oatpp/blob/master/src/oatpp/network/server/SimpleTCPConnectionProvider.hpp#L95)

But I think it's a must-have feature. 
So it should be added eventually.

Regards,
Leonid

**Comment by lganzzzo** [comment]
Not sure if I interpreted the original question correctly.
My original thought was that the question is about binding to an interface specifying the address.

In any case, I'm closing this one as a duplicate in favor of #250 .

@laoshanxi , please feel free to comment on #250 in case you have any ideas/propositions.

**Comment by laoshanxi** [comment]
Thanks, #250 does addressed this issue.
