### ISSUE TITLE
Server crash in release mode

### ISSUE THREAD

**Issue by BossZou** [oatpp/oatpp#179]
I add CORS in my server, and it crashed when it run in release mode. I located where code crash:
```
"oatpp/core/data/share/LazyStringMap.hpp" 
Method: bool putIfNotExists(const Key& key, const StringKeyLabel& value){...}
```
```cpp
  bool putIfNotExists(const Key& key, const StringKeyLabel& value) {

    std::lock_guard<concurrency::SpinLock> lock(m_lock);

      auto it = m_map.find(key);   // crash here

    if(it == m_map.end()) {
      m_map.insert({key, value});
        m_fullyInitialized = false;
      return true;
    }


    return false;
  }
```

which is invoked here:
```cpp
bool Request::putHeaderIfNotExists(const oatpp::data::share::StringKeyLabelCI_FAST& key, const oatpp::data::share::StringKeyLabel& value) {
    return m_headers.putIfNotExists(key, value);
}
```

I found CORS header `Access-Control-Allow-Origin` put successfully but `Access-Control-Allow-Methods` crash when run code ` auto it = m_map.find(key); `. It seems that `oatpp::web::protocol::http::Header::CORS_METHODS` cause bug.

**Comment by lganzzzo** [comment]
Hello @BossZou ,

It's very likely that you have a memory leak. It seems like your application is trying to access resources that are already freed.

If you have it reproduced in release mode only it might be that some variables are optimized-out and freed before you expect it.

That's my best guess...

I would suggest putting logs into the destructor of `AppComponents` and into destructor of your `Controller` to see if the destructor is triggered before you request your endpoint.

Regards,
Leonid

**Comment by BossZou** [comment]
I'd like to know the processing procedure of oatpp when a request comes, such as the stack trace of function invoked.

**Comment by bhorn** [comment]
Then fire up the debugger of your IDE, place a breakpoint in that function and look at the stacktrace. But Leonids answer suggest that your `m_map` isn't allocated yet or already destroyed.

**Comment by BossZou** [comment]
I found a possible reason which cause server crash: The Cmake compile option. I Integrate oatpp and pass cmake compile option of mine ! When I add `-O3`, I found compiler optimize the code which result in crash !  

```
  template<>
  struct hash<oatpp::data::share::StringKeyLabelCI> {
    
    typedef oatpp::data::share::StringKeyLabelCI argument_type;
    typedef v_word32 result_type;
    
    result_type operator()(oatpp::data::share::StringKeyLabelCI const& s) const noexcept {
      
      p_char8 data = s.getData();
      v_buff_size size4 = s.getSize() >> 2;
      
      result_type result = 0;
      
      for(v_buff_size i = 0; i < size4; i++) {
        result ^= (*((p_word32) data) | 538976288); // 538976288 = 32 | (32 << 8) | (32 << 16) | (32 << 24);
        data += 4;
      }
      
      for(v_buff_size i = 0; i < s.getSize() - (size4 << 2); i++ ) {
        ((p_char8) &result)[i] ^= (data[i] | 32);
      }
      
      return result;
    }
  };
```
In the function, I noticed in for loop variable `i` is optimized out when  I compile with parameters `-O3`. So unordered_map crash with segment fault.

May be think about that try to optimize make?

**Comment by lganzzzo** [comment]
Hey @BossZou ,

What is your OS, and compiler?

I compiled with clang on MAC with -O3, and I can't reproduce the issue. Oatpp runs fine.

**Comment by BossZou** [comment]
My OS: Linux - 5.0.0-37-generic - x86_64 / Ubuntu 18.04
compiler: gcc version 7.4.0

**Comment by lganzzzo** [comment]
Hey @BossZou ,

You were right. I have accidentally managed to reproduce the bug with hash-functions when added the ubuntu 18.04 to the CI.
Strange, but it was reproducing only on CI - ubuntu 18.04 (even in debug mode). On all other VMs with ubuntu 18.04 that I've tried, it was not reproduced.

Nevertheless, I have changed the hash functions and it was fixed.
See the commit - https://github.com/oatpp/oatpp/pull/187/commits/d200e60eb6bf49b6ff632cc9f2ab0d3f14b89c17 
Please feel free to reopen this issue or create a new one in case it's still reproducible for you.

Best Regards,
Leonid
