### ISSUE TITLE
Does oatpp support unsigned value type?

### ISSUE THREAD

**Issue by BossZou** [oatpp/oatpp#184]
I fount oatpp only support `string`, `int8`, `int16`, .... . It seem that unsigned type is not supported. How to deserialize to unsigned value?

**Comment by lganzzzo** [comment]
Hello @BossZou ,

Unsigned mapping-enabled types are planned to be added for the oatpp version `1.0.0`. Which is scheduled for the end of Jan/mid-Feb. So just wait for a bit :)

Regards,
Leonid

**Comment by BossZou** [comment]
Can you support an option in CmakeLists.txt which allow to disable log out

And I found that `ADD_CORS` only support `GET`, `POST`, `OPTIONS`, so can I customize what method supported?

**Comment by lganzzzo** [comment]
> Can you support an option in CmakeLists.txt which allow to disable log out
> And I found that ADD_CORS only support GET, POST, OPTIONS, so can I customize what method supported?

Please create a separate issue for both, so that they won't get lost.

---

About `ADD_CORS` - please find the docs here - https://oatpp.io/docs/components/api-controller/#cors
You can specify all CORS params.

Customize allowed methods:
```cpp
  ADD_CORS(root, "*", "GET, POST, PUT, DELETE")
  ENDPOINT("GET", "/", root) {
    return createDtoResponse(Status::CODE_200, "Hello!");
  }
```

Regards,
Leonid

**Comment by lganzzzo** [comment]
Hey @BossZou ,

Unsigned Integers were added to the oatpp in this PR - https://github.com/oatpp/oatpp/pull/187

Regards,
Leonid
