### ISSUE TITLE
How to accept files uploaded by users.

### ISSUE THREAD

**Issue by gergul** [oatpp/oatpp#185]
Could you give me an example please.

**Comment by gergul** [comment]
I see it.

**Comment by lganzzzo** [comment]
Hello @gergul ,

There are two ways to upload a file:

1. Post binary body:

```cpp
  ENDPOINT("POST", "/", postBody, BODY_STRING(String, body)) {
    // TODO do something with binary data contained in the 'body'
    return createResponse(Status::CODE_200, "File uploaded");
  }
```

2. Multipart upload - info is here - https://oatpp.io/docs/features/upload-file/#simple-api-multipart-upload


Regards,
Leonid

**Comment by gergul** [comment]
Thank you for your conscientious.
