### ISSUE TITLE
Only to say that it is a great project

### ISSUE THREAD

**Issue by prsolucoes** [oatpp/oatpp#193]
Hi,

Only to say that it is a great project, don't abandon it like crow was abandoned

Thanks.

**Comment by bhorn** [comment]
Hi there,

Thanks for the nice words, @lganzzzo will surely be flattered ;)

Oat++ is in active development. @lganzzzo released Oat++1.0.0 just earlier this month. We have further things in mind. First some improvements as always. Another big goal are multiple great modules to ease the adaption of oatpp even more. The big picture for Oat++ would be to support cloud-architectures as well as embedded/IoT systems. 
We are always happy about suggestions and feature requests.

**Comment by lganzzzo** [comment]
Thank you so much!

As @bhorn mentioned - we have more things to do!
So please don't worry - oatpp is not going to be abandoned.

Best Regards,
Leonid

**Comment by prsolucoes** [comment]
Thanks.
