### ISSUE TITLE
Set-Cookie header multiple times

### ISSUE THREAD

**Issue by miketolkachev** [oatpp/oatpp#196]
In file: oatpp/web/protocol/http/incoming/Request.hpp

# Question

How to set multiple headers with same name?
For example:
```
auto res = createDtoResponse(Status::CODE_200, user);
res->putHeader("Set-Cookie", "token=dsgflk879453yrewActive;");
res->putHeader("Set-Cookie", "active=true;");
return res;
```
After that i have first cookie "token" only.

I looked into RFC6265:
> An origin server can include multiple
> Set-Cookie header fields in a single response.  The presence of a
> Cookie or a Set-Cookie header field does not preclude HTTP caches
> from storing and reusing a response.
> 
> Origin servers SHOULD NOT fold multiple Set-Cookie header fields into
> a single header field.  The usual mechanism for folding HTTP headers
> fields (i.e., as defined in [RFC2616]) might change the semantics of
> the Set-Cookie header field because the %x2C (",") character is used
> by Set-Cookie in a way that conflicts with such folding.

**Comment by lganzzzo** [comment]
Hello @miketolkachev ,

Currently, oatpp uses key-->value map for headers. Thus there is a limitation that you can't  have multiples <header-name> --> <header-value> pairs.

The workaround is to put all cookie values under the sample header entry (using `;` separator):

```cpp
auto res = createDtoResponse(Status::CODE_200, user);
res->putHeader("Set-Cookie", "token=dsgflk879453yrewActive; active=true");
return res;
```

It is a valid header value and all clients should support this.

Best Regards,
Leonid

**Comment by lganzzzo** [comment]
I am closing this issue.
@miketolkachev please feel free to reopen in case there are more questions on this mater.

Regards,
Leonid
