### ISSUE TITLE
[featured] Support dor Conan

### ISSUE THREAD

**Issue by prsolucoes** [oatpp/oatpp#197]
Hi,

Can you add support for conan deps manager?

Oficial repo link if you want:
https://github.com/conan-io/conan-center-index

Thanks.

**Comment by lganzzzo** [comment]
Hello @prsolucoes ,

It may be a good idea to add support for conan.
It is not on a schedule at the moment, but if someone decides to contribute this feature - I'll provide all the necessary assistance.

Regards,
Leonid

**Comment by lganzzzo** [comment]
Update:
The `library request` has been added to the conan-center-index repo https://github.com/conan-io/conan-center-index/issues/1228 
thanks to @ZaMaZaN4iK

**Comment by frek818** [comment]
@lganzzzo I built a candidate PR for this issue. Do you mind adding a review? https://github.com/conan-io/conan-center-index/pull/1677

**Comment by lganzzzo** [comment]
Hey @frek818 ,

That's great!
Please find my review in that PR.

And thank you for contributing!

Regards,
Leonid

**Comment by lganzzzo** [comment]
And the main oatpp module is merged to master!
https://github.com/conan-io/conan-center-index/pull/1677

All thanks to @frek818 :tada::tada::tada:

**Comment by lganzzzo** [comment]
Closing this issue.
