### ISSUE TITLE
How to test "GET" and "POST" with an bearer authorization

### ISSUE THREAD

**Issue by chenqingguo** [oatpp/oatpp#210]
Hey,

I create "GET" and "POST" with bearer authorization，How to test them with using API?
I will put my code later.
Thanks

**Comment by chenqingguo** [comment]
And I also want to know how to use API after I build thoes servers—POST GET... just like the test demo you provide?

**Comment by lganzzzo** [comment]
Hello @chenqingguo ,

> I create "GET" and "POST" with bearer authorization，How to test them with using API?

Let's assume you have an endpoint:

```cpp
ENDPOINT("GET", "bearer-auth", auth,
         AUTHORIZATION(std::shared_ptr<DefaultBearerAuthorizationObject>, authObject)) {
  if(authObject->token == "4e99e8c12de7e01535248d2bac85e732") {
    return createResponse(Status::CODE_200, "OK");
  } else {
    return createResponse(Status::CODE_401, "Unauthorized");
  }
}
```

Now you can test it whether manually or you can write unit tests.

### Test Manually

With invalid token 
```bash
curl http://localhost:8000/bearer-auth -H "Authorization: Bearer some-invalid-token" -v              
*   Trying ::1...
* TCP_NODELAY set
* Connected to localhost (::1) port 8000 (#0)
> GET /bearer-auth HTTP/1.1
> Host: localhost:8000
> User-Agent: curl/7.64.1
> Accept: */*
> Authorization: Bearer some-invalid-token
> 
< HTTP/1.1 401 Unauthorized
< Content-Length: 12
< Connection: keep-alive
< Server: oatpp/1.0.0
< 
```

**Comment by lganzzzo** [comment]
@chenqingguo ,

As for this question:
> And I also want to know how to use API after I build thoes servers—POST GET... just like the test demo you provide?

I'm not sure I understand the question.
Please give more details - what you mean `use API`, which `those servers`, and please
specify which exact demo you are referring to.

Best Regards,
Leonid

**Comment by chenqingguo** [comment]
@lganzzzo 
Thank you for your quick reply.
Here is my ENDPOINT
```
ENDPOIT("POST","/data",my_post,
BODY_DTO(ResultType::ObjectWrapper,post_data),
AUTHORIZATION(std::shared_ptr<MyAuthorizationObject>,authObject))
{
    return createDtoResponse(Status::CODE_201,post_data);
}
```
I want to use client to call application APIs
```
API_CALL("post","/data",my_post)
...
auto response=client->my_post();
OATPP_ASSERT(response->getStatusCode()==201);
...
```
The test response ofcourse is unauthorized, because I don't provid a token. 
By the way, I use postman with bearer authorization and josn data, and it works.

 ```
auto response = MyClient->bearerAuth("valid-token");
OATPP_ASSERT(response->getStatusCode() == 200);
```
I will try this.
> Please note that for the real-life case you will also need to use HTTPS.

Thank you for your kind reminding.

**Comment by lganzzzo** [comment]
Hey @chenqingguo ,

Please don't forget to add the `AUTHORIZATION` parameter to your client `API_CALL` in order to pass bearer token:

```cpp
...
API_CALL("POST", "/data", postBodyWithAuth, BODY_DTO(MyDto::ObjectWrapper, body), AUTHORIZATION(String, token, "Bearer"))
...
auto response = MyClient->postBodyWithAuth(bodyObject, tokenString);
OATPP_ASSERT(response->getStatusCode() == 200);
```

Regards,
Leonid

**Comment by chenqingguo** [comment]
Thank you very much.
@lganzzzo 
I have json data like 
```
{
"id": 1,
"feature":[132.12,0.1,12.1,21.555,... ]
"location":["left":45,"top":34,...]
...
}
```
DTO doesn't support vector, can DTO deal with my situation?
If can't , I have to use rapidJson?

**Comment by bhorn** [comment]
Well, at first, your JSON is incorrect! It should be

```json
{
"id": 1,
"feature":[132.12,0.1,12.1,21.555],
"location":{"left":45,"top":34}
}
```
For `location` it should be an object `{}`, not an array `[]`!

Second, when you have those arrays or objects your DTO would look something like this:
```c++
class MyDTO : public oatpp::data::mapping::type::Object {
  DTO_INIT(MyDTO, Object);

  DTO_FIELD(Int64, id);
  DTO_FIELD(List<Float32>::ObjectWrapper, feature);
  DTO_FIELD(Fields<Int64>::ObjectWrapper, location);
  // ...
};
```

`List<Float32>::ObjectWrapper` is used to represent an array of floats `[132.3,0.16,13.37]`.
The `Fields<Int64>::ObjectWrapper` represents an object with arbitrary fields `{"key":value<Int63>}`. `Fields<T>` can be used if you want to accept an object-style "array" where you don't know the keys.
However, if you know the keys beforehand, I strongly suggest to implement them as a DTO, too:

```
class LocationDTO  : public oatpp::data::mapping::type::Object {
  DTO_INIT(LocationDTO, Object);
  DTO_FIELD(Int64, left);
  DTO_FIELD(Int64, top);
  DTO_FIELD(Int64, right);
  DTO_FIELD(Int64, bottom);
  // ... what ever you need
}
class MyDTO : public oatpp::data::mapping::type::Object {
  DTO_INIT(MyDTO, Object);

  DTO_FIELD(Int64, id);
  DTO_FIELD(List<Float32>::ObjectWrapper, feature);
  DTO_FIELD(LocationDTO::ObjectWrapper, location); // now your "location" is also typed as DTO!
  // ...
};
```

**Comment by chenqingguo** [comment]
@bhorn 
Thanks.
my DTO
```
class ObjectDTO  : public oatpp::data::mapping::type::Object {
  DTO_INIT(LocationDTO, Object);
  DTO_FIELD(Int64, left);
  DTO_FIELD(Int64, top);
  DTO_FIELD(Int64, right);
  DTO_FIELD(Int64, bottom);
  DTO_FIELD(List<String>::ObjectWrapper, feature);
}
class ObjectsDTO : public oatpp::data::mapping::type::Object {
  DTO_INIT(ObjectsDTO , Object);
 DTO_FIELD(List<ObjectDTO  ::ObjectWrapper>::ObjectWrapper, objects);
};
```
and my data structure define
```
class Object{
Int64 left;
...
List<string> feature;
}
class Objects{
List<Object> objects;
}
```
How to put the DTO data in my class, or How to Serialize / Deserialize them.
Can Serialize / Deserialize replace json parse?

**Comment by bhorn** [comment]
@chenqingguo why would you need your data structure? You can use the DTO in you whole project and don't need to copy data around if you do not have to.

First of all, you have an error in your DTO! Your DTO is namend ObjectDTO but you INIT a DTO namend LocationDTO! Either rename your DTO-Class to LocationDTO or change the init to ObjectDTO.

```c++
class ObjectDTO  : public oatpp::data::mapping::type::Object {
  DTO_INIT(LocationDTO, Object);
  // [...]
}
```

Second, take a look at our tests and examples. Here is a test that basically shows the complete usage of the DTOs: https://github.com/oatpp/oatpp/blob/master/test/oatpp/parser/json/mapping/DTOMapperTest.cpp

---

Anyhow, creating DTOs with `List<T>` for serialization is a bit tricky since you have to manually initialise those lists.

```c++
// Create your ObjectsDTO
auto dto = ObjectsDTO::createShared();
dto->objects = List<ObjectDTO::ObjectWrapper>::createShared(); // this creates a new list of the type of dto->objects and stores it

// Example for one ObjectDTO
auto obj = ObjectDTO::createShared();
obj->left = 24;
obj->top = 200;
obj->feature =  List<String>::createShared();
obj->feature->pushBack("feat1");
obj->feature->pushBack("feat2");

// add ObjectDTO to ObjectsDTO:
dto->pushBack(obj);
```

However, you can skip the manual initialisation of the lists when you define your DTO to have th fields have default values:

```c++
class ObjectDTO  : public oatpp::data::mapping::type::Object {
  DTO_INIT(ObjectDTO, Object);
  DTO_FIELD(Int64, left);
  DTO_FIELD(Int64, top);
  DTO_FIELD(Int64, right);
  DTO_FIELD(Int64, bottom);
  DTO_FIELD(List<String>::ObjectWrapper, feature) = List<String>::createShared();
}
class ObjectsDTO : public oatpp::data::mapping::type::Object {
  DTO_INIT(ObjectsDTO , Object);
  DTO_FIELD(List<ObjectDTO::ObjectWrapper>::ObjectWrapper, objects) = List<ObjectDTO::ObjectWrapper>::createShared();;
};
```

Now you can serialize your DTO to a string with an objectmapper:
```
oatpp::String json = [your mapper]->writeToString(dto);
```

or to use an API-Call:
```c++
auto response = MyClient->postBodyWithAuth(dto, tokenString);
```

You should really look up all our examples and the tests of Oat++! They are a rich resource and basically an FAQ for the most basic questions.

**Comment by chenqingguo** [comment]
Well,
I need to get data users post to me,then I put the data to other function as a input,so I have to transfer data. I use `BODY_STRING`to get String and parse it by rapidjson.

**Comment by lganzzzo** [comment]
I'm closing this issue.
@chenqingguo , please feel free to reopen in case you have more questions on this matter.
