### ISSUE TITLE
How can I add description for Status::Code?

### ISSUE THREAD

**Issue by codderembedded** [oatpp/oatpp#212]
For example;
![image](https://user-images.githubusercontent.com/49305144/78242124-2333fb80-74ea-11ea-8cb6-e1bff66aa24c.png)

**Comment by bhorn** [comment]
The PR for this feature is merged :)
You can add your own description as 3th argument to `addResponse`:

```c++
  ENDPOINT_INFO(root) {
    info->summary = "root_summary";
    info->addResponse<String>(Status::CODE_200, "text/plain", "Your custom description");
    info->addResponse<String>(Status::CODE_404, "text/plain"); // can be left out to use the default http status code text
  }
  ENDPOINT("GET", "/", root) {
    return createResponse(Status::CODE_200, "test");
  }
```

**Comment by codderembedded** [comment]
But it doesn't let me write it as the 3rd argument.

**Comment by codderembedded** [comment]
Thank you very much

**Comment by codderembedded** [comment]
I changed the code but the description is not visible when I run it

**Comment by bhorn** [comment]
@coderembedded Have you updated `oatpp-swagger` too?

**Comment by codderembedded** [comment]
I opened oatpp-swagger and changed the changed codes. what should I do?

**Comment by bhorn** [comment]
@codderembedded You have to update both repositories (`oatpp` and `oatpp-swagger`) to the newest release/commit, not just `oatpp`.

**Comment by codderembedded** [comment]
it happened now. Thank you
