### ISSUE TITLE
Path Variables Mapping

### ISSUE THREAD

**Issue by alfredtofu** [oatpp/oatpp#215]
crow supports path variables for multi-level, does oatpp have similar functions? For example, if define as follow:
```
  CROW_ROUTE(app, "/file/<path>")
```
then this router can process `/file/a`, `/file/a/b/` and `/file/a/b/c`.

Here are the definition in crow: https://github.com/ipkn/crow/blob/49edf898a5b9a39a0d69072cc2434c4f23692908/include/crow/routing.h#L790

**Comment by alfredtofu** [comment]
I found that `ENDPOINT("GET", "/file/*"` well supoorted it.

**Comment by DruncBread** [comment]
i tried `ENDPOINT("GET", "cstask/raw-image/{path}", getRawImg, PATH(String, path, "path")) {}` but it didnt work......can you give an example?

**Comment by DruncBread** [comment]
i tried `ENDPOINT("GET", "user/image/*", userImg, PATH(String, path, "*")) {} ` but it didnt work.......... can you give an example?
