### ISSUE TITLE
Recent PR may be causing example project build failures

### ISSUE THREAD

**Issue by james-balnaves-rocketinsights** [oatpp/oatpp#216]
PR https://github.com/oatpp/oatpp/pull/214
may be causing the example projects (e.g., https://github.com/oatpp/example-hls-media-stream) to fail to build with the error:
```make
[ 12%] Building CXX object CMakeFiles/hls-example-lib.dir/src/Utils.cpp.o
/Users/james/Projects/example-hls-media-stream/src/Utils.cpp:19:25: error: no member named 'empty' in
      'oatpp::data::mapping::type::String'
  return oatpp::String::empty();
         ~~~~~~~~~~~~~~~^
/Users/james/Projects/example-hls-media-stream/src/Utils.cpp:51:25: error: no member named 'empty' in
      'oatpp::data::mapping::type::String'
  return oatpp::String::empty();
         ~~~~~~~~~~~~~~~^
2 errors generated.
make[2]: *** [CMakeFiles/hls-example-lib.dir/src/Utils.cpp.o] Error 1
make[1]: *** [CMakeFiles/hls-example-lib.dir/all] Error 2
make: *** [all] Error 2```

**Comment by lganzzzo** [comment]
Hey @james-balnaves-rocketinsights ,

You are 💯 right.
We'll fix it shortly. Meanwhile, you can just change `oatpp::String::empty()` to `nullptr`.

Thanks for letting us know!

Regards,
Leonid

**Comment by lganzzzo** [comment]
Hey @james-balnaves-rocketinsights ,

Example projects have been updated.
Thanks for you attention!

Regards,
Leonid
