### ISSUE TITLE
Server start fail with `Couldn't not open a socket`

### ISSUE THREAD

**Issue by BossZou** [oatpp/oatpp#217]
I try run my application program in server machine and it failed. And I add more detail log as follow:
![oatpp-fail](https://user-images.githubusercontent.com/40255591/78642137-d2a31080-78e4-11ea-8c1d-585658fa3577.png)

The output in console is like:
![071-bug](https://user-images.githubusercontent.com/40255591/78642226-f403fc80-78e4-11ea-82b9-9d2f71c4b29f.png)

I'm confused.

**Comment by lganzzzo** [comment]
Hey @BossZou ,

Looks interesting,
What is the machine you are trying to run the application on?

- Operation System?
- Is it a virtual machine?

**Comment by BossZou** [comment]
My system is Centos7.4, and I run my server in docker container. @lganzzzo

**Comment by lganzzzo** [comment]
Please give me the name of the Docker image - for me to test.
I mean the image you extend `FROM <image-name>`

**Comment by BossZou** [comment]
@lganzzzo `milvusdb/milvus:0.7.1-cpu-d040120-d2fad1`

**Comment by lganzzzo** [comment]
Also, I like the detailed logging that you've added in 
your branch https://github.com/oatpp/oatpp/compare/master...BossZou:test,
So please feel free to create a pull-request

**Comment by bhorn** [comment]
According to just the error message, I would assume that there is an issue with IPv4 and IPv6 in your container/host.

**Comment by BossZou** [comment]
I noticed specify ipv6:
```
memset(&hints, 0, sizeof(hints));
hints.ai_family = AF_INET6;  // TODO: here
hints.ai_socktype = SOCK_STREAM;
hints.ai_protocol = 0;
hints.ai_flags = AI_PASSIVE;
```
why?

**Comment by lganzzzo** [comment]
Hello @BossZou ,

According to the docs, using `AF_INET6` will also allow ipv4 clients to connect to the server.
From https://tools.ietf.org/html/rfc3493 

**3.7 Compatibility with IPv4 Nodes**
```
Applications may use AF_INET6 sockets to open TCP connections to IPv4
nodes, or send UDP packets to IPv4 nodes, by simply encoding the
destination's IPv4 address as an IPv4-mapped IPv6 address, and
passing that address, within a sockaddr_in6 structure, in the
connect() or sendto() call.  When applications use AF_INET6 sockets
to accept TCP connections from IPv4 nodes, or receive UDP packets
from IPv4 nodes, the system returns the peer's address to the
application in the accept(), recvfrom(), or getpeername() call using
a sockaddr_in6 structure encoded this way.
```

However, I may be missing something here.

Is it works for you when you specify `ipv4` explicitly?
Or you still getting the same error?

Regards,
Leonid

**Comment by BossZou** [comment]
@lganzzzo  I found `ipv6` is disable is the machine where server fail. After enabling `ipv6`, my server work well.

**Comment by bhorn** [comment]
Of course setting `.ai_familiy` to `AF_INET6` only works if the Kernel has IPv6 enabled. I would assume in this particular setup, IPv6 is build in the kernel but not enabled.

**Comment by lganzzzo** [comment]
Please follow the linked issue - #250
