### ISSUE TITLE
example-async-api

### ISSUE THREAD

**Issue by mynameischaos** [oatpp/oatpp#221]
run demo but got this error, please help me. 

[oatpp::network::server::SimpleTCPConnectionProvider::instantiateServer()]:Error. Couldn't open a socket: socket(10, 1, 6) Address family not supported by protocol

**Comment by lganzzzo** [comment]
Hello @mynameischaos ,

Please provide more details about the system you are running on.
- OS
- Is it a virtual machine / docker / or a regular machine

Regards,
Leonid

**Comment by lganzzzo** [comment]
Please follow the linked issue - #250
