### ISSUE TITLE
how to do redirect 

### ISSUE THREAD

**Issue by alfredtofu** [oatpp/oatpp#224]
how can I redirect like this: https://stackoverflow.com/questions/14343812/redirecting-to-url-in-flask

**Comment by lganzzzo** [comment]
Hello @alfredtofu ,

Just use the status code `Status::CODE_302` and set the `Location` header.

```cpp
ENDPOINT("GET", "/", root) {
  auto response = createResponse(Status::CODE_302, "");
  response->putHeader("Location", "http://www.example.com");
  return response;
}
```

Regards,
Leonid
