### ISSUE TITLE
Multiple inheritance support

### ISSUE THREAD

**Issue by ryomatcu** [oatpp/oatpp#256]
Hi, thank you for the great framework.

Do you have any plans for multiple inheritance?
I want support for multiple inheritance like a below:

```cpp
  DTO_INIT(User, Foo, Bar)
```

Thanks.

**Comment by lganzzzo** [comment]
Hey @ryomatcu ,

Thanks for the question!

We didn't investigate that. There might be some challenges handling diamond dependencies in DTOs. But we didn't look at this precisely.

It's not in the scope currently as it's a pretty rare case to have a need for multiple inheritence in DTOs.

**It would be very helpfull If you could post your example to better understand possible use-cases.**

**Also, please note:**

While at the moment you can't inherit fields from multiple DTOs, you still can inherit behavior from multiple Non-DTO classes. Meaning that you can do like this:

```cpp
class Printable {
public:
  virtual void print() = 0;
}

class MyDto : public oatpp::DTO, public Printable { //< You can inherit behavior from multiple classes

  DTO_INIT(MyDto, DTO) //< But you have only one DTO fields inheritance vertical

  DTO_FIELD(String, text);

public:

  void print() override {
    std::cout << text->c_str() << std::endl;
  }

};
```

**Comment by ryomatcu** [comment]
Hi, @lganzzzo 

Thank you for answering!

I understood that multiple inheritance is not in scope.
I'll consider another way. I'll also contact you if I'll find more questions.

Thank you.
