### ISSUE TITLE
The max simultaneous connections of simple API

### ISSUE THREAD

**Issue by chenqingguo** [oatpp/oatpp#259]
Simple API has a disadvantage -  comparable smaller limit of max simultaneous connections. When the conections go over 200, I got this message "sorry, too many clients already." What's the limit of max simultaneous conections. Maybe I should choose Async API?

**Comment by lganzzzo** [comment]
Hello @chenqingguo ,

200 is a too small number even for simple API.
Most probably you have an open-file-descriptor limit being set to 256 in your system.

use the following command to increase the limit:

```bash
$ ulimit -n <max-open-file-descriptors-number>
```

Then, max connections for simple API will be limited by the max number of threads your system can spawn.

Regards,
Leonid

**Comment by chenqingguo** [comment]
Thanks @lganzzzo，

well, the value of open files is set to 1024 in my system. 
I increase the limit `ulimit -n 10240` in the terminal where oatpp server run, but it dosen't work.

**Comment by lganzzzo** [comment]
Hey @chenqingguo ,

I read your initial message more carefully and noticed the message `sorry, too many clients already.` - is not an oatpp message - oatpp doesn't have such a message.

So it might be a problem with your client application.

Also, make sure that you apply `ulimit` before the application start.
And in both terminal window for client and for server, in case you running those from different terminal windows.

**Comment by chenqingguo** [comment]
@lganzzzo ,
There are connections to postgres in my server, I gusses the message is from postgreSQL.
Here is the whoe message:


server=oatpp/1.0.0
code=500
description=Internal Server Error
message=FATAL: sorry, too many clients already

**Comment by lganzzzo** [comment]
Hey @chenqingguo ,

Take a look here - https://stackoverflow.com/questions/30778015/how-to-increase-the-max-connections-in-postgres

You have to increase prostgres `max-connections`.
However, it's not the best idea to create many connections to DB. You should use a connection-pool to database for better performance and resource efficiency.

**Comment by chenqingguo** [comment]
@lganzzzo ,
That's great.
Thank you very much.
