### ISSUE TITLE
BufferOutputStream::reserveBytesUpfront() is inefficient

### ISSUE THREAD

**Issue by srogatch** [oatpp/oatpp#262]
I tried to upload a moderate volume of data via POST requests to an `oatpp`-based web service. The volume is: ~114MBytes/minute, it's ~20 requests/minute each ~5.7MBytes. However, `oatpp` in this case loads almost 100% of a Ryzen 7 PRO 3700 CPU with 16 logical cores.
Profiling shows the following:
![oatpp_BufferOutputStream_reserveBytesUpfront](https://user-images.githubusercontent.com/5251612/85919540-a4462900-b874-11ea-8fbc-752146c2de0b.png)
The version of oatpp used is 1.0.0 .
Is there a workaround for this bug, e.g. can I somehow make Request::readBodyToString() to allocate a large buffer at once so to eliminate the need for reallocation (e.g. make the buffer size equal to the size of the unencoded POST body)? Or maybe is there a way to increase the growth rate for the BufferOutputStream used?

**Comment by lganzzzo** [comment]
Hello @srogatch ,

This bug was fixed - please see this issue https://github.com/oatpp/oatpp/issues/198
Just take this commit - https://github.com/oatpp/oatpp/commit/56f4d667a93e68d7a7d88e9a562e1a2bf86c43da - it's still `1.0.0`

Please let me know if it helped.

Regards,
Leonid

**Comment by srogatch** [comment]
Thanks, @lganzzzo ! It looks like the time to upgrade to v1.1.0 for me. I'll let you know about the results.
Anyway, if you still depend on `memcpy`, please, consider the following replacement:
```
#include <immintrin.h>
#include <intrin.h>

namespace oatpp {
  template<bool taCacheStore, bool taCacheLoad> __declspec(noalias) static inline
    void Copy256(void* const __restrict pStore, const void* const __restrict pLoad, size_t nVects)
  {
    const __m256i* __restrict pSrc = static_cast<const __m256i*>(pLoad);
    __m256i* __restrict pDest = static_cast<__m256i*>(pStore);
    for (; nVects > 0; nVects--, pSrc++, pDest++) {
      const __m256i loaded = taCacheLoad ? _mm256_loadu_si256(pSrc) : _mm256_stream_load_si256(pSrc);
      taCacheStore ? _mm256_storeu_si256(pDest, loaded) : _mm256_stream_si256(pDest, loaded);
    }
    if (!taCacheStore) {
      _mm_sfence();
    }
  }

  template<bool taCacheStore, bool taCacheLoad> __declspec(noalias) static inline
    void FastCopy(void* const __restrict pStore, const void* const __restrict pLoad, const size_t nBytes)
  {
    const size_t nVectsDown = nBytes / sizeof(__m256i);
    Copy256<taCacheStore, taCacheLoad>(pStore, pLoad, nVectsDown);
    const size_t nCopiedBytes = nVectsDown * sizeof(__m256i);
    memcpy(static_cast<char*>(pStore) + nCopiedBytes, static_cast<const char*>(pLoad) + nCopiedBytes,
      nBytes - nCopiedBytes);
  }
}
```
Its performance is discussed at https://stackoverflow.com/a/44948720/1915854

**Comment by lganzzzo** [comment]
Hey,
Thanks for the code snippet, I'll investigate it!

**Comment by srogatch** [comment]
After upgrading to `oatpp 1.1.0` I'm getting the following compilation errors and warnings when linking with my DLL:
```1>LINK : warning C4743: 'class oatpp::data::mapping::type::Type `static class oatpp::data::mapping::type::Type * __ptr64 __cdecl oatpp::data::mapping::type::__class::String::getType(void)'::`2'::type' has different size in 'C:\Work\imported\src\oatpp-1.1.0\src\oatpp\web\protocol\http\http.cpp' and 'C:\Work\common\guardedrequesthandler.cpp': 64 and 56 bytes
1>LINK : warning C4743: 'class oatpp::data::mapping::type::Type `static class oatpp::data::mapping::type::Type * __ptr64 __cdecl oatpp::data::mapping::type::__class::String::getType(void)'::`2'::type' has different size in 'C:\Work\imported\src\oatpp-1.1.0\src\oatpp\core\data\mapping\type\primitive.cpp' and 'C:\Work\common\guardedrequesthandler.cpp': 64 and 56 bytes
1>LINK : warning C4743: 'class oatpp::data::mapping::type::Type `static class oatpp::data::mapping::type::Type * __ptr64 __cdecl oatpp::data::mapping::type::__class::String::getType(void)'::`2'::type' has different size in 'C:\Work\imported\src\oatpp-1.1.0\src\oatpp\core\utils\conversionutils.cpp' and 'C:\Work\common\guardedrequesthandler.cpp': 64 and 56 bytes
1>LINK : warning C4743: 'class oatpp::data::mapping::type::Type `static class oatpp::data::mapping::type::Type * __ptr64 __cdecl oatpp::data::mapping::type::__class::String::getType(void)'::`2'::type' has different size in 'C:\Work\imported\src\oatpp-1.1.0\src\oatpp\core\parser\caret.cpp' and 'C:\Work\common\guardedrequesthandler.cpp': 64 and 56 bytes
1>LINK : warning C4743: 'class oatpp::data::mapping::type::Type `static class oatpp::data::mapping::type::Type * __ptr64 __cdecl oatpp::data::mapping::type::__class::String::getType(void)'::`2'::type' has different size in 'C:\Work\imported\src\oatpp-1.1.0\src\oatpp\core\data\stream\chunkedbuffer.cpp' and 'C:\Work\common\guardedrequesthandler.cpp': 64 and 56 bytes
1>   Creating library C:\Work\x64\Release\Common.lib and object C:\Work\x64\Release\Common.exp
1>GuardedRequestHandler.obj : error LNK2001: unresolved external symbol "public: __cdecl oatpp::data::mapping::type::Type::Type(class oatpp::data::mapping::type::ClassId const &,char const *)" (??0Type@type@mapping@data@oatpp@@QEAA@AEBVClassId@1234@PEBD@Z)
1>C:\Work\x64\Release\Common.dll : fatal error LNK1120: 1 unresolved externals```

I built `oatpp` with the following commands:
```mkdir build
cmake .. -G"Visual Studio 16 2019" -A x64 -DCMAKE_INSTALL_PREFIX=C:/Work/Imported/install/oatpp
```

Could you help to resolve this, @lganzzzo ?

**Comment by lganzzzo** [comment]
Hey @srogatch ,

Do you have your DLL built? Does it depend on oatpp?

How does your dependency graph look like?
```
- oatpp
   |
   |- DLL
       |
       |- App
```

Have you rebuilt your DLL after updating the oatpp?

**Comment by srogatch** [comment]
Yes, my EXE depends on my DLL and `oatpp` static lib, and my DLL depends on `oatpp` static lib too. I am getting these error and warnings when rebuilding the DLL and the EXE (for both projects). One detail: when building `oatpp` I set in MSVS the language standard to "Latest Draft".

**Comment by srogatch** [comment]
Oh, sorry, I've understood the problem: it is happening because the `include` files get placed into a different directory for v1.1.0 and v1.0.0. Let me fix this and get back to you...

**Comment by lganzzzo** [comment]
Yes, oatpp installs each version to a different directory.

For `1.0.0` everything goes to folders sufficed with `1.0.0` - `oatpp-1.0.0/...`
For `1.1.0` everything goes to `oatpp-1.1.0/...`

The new version won't override files from old version

**Comment by srogatch** [comment]
Thank you, after fixing the `oatpp` include files placement, my build is successful. Just a few warnings in the files I include:
```1>C:\Work\Imported\include\oatpp\core\data\mapping\type\Primitive.hpp(134,25): warning C4389: '!=': signed/unsigned mismatch
1>C:\Work\Imported\include\oatpp\core\data\share\MemoryLabel.hpp(190,15): warning C4389: '!=': signed/unsigned mismatch
1>C:\Work\Imported\include\oatpp\core\data\share\MemoryLabel.hpp(244,15): warning C4389: '!=': signed/unsigned mismatch
1>C:\Work\Imported\include\oatpp\core\data\share\MemoryLabel.hpp(300,15): warning C4389: '!=': signed/unsigned mismatch
```
Would you like to fix these? Or I can do this and submit a pull request.
There are also a lot of compiler warnings when compiling 64-bit with Warning level 4 and Latest Draft standard in MSVS2019.

**Comment by lganzzzo** [comment]
Hey @srogatch , 

It would be great, if you could contribute this!
The windows build is pretty rich on warnings, and it's a good idea to get rid of those.

Regards,
Leonid

**Comment by srogatch** [comment]
Sure, @lganzzzo . I'm then closing this issue and will try to fix the warnings where I can.

**Comment by bamkrs** [comment]
> Thanks, @lganzzzo ! It looks like the time to upgrade to v1.1.0 for me. I'll let you know about the results.
> Anyway, if you still depend on `memcpy`, please, consider the following replacement:
> 
> ```c++
> #include <immintrin.h>
> #include <intrin.h>
> 
> namespace oatpp {
>   template<bool taCacheStore, bool taCacheLoad> __declspec(noalias) static inline
>     void Copy256(void* const __restrict pStore, const void* const __restrict pLoad, size_t nVects)
>   {
>     const __m256i* __restrict pSrc = static_cast<const __m256i*>(pLoad);
>     __m256i* __restrict pDest = static_cast<__m256i*>(pStore);
>     for (; nVects > 0; nVects--, pSrc++, pDest++) {
>       const __m256i loaded = taCacheLoad ? _mm256_loadu_si256(pSrc) : _mm256_stream_load_si256(pSrc);
>       taCacheStore ? _mm256_storeu_si256(pDest, loaded) : _mm256_stream_si256(pDest, loaded);
>     }
>     if (!taCacheStore) {
>       _mm_sfence();
>     }
>   }
> 
>   template<bool taCacheStore, bool taCacheLoad> __declspec(noalias) static inline
>     void FastCopy(void* const __restrict pStore, const void* const __restrict pLoad, const size_t nBytes)
>   {
>     const size_t nVectsDown = nBytes / sizeof(__m256i);
>     Copy256<taCacheStore, taCacheLoad>(pStore, pLoad, nVectsDown);
>     const size_t nCopiedBytes = nVectsDown * sizeof(__m256i);
>     memcpy(static_cast<char*>(pStore) + nCopiedBytes, static_cast<const char*>(pLoad) + nCopiedBytes,
>       nBytes - nCopiedBytes);
>   }
> }
> ```
> 
> Its performance is discussed at https://stackoverflow.com/a/44948720/1915854

I highly advise against using intrinsics here. While I love using them myself, this is not the right place. Just think about the complications we can and will run into just because the msvc isn't capable of using the underlying hardware correctly. Sure we can implement some more ifdef and refactor everything to use our own memcopy. But if we really want to dig down this rabbit hole, we should go all the was and also implement our own (hardened) malloc etc.
However, to keep Oat++ as platform independent as possible - by now - I suggest to let the compiler decide what is best.

**Comment by lganzzzo** [comment]
After taking a closer look, and reviewing the proposed memcpy solution, I would agree with @bamkrs .
However, we can keep this option it in mind for future performance optimizations.
