### ISSUE TITLE
ORM. DbClient - unified interface to access databases.

### ISSUE THREAD

**Issue by lganzzzo** [oatpp/oatpp#264]
# ql::Client

`oatpp::ql::Client` - is the unified interface to access databases that support any kind of Query Language (e.x. SQL, N1QL, CQL, etc.). `oatpp::ql::Client` is similar to [ApiClient](https://oatpp.io/docs/components/api-client/) but for databases.

## API

The main `oatpp` module should provide three components:
- `oatpp::ql::Client` - base implementation for QL clients.
- `oatpp::ql::Executor` - base implementation for database-request executors.
- `QL` codegen.

### Example

Declare database client:

```cpp
#include OATPP_CODEGEN_BEGIN(QL) ///< Begin code-gen section

class MyDbClient : public oatpp::ql::Client {

  ...

  QUERY(getUserById,
        "SELECT * FROM user WHERE userId=:userId",
        PARAM(String, userId))

  QUERY(deleteUserById,
        "DELETE FROM user WHERE userId=:userId",
        PARAM(String, userId))

}

#include OATPP_CODEGEN_END(QL) ///< End code-gen section
```

Use the declared database client:

```cpp
#include "oatpp-postgresql/Executor"

...

auto executor = std::make_shared<oatpp::postgresql::Executor>(...)
MyDbClient dbClient(executor);

auto dbResponse = dbClient.getUserById("<userId>");

if(dbResponse->isSuccess()) {
  auto user = dbResponse->toDto<UserDTO>();
}
```

## Things to consider

- Provided functionality must support different dialects and must correctly handle things like string escape for different dialects.

**Comment by lganzzzo** [comment]
Work on the draft has started in [ql_client_draft](https://github.com/oatpp/oatpp/tree/ql_client_draft) branch.

**Comment by nicraMarcin** [comment]
@lganzzzo are you going to provide database connection pool to keep configurable open and ready to execute connections?

**Comment by lganzzzo** [comment]
@nicraMarcin , 

> are you going to provide database connection pool to keep configurable open and ready to execute connections?

Yes. The connection pool functionality is going to be provided on the level of `Executor`. 
Most probably It's going to be DB specific. But we'll try to keep interfaces the same for all executors if possible.

**Comment by nicraMarcin** [comment]
Maybe this will be good example https://github.com/malikkirchner/connection-pool

**Comment by lganzzzo** [comment]
Thanks, I'll check it out!

**Comment by lganzzzo** [comment]
The API is ready to test in the `v_1.2.0` branch.
Also the [oatpp-sqlite](https://github.com/oatpp/oatpp-sqlite) adapter is also ready for beta-testing.

## API

For more detailed docs see - https://oatpp.io/docs/components/orm/

### Declaration

```cpp
#include "oatpp/orm/SchemaMigration.hpp"
#include "oatpp/orm/DbClient.hpp"
#include "oatpp/core/macro/codegen.hpp"

#include OATPP_CODEGEN_BEGIN(DbClient) ///< Begin code-gen section

class MyClient : public oatpp::orm::DbClient {
public:

  MyClient(const std::shared_ptr<oatpp::orm::Executor>& executor)
    : oatpp::orm::DbClient(executor)
  {
    oatpp::orm::SchemaMigration migration(executor); // Init schema using SchemaMigration
    migration.addFile(1, "sql/initial_schema.sql");
    migration.addFile(2, "sql/schema_fix_1.sql");
    migration.migrate();
  }

  /**
   * Declare create user method
   */
  QUERY(createUser,
        "INSERT INTO users (name, email, role) VALUES (:name, :email, :role);", // SQL-template
        PARAM(oatpp::String, name), PARAM(oatpp::String, email), PARAM(oatpp::Enum<UserRoles>::AsString, role)) // Template parameters

  /**
   * Declare get user-by id method
   */
  QUERY(getUserByName, 
        "SELECT * FROM users WHERE name=:name;", // SQL-template
        PARAM(oatpp::String, name)) // Template parameters
        
};

#include OATPP_CODEGEN_END(DbClient) ///< End code-gen section
```

### Usage

```cpp
/* declare a client */
auto client = MyClient(executor /* database-specific executor */);

/* Create new user in the database */
client.createUser("admin", "admin@domain.com", UserRoles::ADMIN);

/* Find user by name in the database */
auto result = client.getUserByName("admin");

/* Retrieve query result as a vector of UserDto objects */
/* Of cause, UserDto had to be previously defined */
/* You can also use oatpp::Fields<oatpp::Any> - instead of UserDto for any arbitrary result */
auto dataset = res->fetch<oatpp::Vector<oatpp::Object<UserDto>>>();

/* And we can easily serialize result as a json string using json object mapper */
auto json = jsonObjectMapper.writeToString(dataset);

/* Print the resultant json */
std::cout << json->c_str() << std::endl;
```

Output:

```json
[
  {
    "name": "admin",
    "email": "admin@domain.com",
    "role": "ROLE_ADMIN"
  }
]
```

**Comment by lganzzzo** [comment]
Implemented.
Please find more info in [1.2.0 changelog](https://github.com/oatpp/oatpp/blob/v_1.2.0/changelog/1.2.0.md)
