### ISSUE TITLE
Listen and Send over TCP

### ISSUE THREAD

**Issue by br4m1** [oatpp/oatpp#271]
Dear reader,

I want to build a application wich, **next to being a rest api**, also does the following:
It needs to make a tcp connection to a specific port, send a message and listen for messages back.
It also needs to be able listen on another port and also send messages.

![image](https://user-images.githubusercontent.com/38427685/86596316-4b744000-bf9a-11ea-9a52-fa159e48f31c.png)
The left should be my application, the right is an application running on the same or a different device.

The messages back and forth are made up of:
- First 4 bytes are the length of the message (excluding the 4 bytes themselves) in big-endian: for parsing
- XML message

I was wondering **if the above is possible with help from the OAT++ library**, are there examples and do you maybe have some pointers where to start / what to use?

Greetz,

Bram Weevers

**Comment by lganzzzo** [comment]
Hello @br4m1 ,

It can be done pretty easily with Oat++.
Oat++ application can listen and server on different ports with different protocols.
You can also utilize the object-mapping layer of oatpp to create your custom protocols if needed.

For XML you'll need to use a 3rd party lib - there are plenty of them out there.

# Example

## Client

```cpp
oatpp::network::client::SimpleTCPConnectionProvider connectionProvider("localhost", "9000");
auto connection = connectionProvider.getConnection();

// Send Message
{
  oatpp::String xmlMessage = "<some-xml>";

  v_uint32 msgLen = htonl(xmlMessage->getSize()); // msgLen in network(big endian) order.

  connection->writeExactSizeDataSimple(&msgLen, 4); // send first 4 bytes.
  connection->writeExactSizeDataSimple(xmlMessage->getData(), xmlMessage->getSize()); // send message payload
}

// Read Response
{
  v_uint32 msgLen;
  connection->readExactSizeDataSimple(&msgLen, 4); // read first 4 bytes

  oatpp::String xmlMessage(ntohl(msgLen)); // convert message size from network order to host order. And allocate buffer;
  connection->readExactSizeDataSimple(xmlMessage->getData(), xmlMessage->getSize()); // read message payload
  // TODO xmlMessage var is ready-to-use - it contains received xml
}
```

## Server

Implement your own `oatpp::network::server::ConnectionHandler` class;

```cpp
class MyConnectionHandler : public oatpp::network::server::ConnectionHandler {
public:

  void handleConnection(const std::shared_ptr<IOStream>& connection, const std::shared_ptr<const ParameterMap>& params) override {

    // Same as in the client example but first read, then write
    // TODO - you may also allocate a separate thread to serve each client

    // Read Message
    {
      v_uint32 msgLen;
      connection->readExactSizeDataSimple(&msgLen, 4); // read first 4 bytes

      oatpp::String xmlMessage(ntohl(msgLen)); // convert message size from network order to host order. And allocate buffer;
      connection->readExactSizeDataSimple(xmlMessage->getData(), xmlMessage->getSize()); // read message payload
      // TODO xmlMessage var is ready-to-use - it contains received XML
    }

    // Send Message
    {
      oatpp::String xmlMessage = "<some-xml>";

      v_uint32 msgLen = htonl(xmlMessage->getSize()); // msgLen in network(big endian) order.

      connection->writeExactSizeDataSimple(&msgLen, 4); // send first 4 bytes.
      connection->writeExactSizeDataSimple(xmlMessage->getData(), xmlMessage->getSize()); // send message payload
    }

  }

};
```

Then having your connection handler, use a standard Oat++ ConnectionHandler/ConnectionProvider/Server pattern to serve clients with your custom protocol over TCP.

Please let me know if you have more questions.

Regards,
Leonid

**Comment by br4m1** [comment]
The server side is already a existing running application, so no need for me to implement that, but thanks for the example.

I tried embedding similar code as you wrote above, but my application started crashing, so i made a test application to test the code above:

```c++
#include "oatpp/network/client/SimpleTCPConnectionProvider.hpp"

#include <iostream>

#if defined(WIN32) || defined(_WIN32)
#include <Winsock2.h>
#else
#include <arpa/inet.h>
#endif

int main(int argc, const char *argv[]) {

  try {
    oatpp::network::client::SimpleTCPConnectionProvider connectionProvider(
        "ip", 4101);
    // std::shared_ptr<oatpp::data::stream::IOStream> connection =
    //     connectionProvider.getConnection();
  } catch (const std::runtime_error &re) {
    // speciffic handling for runtime_error
    std::cerr << "Runtime error: " << re.what() << std::endl;
  } catch (const std::exception &ex) {
    // speciffic handling for all exceptions extending std::exception, except
    // std::runtime_error which is handled explicitly
    std::cerr << "Error occurred: " << ex.what() << std::endl;
  } catch (...) {
    // catch any other errors (that we have no information about)
    std::cerr << "Unknown failure occurred. Possible memory corruption"
              << std::endl;
  }
  // const v_uint16 NFIRSTBYTES = 4;

  // // Send Message
  // {
  // oatpp::String xmlMessage = "<some-xml>";

  // v_uint32 msgLen = htonl(xmlMessage->getSize()); // msgLen in network(big
  // endian) order.

  // connection->writeExactSizeDataSimple(&msgLen, NFIRSTBYTES); // send first 4
  // bytes. connection->writeExactSizeDataSimple(xmlMessage->getData(),
  // xmlMessage->getSize()); // send message payload
  // }

  // // Read Response
  // {
  // v_uint32 msgLen;
  // connection->readExactSizeDataSimple(&msgLen, NFIRSTBYTES); // read first 4
  // bytes

  // oatpp::String xmlMessage(ntohl(msgLen)); // convert message size from
  // network order to host order. And allocate buffer;
  // connection->readExactSizeDataSimple(xmlMessage->getData(),
  // xmlMessage->getSize()); // read message payload
  // // OATPP_LOGI("CCV Vx API", "%s", connection->);
  // }

  system("pause");

  return 1;
}
```

If i add `oatpp::network::client::SimpleTCPConnectionProvider connectionProvider("10.103.19.85", 4101);`, the application won't crash.
But if I add `std::shared_ptr<oatpp::data::stream::IOStream> connection = connectionProvider.getConnection();` will crash:
`Runtime error: [oatpp::network::client::SimpleTCPConnectionProvider::getConnection()]. Error. Call to getaddrinfo() faild.`

**Comment by br4m1** [comment]
```c++
auto res = getaddrinfo(m_host->c_str(), portStr->c_str(), &hints, &result);

  if (res != 0) {
    throw std::runtime_error("[oatpp::network::client::SimpleTCPConnectionProvider::getConnection()]. Error. Call to getaddrinfo() faild.");
  }
```
I found this in the code, so that means `getaddrinfo` returns  not zero.

**Comment by br4m1** [comment]
I added a cout to the if statement where I print the res with `gai_strerror(res)` : 
 `Either the application has not called WSAStartup, or WSAStartup failed.`

So I fixed that by initializing the oatpp env.

**Comment by lganzzzo** [comment]
Hey @br4m1 ,
Great that you have figured it out!
You can add the `gai_strerror(res)` to the throw message, and send a PR if you will.
This message will be helpful.

**Comment by lganzzzo** [comment]
I'm closing this one.
@br4m1 please feel free to reopen or to create a new issue in case you have more questions
