### ISSUE TITLE
CMake Error

### ISSUE THREAD

**Issue by LaVine-WU** [oatpp/oatpp#286]
Hello, I encountered the following problems during the installation：
CMake Error: The source directory "/data" does not appear to contain CMakeLists.txt.

**Comment by lganzzzo** [comment]
Hello @LaVine-WU ,

Thanks for the issue.

We need some more info from you:

- do you have some custom directory structure?
- what is your project layout look like (directories)?
- what is the `/data` directory? (the only `/data` dir oatpp has is `<repo>/src/oatpp/core/data/...` and it should not contain any CMake files)

---

The installation of `oatpp` in its' "canonical" form should look like this:

- **Clone oatpp:**
   You should get the following content
   ```
   oatpp/                  #<-- this repo root
     |
     |- CMakeLists.txt
   ```
- **Create `build/` folder**
   Now you should get the following content
   ```
   oatpp/                  #<-- this repo root
     |
     |- build/             #<-- the newly created build folder
     |- CMakeLists.txt
   ```
- **Build and install oatpp**:
   From the `build/` folder run the following commands:
   ```bash
   $ cmake ..
   $ make install
   ```

Regards,
Leonid

**Comment by LaVine-WU** [comment]
Thank you for your reply, I seem to have found the cause of this problem. I created the build folder by mistake in the windows environment. Thank you again!
