### ISSUE TITLE
Could you give an example of how to response with a html page?

### ISSUE THREAD

**Issue by WayneY** [oatpp/oatpp#291]
Could you give an example of how to response with a html page? Not only a json, or some hard coded strings, but a traditional HTML page, with javascript, css and images. Outputing some static HTML files is my first step to write a website, but I did not see any examples... The most close example is the one for live streaming, but in that case the web page is hard coded in a string, which could not be followed in practical use.

**Comment by lganzzzo** [comment]
Hello @WayneY ,
At the moment oatpp is most focussed on serving APIs, and has no convenience methods (like a template engine) to serve
HTML pages.

**Comment by bamkrs** [comment]
Take a look on how the Swagger-UI is served in oatpp-swagger.
This should help you for serving html pages.

**Comment by WayneY** [comment]
Thank you, I will take a look.
