### ISSUE TITLE
could any one tell me how to use multipart

### ISSUE THREAD

**Issue by Aries1989** [oatpp/oatpp#292]

**Comment by lganzzzo** [comment]
Hello @Aries1989 ,

Please find multipart examples here - https://oatpp.io/docs/features/upload-file/#simple-api-multipart-upload

To test your endpoint use:

```bash
curl http://localhost:8000/path/to/endpoint -F part1=@001.txt -F part2=@002.txt -H "Expect: "
```

Note: the `Expect` header is set to be empty as oatpp at the moment doesn't support it, and won't respond with `100-continue`.

**Comment by lganzzzo** [comment]
Closing this...
