### ISSUE TITLE
How can I access to the client address (the caller)

### ISSUE THREAD

**Issue by Ventastega** [oatpp/oatpp#295]
I would like to prevent flooding by rate limiting the REST calls by client address.
Is is possible to get the client address from the controller ?

Thank you.

**Comment by lganzzzo** [comment]
Hello @Ventastega ,

Please find this issue in oatpp-websocket - https://github.com/oatpp/oatpp-websocket/issues/4
It applies to the whole oatpp framework, not only to websocket.

**Comment by lganzzzo** [comment]
I'll leave it here for convenience:

Starting from release [0.19.11](https://github.com/oatpp/oatpp/releases/tag/0.19.11)
Peer IP and port can be obtained via the connection stream context.

Enable extended connection info in server connection provider:

```cpp
oatpp::network::server::SimpleTCPConnectionProvider::createShared(8000, true /* enable extended info */)
```

List all connection properties available:

```cpp
 ENDPOINT("GET", "/", root, 
          REQUEST(std::shared_ptr<IncomingRequest>, request)) 
 {
   auto* context = request->getConnection()->getInputStreamContext();
   for(const auto& pair : context->getProperties().getAll()) {
     OATPP_LOGD("property", "'%s' - '%s'", pair.first.getData(), pair.second.getData());
   }
   return createResponse(Status::CODE_200, "Hello World!!!");
 }
```

Cheers,
Leonid

**Comment by kekxv** [comment]
> I'll leave it here for convenience:
> 
> Starting from release [0.19.11](https://github.com/oatpp/oatpp/releases/tag/0.19.11) Peer IP and port can be obtained via the connection stream context.
> 
> Enable extended connection info in server connection provider:
> 
> ```c++
> oatpp::network::server::SimpleTCPConnectionProvider::createShared(8000, true /* enable extended info */)
> ```
> 
> List all connection properties available:
> 
> ```c++
>  ENDPOINT("GET", "/", root, 
>           REQUEST(std::shared_ptr<IncomingRequest>, request)) 
>  {
>    auto* context = request->getConnection()->getInputStreamContext();
>    for(const auto& pair : context->getProperties().getAll()) {
>      OATPP_LOGD("property", "'%s' - '%s'", pair.first.getData(), pair.second.getData());
>    }
>    return createResponse(Status::CODE_200, "Hello World!!!");
>  }
> ```
> 
> Cheers, Leonid

not working , oatpp-1.3.0

**Comment by Lnxzz** [comment]
> > I'll leave it here for convenience:
> > Starting from release [0.19.11](https://github.com/oatpp/oatpp/releases/tag/0.19.11) Peer IP and port can be obtained via the connection stream context.
> > Enable extended connection info in server connection provider:
> > ```c++
> > oatpp::network::server::SimpleTCPConnectionProvider::createShared(8000, true /* enable extended info */)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > List all connection properties available:
> > ```c++
> >  ENDPOINT("GET", "/", root, 
> >           REQUEST(std::shared_ptr<IncomingRequest>, request)) 
> >  {
> >    auto* context = request->getConnection()->getInputStreamContext();
> >    for(const auto& pair : context->getProperties().getAll()) {
> >      OATPP_LOGD("property", "'%s' - '%s'", pair.first.getData(), pair.second.getData());
> >    }
> >    return createResponse(Status::CODE_200, "Hello World!!!");
> >  }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Cheers, Leonid
> 
> not working , oatpp-1.3.0

Make sure to enable the extended connection information in the server connection provider:

`  /**
   *  Create ConnectionProvider component which listens on the port
   */
  OATPP_CREATE_COMPONENT(std::shared_ptr<oatpp::network::ServerConnectionProvider>, serverConnectionProvider)([] {
    return oatpp::network::tcp::server::ConnectionProvider::createShared({AppComponent::get_host().c_str(), static_cast<short unsigned int>(AppComponent::get_port()), oatpp::network::Address::IP_4}, **true**);
  }());`

**Comment by JosefSommerauer** [comment]
is it also somehow possible to get the client ip of a websocket connection?

**Comment by lganzzzo** [comment]
Hello @JosefSommerauer ,

Having instance of `WebSocket` / `AsyncWebScoket` you can access its connection object - https://github.com/oatpp/oatpp-websocket/blob/master/src/oatpp-websocket/WebSocket.hpp#L167 .

Then just like in the example above - get stream context and get all the properties including client IP address

**Comment by JosefSommerauer** [comment]
feels a little bit like a hack but this works :
```
auto * context = &(socket->getConnection().object->getInputStreamContext());
```
but thanks anyway @lganzzzo. and thanks that you are contributing to oatpp, its an awesome project!
