### ISSUE TITLE
parent directory naming

### ISSUE THREAD

**Issue by tropf** [oatpp/oatpp#30]
# parent directory naming
When building, oatpp is required to be cloned into a directory named `oatpp`

**This breaks compatibility**, e.g. with the [External Project](https://cmake.org/cmake/help/v3.13/module/ExternalProject.html) feature from cmake.

## Steps to reproduce
Create an empty directory, and add two files:

`CMakeLists.txt` should contain:  
```
cmake_minimum_required (VERSION 2.6)

project (test_oatpp_as_external)

set(PROJECT_VERSION_MAJOR 0)
set(PROJECT_VERSION_MINOR 1)
set(CMAKE_CXX_STANDARD 11)

include(ExternalProject)
option(OATPP_INSTALL "Create installation target for oat++" OFF)
option(OATPP_BUILD_TESTS "Create test target for oat++" OFF)
ExternalProject_Add(oatpp_external_project
    PREFIX "extern/oatpp"
    GIT_REPOSITORY "https://github.com/oatpp/oatpp/"
    UPDATE_DISCONNECTED TRUE
    )

add_executable(testprogram main.cc)
add_dependencies(testprogram oatpp_external_project)
target_link_libraries(testprogram oatpp)
```

`main.cc` is a dummy file and should contain:  
```c++
int main() { return 0; }
```
Then compile using:  
```bash
mkdir build && cd build
cmake ..
make
# the build now breaks
```

## Expected Bahaviour
Cmake downloads oat++ and builds it successfully.
Then, the test application is built and linked against oat++.

## Actual Behaviour
CMake downloads oat++ and tries to build it.
This build fails with:

```
In file included from [...]/build/extern/oatpp/src/oatpp_external_project/algorithm/CRC.cpp:25:
[...]/build/extern/oatpp/src/oatpp_external_project/algorithm/CRC.hpp:28:10: fatal error: oatpp/core/base/Environment.hpp: No such file or directory
 #include "oatpp/core/base/Environment.hpp"
```

This happens because the External Project feature of cmake doesn't clone oatpp into a directory named `oatpp`, but in this case `oatpp_external_project` (full path: `build/extern/oatpp/src/oatpp_external_project`)

## Cause
This is caused by the following lines of oat++'s `CMakeLists.txt` file:

```
target_include_directories(oatpp PUBLIC
    $<BUILD_INTERFACE:${CMAKE_CURRENT_SOURCE_DIR}/..>
    $<INSTALL_INTERFACE:${CMAKE_INSTALL_INCLUDEDIR}>
)
```

With these lines, the directory containing the source files has to be named oatpp.

## Proposed Fix
One of these:

1. Remove `oatpp/` from the beginning of all include statements
2. put all source files in a subdirectory with the name `oatpp`

**Comment by lganzzzo** [comment]
Hey @tropf ,
Thank you for the issue and detailed description.

Proposed fixes have some conflicts with oatpp submodules. ex(oatpp-consul, oatpp-swagger, etc.)

I have to think about it.
I'l come back to you as soon as I have resolution for this.

Best Regards,
Leonid

**Comment by lganzzzo** [comment]
Hello @tropf 

Directory structure have been changed as for your 2nd proposition.
Now oatpp and all of it's modules have new dir structure.

For `CMake` - `ExternalProject_Add` usage you may see one of the example-projects:  
- [https://github.com/oatpp/example-crud](https://github.com/oatpp/example-crud)

Best Regards,
Leonid
