### ISSUE TITLE
ErrorHandler may handle a corrupted string

### ISSUE THREAD

**Issue by bronekrab** [oatpp/oatpp#300]
Hello!

Message string in this method

https://github.com/oatpp/oatpp/blob/8a4fd7e57e440766b882ed5e497c83a2fe634189/src/oatpp/web/server/handler/ErrorHandler.cpp#L37

may be corrupted. When unhandled exception thrown from user code, this exception catched by this  

https://github.com/oatpp/oatpp/blob/8a4fd7e57e440766b882ed5e497c83a2fe634189/src/oatpp/core/async/Coroutine.cpp#L318

`oatpp::async::Error` constructor don't copy `const char*` string from `std::exception::what()`. C-string will be destroyed when `std::exception e` object destroyed.

**Comment by lganzzzo** [comment]
Hey @bronekrab ,
You are right!
Marked this as a bug!

**Comment by lganzzzo** [comment]
Fixed
