### ISSUE TITLE
Oatpp recursive header inclusion error

### ISSUE THREAD

**Issue by Ultra-Code** [oatpp/oatpp#303]
Just built oatpp to standard path but when included in a cpp file i get a clang error pp_file_not_found but the file exist in the /usr/local/include/ dir ,So I included that dir to my preprocessor options but the error persist ie. even after adding -I/usr/local/include/oatpp-1.1.0/oatpp/oatpp/ to my compile options

**Comment by lganzzzo** [comment]
Hello @Ultra-Code ,

Please give us more info:
- system info 
- exact error message
- how you installed oatpp - set of commands
- how you are trying to include oatpp in your project - cmake script or whatever you are using

Regards,
Leonid

**Comment by Ultra-Code** [comment]
@lganzzzo sorry for my late reply

-  I am on debian sid 
-  fatal error: 'oatpp-1.1.0/oatpp/oatpp/oatpp/network/server/Server.hpp' file not found 
# Set of commands for installation
-  cmake -G Ninja ..
-  sudo checkinstall ninja install

# How am including
- just regular #include <oatpp-1.1.0/oatpp/oatpp/oatpp/network/server/Server.hpp>
- and it seems all headers aren't found because if i remove the first one the second also isn't found
- i was following the simplest project  in API - Low Level Components Overview of docs

**Comment by lganzzzo** [comment]
Hey @Ultra-Code ,

Why do include `#include <oatpp-1.1.0/oatpp/oatpp/oatpp/network/server/Server.hpp>` ?
It is supposed that you include `#include "oatpp/network/server/Server.hpp"`

Please take a look at a [starter-project](https://github.com/oatpp/oatpp-starter).

**Comment by Ultra-Code** [comment]
Yes @lganzzzo if I was working with the starter repo `#include "oatpp/network/server/Server.hpp"` would be the right because the header would be relative to the file but since i have installed oatpp system wide I wan't to use those header and follow the tutorial without cloning and using the starter repo and besides it is the sys wide headers that I will use when working on my actual project. And also even changing to use the ones exactly in the guide still give me the same error and this time around all the symbols are undecleared even namespace oatpp

**Comment by lganzzzo** [comment]
Hey @Ultra-Code ,

It's a common practice to install oatpp system-wide. And `oatpp-starter` assumes that you install oatpp system-wide.

Please refer to [oatpp installation guide](https://oatpp.io/docs/installation/unix-linux/) and please look at the [oatpp-starter/CMakeLists.txt](https://github.com/oatpp/oatpp-starter/blob/master/CMakeLists.txt#L18) for how-to correctly link oatpp in your project.

Once you link oatpp correctly in your project it will set your include paths to point to the right directory, and your problem will be resolved.

**Comment by Ultra-Code** [comment]
@lganzzzo  Thank you very much ,I really appreciate it. My issue was with the correct linking of the oatpp , tweaking my CMakeLists.txt fix the issue.

**Comment by lganzzzo** [comment]
Hey, I'm glad it helped!
Closing the issue.
