### ISSUE TITLE
A mistake in the step by step guide

### ISSUE THREAD

**Issue by zxjbill** [oatpp/oatpp#311]
Hi
Use oatpp-1.1.0 and compile the project showed in the website [https://oatpp.io/docs/start/step-by-step](url).
Maybe there are some mistakes in the file _test/MyControllerTest.cpp_. Example:
`auto message = response->readBodyToDto<MessageDto>(objectMapper);`
`OATPP_ASSERT(message->statusCode->getValue() == 200);`

Should these be `auto message = response->readBodyToDto<oatpp::Object<MessageDto>>(objectMapper.get());`  and `OATPP_ASSERT(message->statusCode == 200);` instead?

Thanks!

**Comment by lganzzzo** [comment]
Hey @zxjbill ,

Thanks for the issue report!
You are correct, it's a mistake in the docs which left from the previous releases.

We'll have to update the docs to fix that!

Thanks for reporting it!

Best Regards,
Leonid

**Comment by lganzzzo** [comment]
Fixed
