### ISSUE TITLE
Why does httpServer crash when it exits?

### ISSUE THREAD

**Issue by NickPak** [oatpp/oatpp#313]
```c++
std::_Sp_counted_base<(__gnu_cxx::_Lock_policy)2>::_M_release shared_ptr_base.h:155
std::__shared_count<(__gnu_cxx::_Lock_policy)2>::~__shared_count shared_ptr_base.h:728
std::__shared_ptr<oatpp::base::StrBuffer, (__gnu_cxx::_Lock_policy)2>::~__shared_ptr shared_ptr_base.h:1167
std::shared_ptr<oatpp::base::StrBuffer>::~shared_ptr shared_ptr.h:103
oatpp::data::mapping::type::ObjectWrapper<oatpp::base::StrBuffer, oatpp::data::mapping::type::__class::String>::~ObjectWrapper Type.hpp:97
oatpp::data::mapping::type::String::~String Primitive.hpp:62
oatpp::parser::json::mapping::Serializer::Config::~Config Serializer.hpp:49
__gnu_cxx::new_allocator<oatpp::parser::json::mapping::Serializer::Config>::destroy<oatpp::parser::json::mapping::Serializer::Config> new_allocator.h:140
std::allocator_traits<std::allocator<oatpp::parser::json::mapping::Serializer::Config> >::destroy<oatpp::parser::json::mapping::Serializer::Config> alloc_traits.h:487
std::_Sp_counted_ptr_inplace<oatpp::parser::json::mapping::Serializer::Config, std::allocator<oatpp::parser::json::mapping::Serializer::Config>, (__gnu_cxx::_Lock_policy)2>::_M_dispose shared_ptr_base.h:554
std::_Sp_counted_base<(__gnu_cxx::_Lock_policy)2>::_M_release shared_ptr_base.h:155
std::__shared_count<(__gnu_cxx::_Lock_policy)2>::~__shared_count shared_ptr_base.h:728
std::__shared_ptr<oatpp::parser::json::mapping::Serializer::Config, (__gnu_cxx::_Lock_policy)2>::~__shared_ptr shared_ptr_base.h:1167
std::shared_ptr<oatpp::parser::json::mapping::Serializer::Config>::~shared_ptr shared_ptr.h:103
oatpp::parser::json::mapping::Serializer::~Serializer Serializer.hpp:38
__gnu_cxx::new_allocator<oatpp::parser::json::mapping::Serializer>::destroy<oatpp::parser::json::mapping::Serializer> new_allocator.h:140
std::allocator_traits<std::allocator<oatpp::parser::json::mapping::Serializer> >::destroy<oatpp::parser::json::mapping::Serializer> alloc_traits.h:487
std::_Sp_counted_ptr_inplace<oatpp::parser::json::mapping::Serializer, std::allocator<oatpp::parser::json::mapping::Serializer>, (__gnu_cxx::_Lock_policy)2>::_M_dispose shared_ptr_base.h:554
std::_Sp_counted_base<(__gnu_cxx::_Lock_policy)2>::_M_release shared_ptr_base.h:155
std::__shared_count<(__gnu_cxx::_Lock_policy)2>::~__shared_count shared_ptr_base.h:728
std::__shared_ptr<oatpp::parser::json::mapping::Serializer, (__gnu_cxx::_Lock_policy)2>::~__shared_ptr shared_ptr_base.h:1167
std::shared_ptr<oatpp::parser::json::mapping::Serializer>::~shared_ptr shared_ptr.h:103
oatpp::parser::json::mapping::ObjectMapper::~ObjectMapper ObjectMapper.hpp:40
__gnu_cxx::new_allocator<oatpp::parser::json::mapping::ObjectMapper>::destroy<oatpp::parser::json::mapping::ObjectMapper> new_allocator.h:140
std::allocator_traits<std::allocator<oatpp::parser::json::mapping::ObjectMapper> >::destroy<oatpp::parser::json::mapping::ObjectMapper> alloc_traits.h:487
std::_Sp_counted_ptr_inplace<oatpp::parser::json::mapping::ObjectMapper, std::allocator<oatpp::parser::json::mapping::ObjectMapper>, (__gnu_cxx::_Lock_policy)2>::_M_dispose shared_ptr_base.h:554
std::_Sp_counted_base<(__gnu_cxx::_Lock_policy)2>::_M_release shared_ptr_base.h:155
std::__shared_count<(__gnu_cxx::_Lock_policy)2>::~__shared_count shared_ptr_base.h:728
std::__shared_ptr<oatpp::parser::json::mapping::ObjectMapper, (__gnu_cxx::_Lock_policy)2>::~__shared_ptr shared_ptr_base.h:1167
std::shared_ptr<oatpp::parser::json::mapping::ObjectMapper>::~shared_ptr shared_ptr.h:103
...............
__run_exit_handlers 0x00007f66df1d6d8c
__GI_exit 0x00007f66df1d6eba
__libc_start_main 0x00007f66df1c10a2
_start 0x000000000084ecaa
```

**Comment by NickPak** [comment]
@lganzzzo Hey, Sorry, I wrote my own httpServer, but it crashed when the process quit, I don't know what caused it.

**Comment by NickPak** [comment]
Hey, I'm Sorry, I wrote my own httpServer, but it crashed when the process quit, I don't know what caused it.

**Comment by NickPak** [comment]
@lganzzzo Hey, I'm Sorry, I wrote my own httpServer, but it crashed when the process quit, I don't know what caused it.

**Comment by NickPak** [comment]
@lganzzzo Hey, I'm sorry, I wrote my own httpServer, but it crashes when the process exits. I seem to have found the problem, but don't know the reason.
```c++
API_CALL(HTTP_GET, "v1/health/service/{serviceName}", healthService, PATH(String, serviceName), QUERY(String, Near, "near"), QUERY(Boolean, passingOnly, "passing"), QUERY(String, filter, "filter"))
API_CALL(HTTP_GET, "v1/health/service/{serviceName}", healthService, PATH(String, serviceName), QUERY(String, Near, "near"), QUERY(String, passingOnly, "passing"))
```
The problem is with the passingOnly parameter, which raises the problem when its type is Boolean, and works fine if its type is String

**Comment by lganzzzo** [comment]
Hey @NickPak ,

Did you just close the issue, or it's still unresolved?

**Comment by NickPak** [comment]
@lganzzzo Yes, I'm still working on it

**Comment by lganzzzo** [comment]
Please give me some more details,

How the API call is connected to the process exit?

**Comment by lganzzzo** [comment]
Hey @NickPak ,

- The log is about the destruction of the JSON object mapper.
- Your code is about `API_CALL` in ApiClient. And your API calls do not use the body so the object mapper is not connected here.
- And also you are saying that server crashes when the process exists.

These look like three unrelated things to me.
Please give more context on this issue.

**Comment by NickPak** [comment]
The code is also involved in the environment of 'Consul'. I was thinking about how to ask you for help. I started an HttpServer in 'Consul API' for service level health check. As long as it is not on at the same time everything works fine but if it is on at the same time and the above API is called it will crash on exit

**Comment by NickPak** [comment]
Is it because I am in a process created two oatpp: : parser: : json: : mapping: : ObjectMapper object?

**Comment by lganzzzo** [comment]
> The code is also involved in the environment of 'Consul'. I was thinking about how to ask you for help. I started an HttpServer in 'Consul API' for service level health check. As long as it is not on at the same time everything works fine but if it is on at the same time and the above API is called it will crash on exit

To clarify:
- You have consul + oatpp service running somewhere (ex.: in the cloud).
- You register oatpp service in consul providing a health check endpoint.
- What happens next? Why your service should exits?

> Is it because I am in a process created two oatpp: : parser: : json: : mapping: : ObjectMapper object?

Are using `OATPP_CREATE_COMPONENT` to create object mappers?
Please share the code how you create your object mappers.

**Comment by NickPak** [comment]
I am uploading this code to Github. Thank you very much.
The runtime environment is my Linux system. I didn't use OATPP_CREATE_COMPONENT, but call `oatpp::parser::json::mapping::ObjectMapper::createShared ()`

**Comment by lganzzzo** [comment]
Hey, 
Please post a link to your code, when ready. 
Thanks

**Comment by NickPak** [comment]
@lganzzzo Hey, Thank you very much!

I have uploaded the code to my Github.
You can run it by following the steps below:

1. Get the code:
`git clone -b consul https://github.com/NickPak/oatpp.git`
2.Start the consul
`oatpp/consul/bin/start_consul_linux.sh`
3.Compile and run with CMake
```
cd ./oatpp && cmake -S. -Bbuild -DCMAKE_BUILD_TYPE=Debug && cmake --build build --target consul
cd build/consul && ./consul
```
When the program is finished, you'll get a core file.
I don't know if I was using OATPP API incorrectly or something else.

**Comment by lganzzzo** [comment]
Hey @NickPak ,

As I'm looking in your code,- it seems to me that your issue is similar to #308 

Also, you don't init oatpp Environment, and you don't have a proper cleanup procedure there.

Aside from mentioned above the code looks a bit overcomplicated 
like this kind of things:

```cpp
        if (m_load >= 0) {
            const auto &body = oatpp::web::protocol::http::outgoing::BufferBody::createShared(fmt::format("The service momentary load is {}%", m_load).c_str());
            return oatpp::web::protocol::http::outgoing::Response::createShared(status, body);
        } else {
            return oatpp::web::protocol::http::outgoing::Response::createShared(status, nullptr);
        }
```

Instead, you can just do:

```cpp
        if (m_load >= 0) {
            return createResponse(status, fmt::format("The service momentary load is {}%", m_load).c_str());
        } else {
            return createResponse(status, "");
        }
```

`createResponse` - is method of `ApiController`

---

I would recommend you to look through [step-by-step guide](https://oatpp.io/docs/start/step-by-step/) -
it will make things about oatpp initialization + about API controllers a bit clearer.

Please also find this response here - https://github.com/oatpp/oatpp/issues/308#issuecomment-702461263
There is a link there for example how to stop the server by a signal.

Best Regards,
Leonid

**Comment by NickPak** [comment]
@lganzzzo Thank you very much, everything seemed to work well when I added the `-DOATPP_DISABLE_POOL_ALLOCATIONS=ON` compile option.

**Comment by lganzzzo** [comment]
Closing this...
