### ISSUE TITLE
SimpleTCPConnectionProvider::instantiateServer memory leak

### ISSUE THREAD

**Issue by bronekrab** [oatpp/oatpp#315]
Hello!

Valgrind reports a Leak_DefinitelyLost on this line 

https://github.com/oatpp/oatpp/blob/4427123bb3608a78806ebce654cfe74605a389bf/src/oatpp/network/server/SimpleTCPConnectionProvider.cpp#L173

it seems the `result` variable is never released.

![image](https://user-images.githubusercontent.com/29654239/94917694-ad6d1480-04b9-11eb-95b8-81242e5faacf.png)

**Comment by lganzzzo** [comment]
Hey @bronekrab ,

Thanks for catching this!

The version `1.2.0` is currently being prepared for release - it would be very helpful if you could check it and contribute a fix in case it's still there.

Please note that `server/SimpleTCPconnectionProvider.cpp` is moved to https://github.com/oatpp/oatpp/blob/master/src/oatpp/network/tcp/server/ConnectionProvider.cpp

Regards,
Leonid

**Comment by bronekrab** [comment]
@lganzzzo , unfortunately, there is currently no way to check the new version. I think the problem is the lack of the `freeaddrinfo (result);` function.
  
Can you explain why the `freeaddrinfo (result);` were removed in this commit, this is definitely not a bug?

https://github.com/oatpp/oatpp/commit/3b59fa2738e155ac907a81fd35f3f3598cc2d98c#diff-d9e151842275d994def65b4400bc6e7bL129

https://github.com/oatpp/oatpp/commit/3b59fa2738e155ac907a81fd35f3f3598cc2d98c#diff-d9e151842275d994def65b4400bc6e7bL137

https://github.com/oatpp/oatpp/commit/3b59fa2738e155ac907a81fd35f3f3598cc2d98c#diff-d9e151842275d994def65b4400bc6e7bL142

**Comment by lganzzzo** [comment]
Hey @bronekrab ,

You are right it was removed by a mistake. It should be there.

**Comment by lganzzzo** [comment]
This one was fixed
