### ISSUE TITLE
new version at vcpkg

### ISSUE THREAD

**Issue by KaungZawHtet** [oatpp/oatpp#318]
There is only 1.0.0 at vcpkg. Can you update with 1.1.0

**Comment by KaungZawHtet** [comment]
1.2.0 better

**Comment by lganzzzo** [comment]
Hey @KaungZawHtet ,

vcpkg for oatpp is maintained by the community.
Please find the PR for `1.1.0` - https://github.com/microsoft/vcpkg/pull/12249

**Comment by KaungZawHtet** [comment]
Seems 1.1.0 is still in issue there.

**Comment by lganzzzo** [comment]
PR was merged! I'm closing this issue.
Many thanks to @mheyman !

**Comment by KaungZawHtet** [comment]
it is still 1.0.0 when u do `vcpkg search oatpp`

<img width="853" alt="Screen Shot 2020-10-07 at 15 15 04" src="https://user-images.githubusercontent.com/15225530/95308636-2d2b2280-08b0-11eb-81a3-ba82b82e34b4.png">
