### ISSUE TITLE
OATPP_LOG prints wrong int value

### ISSUE THREAD

**Issue by ktnr** [oatpp/oatpp#320]
I have a DTO with an int field: ```DTO_FIELD(Int32, jobId);```

When I log the value with the OATPP_LOG() macro

```OATPP_LOGD("D", "[DTOResponseB] data='%i'", responseDto->jobId);```

it prints a large value even though the jobId is 4. When the int is hard coded

```OATPP_LOGD("D", "[DTOResponseB] data='%i'", 1);```

the result is as expected.

But,  ```OATPP_ASSERT(responseDto->jobId == 4);``` passes.

Am I missing something or is this a bug?

**Comment by lganzzzo** [comment]
Hey @ktnr ,

Just do `*jobId`

```cpp
  oatpp::Int32 jobId = 4;
  OATPP_LOGD("AAA", "jobId=%d", *jobId);
```

**Comment by lganzzzo** [comment]
The trick is that `Int32` does auto conversion when the type is known and can be directly converted to/from `v_int32`.
When using the `OATPP_LOGD` type is unknown so you have to explicitly specify a correct stored value.
The `*` operator returns the underlying value of the `oatpp::Int32` which is `v_int32`.

```cpp
                                        Add a star here
                                            |
                                            |
                                           \|/
OATPP_LOGD("D", "[DTOResponseB] data='%i'", *responseDto->jobId);
```

**Comment by ktnr** [comment]
Thanks for the fast response!

Ah, the comparison operators are overloaded, that's why `OATPP_ASSERT` knows the type and passes. Good to know. 

Not that I want to, but this does not allow me to `==` the memory adress of the value the Int32 because it gets dereferenced automatically?

**Comment by lganzzzo** [comment]
Hey @ktnr ,

> Not that I want to, but this does not allow me to == the memory adress of the Int32 because it gets dereferenced automatically?

oatpp mapping-enabled types are just `shared_ptr` + `valueType`

```cpp
oatpp::Int32 value = 32;
OATPP_LOGD("Memory Address", "%d", value.get()); // <-- get raw pointer
OATPP_LOGD("Stored Value", "%d", *value); // <-- stored value
OATPP_LOGD("oatpp type classId", "%d", value.valueType->classId.id);
OATPP_LOGD("oatpp type class name", "%d", value.valueType->classId.name);

std::shared_ptr<v_int32> shared_int32 = value.getPtr();
```
