### ISSUE TITLE
Windows mingw compile error on oatppAllTests project

### ISSUE THREAD

**Issue by mohammad-nazari** [oatpp/oatpp#324]
ConnectionProvider.cpp:300:5: error: 'inet_ntop' was not declared in this scope inet_ntop(AF_INET, &sockAddress->sin_addr, strIp, INET_ADDRSTRLEN);
Windows, MinGW64, g++, cmake, clion

**Comment by lganzzzo** [comment]
Hello @mohammad-nazari ,

I'll be able to look at this in a couple of days.
If you find a solution earlier, please feel free to send a PR.

It looks like a missing include.

Best Regards,
Leonid

**Comment by mohammad-nazari** [comment]
OK
Hi @lganzzzo 
thanks 
https://docs.microsoft.com/en-us/cpp/porting/modifying-winver-and-win32-winnt?redirectedfrom=MSDN&view=vs-2019
MinGW try to build every code for all windows versions so it sets The preprocessor macros _WIN32_WINNT to 0x502 equals to Windows XP. The function inet_ntop in WS2tcpip.h is not defined for windows XP because this version does not support IPV6.

**Comment by wvffle** [comment]
Any update on this?

**Comment by wvffle** [comment]
I found a repo that sort of workarounds it: https://github.com/AravisProject/aravis/pull/441/files

**Comment by lganzzzo** [comment]
Hey @wvffle , 

any success with the patch?

**Comment by wvffle** [comment]
Yeah it compiled without any errors. I'm writing an app for windows 10 and do not have an option to test if everything works well on XP. If you want I can make a PR and someone who has the ability could test this out.

**Comment by bamkrs** [comment]
@wvffle I would not concider WinXP as an target for Oat++. MinGW compatiblity however is a nice-to-have! It would be great if you bundle up an PR for Win10+MinGW
