### ISSUE TITLE
Compile error on clang 7.0.1

### ISSUE THREAD

**Issue by eviveraart** [oatpp/oatpp#326]
With clang 7.0.1 I get the following compile issue:
`oatpp/core/data/mapping/type/./Type.hpp:291:28: error: chosen constructor is explicit in copy-initialization
       InterpretationMap&& pInterpretationMap = {});`
This is fixed by changing the line Type.hpp:291 from 
`InterpretationMap&& pInterpretationMap = {});`
to:
`InterpretationMap&& pInterpretationMap = InterpretationMap{});`

**Comment by lganzzzo** [comment]
Hello @eviveraart ,

Please don't hesitate to send a PR.

Regards,
Leonid

**Comment by eviveraart** [comment]
Done https://github.com/oatpp/oatpp/pull/327
