### ISSUE TITLE
Please add support to BSON UTC datetime type

### ISSUE THREAD

**Issue by rahulgargmit** [oatpp/oatpp#332]
We need to insert String value as datetime in mongodb
for example
Test data:
"timestamp" : "Thu Oct 29 06:21:13 2020"

Expected after insert into mongodb:
"timestamp" : ISODate("Thu Oct 29 06:21:13 2020")

With oatpp, there is no option to have datetime field in a class or DTO.

**Comment by lganzzzo** [comment]
This issue is related to [oatpp-mongo](https://github.com/oatpp/oatpp-mongo)

**Comment by lganzzzo** [comment]
Now BSON DateTime data type is supported. 

```cpp
  #include "oatpp-mongo/bson/Types.hpp"

  ...

  auto duration = std::chrono::system_clock::now().time_since_epoch();
  auto millis = std::chrono::duration_cast<std::chrono::milliseconds>(duration).count();

  collection.insert_one(createMongoDocument(
    oatpp::Fields<oatpp::Any>({
        {"time", oatpp::mongo::bson::DateTime(millis)}
    })
  ));
```

Inserted document:

```json
_id: ObjectId("5f9b6ecb21a7da049662e7d2")
time: 2020-10-30T01:39:23.940+00:00
```

**Comment by lganzzzo** [comment]
Hey @rahulgargmit ,

Checkout the latest `oatpp-mongo` master.

Please let me know how it works.

Regards,
Leonid

**Comment by lganzzzo** [comment]
Closing this one...
