### ISSUE TITLE
How to get data from raw post request to controller and DTO?

### ISSUE THREAD

**Issue by sanekt197** [oatpp/oatpp#333]
Hey. Guys, tell me how to transfer the POST (application/x-www-form-urlencoded) login and password fields to the controller to get a token to implement OAuth2 authorization etc.?
Or maybe there is something similar already in "Bearer Authorization"..

And in general, how can you receive data by POST request (for example, from forms)? That would be possible to accept data in DTO (as far as I understand) Since it is not always convenient to accept data only in a JSON structure .. Some other deserializer is needed? I can't find something in doc :(

**Comment by lganzzzo** [comment]
Hello @sanekt197 ,

> Hey. Guys, tell me how to transfer the POST (application/x-www-form-urlencoded) login and password fields to the controller to get a token to implement OAuth2 authorization etc.?

To send login/password - use `Basic Authorization` - please read here how to set it up in the ApiController - https://oatpp.io/docs/components/api-controller/#authorization-basic

> And in general, how can you receive data by POST request (for example, from forms)? That would be possible to accept data in DTO (as far as I understand) Since it is not always convenient to accept data only in a JSON structure .. Some other deserializer is needed? I can't find something in doc :(

The most convenient way to post form data to oatpp endpoint is to use `multipart-form-data`.  
Here is the full working controller example:

```cpp
#ifndef MyController_hpp
#define MyController_hpp

#include "oatpp/web/mime/multipart/InMemoryPartReader.hpp"
#include "oatpp/web/mime/multipart/Reader.hpp"
#include "oatpp/web/mime/multipart/PartList.hpp"

#include "oatpp/web/server/api/ApiController.hpp"
#include "oatpp/core/macro/codegen.hpp"
#include "oatpp/core/macro/component.hpp"

#include OATPP_CODEGEN_BEGIN(ApiController) //<-- Begin Codegen

namespace multipart = oatpp::web::mime::multipart;

class MyController : public oatpp::web::server::api::ApiController {
public:
  MyController(OATPP_COMPONENT(std::shared_ptr<ObjectMapper>, objectMapper))
    : oatpp::web::server::api::ApiController(objectMapper)
  {}
public:

  static constexpr const char* page =
    "<!DOCTYPE html>\n"
    "<html lang=\"en\">\n"
    "<head>\n"
    "  <meta charset=\"utf-8\"/>\n"
    "  <title>upload</title>\n"
    "</head>\n"
    "<body>\n"
    "<form action=\"http://localhost:8000/post-form\" method=\"post\" enctype=\"multipart/form-data\">\n"
    "  <p><input type=\"text\" name=\"text1\" value=\"text default\">\n"
    "  <p><input type=\"text\" name=\"text2\" value=\"a&#x03C9;b\">\n"
    "  <p><input type=\"file\" name=\"file1\">\n"
    "  <p><input type=\"file\" name=\"file2\">\n"
    "  <p><input type=\"file\" name=\"file3\">\n"
    "  <p><button type=\"submit\">Submit</button>\n"
    "</form>\n"
    "</body>\n"
    "</html>"
    "";

  ENDPOINT("GET", "/", root) {
    return createResponse(Status::CODE_200, page);
  }

  ENDPOINT("POST", "post-form", postForm,
           REQUEST(std::shared_ptr<IncomingRequest>, request))
  {

    auto multipart = std::make_shared<multipart::PartList>(request->getHeaders());

    multipart::Reader reader(multipart.get());
    reader.setDefaultPartReader(multipart::createInMemoryPartReader(10 * 1024 * 1024 /* max-data-size per part */));

    request->transferBody(&reader);

    for(auto& part : multipart->getAllParts())  {
      OATPP_LOGD(
        "part", "name=%s, known_size=%d, value='%s'",
        part->getName()->c_str(),
        part->getKnownSize(),             //<- Available for InMemoryPart only
        part->getInMemoryData()->c_str()  //<- Available for InMemoryPart only
      );
    }

    return createResponse(Status::CODE_200, "OK");

  }
  
};

#include OATPP_CODEGEN_END(ApiController) //<-- End Codegen

#endif /* MyController_hpp */
```

Note the `enctype=\"multipart/form-data\"` in the HTML

Regards,
Leonid

**Comment by sanekt197** [comment]
Great thanks
Figured out
