### ISSUE TITLE
Bug with sending incorrect json doc

### ISSUE THREAD

**Issue by sovamaster** [oatpp/oatpp#340]
Hello!
I am testing example-crud for applying your framework in my project. But I noticed some bug.
I try to get value from the sent json into std::string with this way:
**std::string test = userDto->userName->c_str();**
```
ENDPOINT("POST", "users", createUser,  BODY_DTO(Object<UserDto>, userDto))
{
       std::string test = userDto->userName->c_str();

       return createDtoResponse(Status::CODE_200, m_userService.createUser(userDto));
}

```
UserDto defined like this:
```
class UserDto : public oatpp::DTO {
	DTO_INIT(UserDto, DTO)
	DTO_FIELD(Int32, id);
	DTO_FIELD(String, userName, "username");
};
```

If i send correct json with post query, i get value to "test" variable properly.
```
{
  "id": 0,
  "username": "test_user"
}

```
But if i change json`s field "username" to, as example, "Username" and send this json to endpoin, server will faild with error "Segmentation fault".

Server must'n faild under such condition. It must giv error message to the sender, and continue run.

How can i avoid the failure, if i just neen to get one simple value to variable?

**Comment by lganzzzo** [comment]
Hello @sovamaster ,

Since in the second case, your DTO has the field `Username` but NOT `username`, its field `Username` remains `nullptr`.
So there is no surprise you've got a segmentation fault as you are dereferencing `nullptr`.

```cpp
ENDPOINT("POST", "users", createUser,  BODY_DTO(Object<UserDto>, userDto))
{
       std::string test = userDto->userName->c_str();  // userDto->userName is nullptr 

       return createDtoResponse(Status::CODE_200, m_userService.createUser(userDto));
}
```

Just check for nullptr and throw an error if it is.

```cpp
ENDPOINT("POST", "users", createUser,  
         BODY_DTO(Object<UserDto>, userDto)) 
{
  OATPP_ASSERT_HTTP(userDto->userName, Status::CODE_400, "username is required!");
  std::string test = userDto->userName->std_str();
  ...
  return createDtoResponse(Status::CODE_200, m_userService.createUser(userDto));
}
```

Also, you can use `userName->std_str();` to convert to `std::string` directly.

Regards,
Leonid

**Comment by sovamaster** [comment]
Thank you for help.
