### ISSUE TITLE
HTTP parameter validation

### ISSUE THREAD

**Issue by edimoldovan** [oatpp/oatpp#356]
Hi folks,

I was trying to find out how a more granular parameter validation should be done. Say I have a DTO with two fields: one string and one int. The extra validation I want to have is the string should be maximum 10 characters long and the int should be between 5 and 10.

What would be the suggested way to go about this with oatpp? 

Thank you,
ed

**Comment by lganzzzo** [comment]
Hello @edimoldovan ,

At the moment you have to do it on your own on the endpoint side. (Later, maybe we'll introduce some kind of fine-grained validations for DTOs, but it's not in the scope at the moment)

```cpp
  ENDPOINT("POST", "users", createUser,
           BODY_DTO(Object<UserDto>, user))
  {
    OATPP_ASSERT_HTTP(user->name && user->name->size() > 10, Status::CODE_400, "username should be less than 10 chars long");
    return createDtoResponse(Status::CODE_200, m_userService.createUser(user));
  }
```
