### ISSUE TITLE
Intermittent "Current url has no mapping" (404) error

### ISSUE THREAD

**Issue by srogatch** [oatpp/oatpp#364]
For one of my endpoints `oatpp` intermittently replies "Current url has no mapping" to a GET request. Exactly one good request, one bad, and so on. Details of the response:
```
server=oatpp/1.1.0
code=404
description=Not Found
message=Current url has no mapping
```
Approximately, the code I use for defining the endpoint is as follows:
```
_pRouter = oatpp::web::server::HttpRouter::createShared();
_pDownloadRH = std::make_shared<DownloadRequestHandler>(/*...*/);
std::string sPath = "/download";
_pRouter->route("GET", oatpp::String(sPath.c_str(), sPath.size(), true), _pDownloadRH);
_pConnectionHandler = oatpp::web::server::HttpConnectionHandler::createShared(_pRouter);
_pConnectionProvider = oatpp::network::server::SimpleTCPConnectionProvider::createShared(88, true);
_pServer = make_unique<oatpp::network::server::Server>(_pConnectionProvider, _pConnectionHandler);

// Then in another thread
_pServer->run();
```

The OS is Windows 2016 and 2019 Server 64-bit.

**Comment by lganzzzo** [comment]
Hello @srogatch ,

What is the client software that you are using to make a request? 
Is this issue reproducible using a browser and curl too?

There was a similar issue before - when making a call via Postman, it turned out that it was a bug in the Postman.

Also, I would recommend updating oatpp to `1.2.5` (the latest master) it will output the URL you are trying to hit in case of 404. Thus we can see if the URL gets corrupted.

**Comment by srogatch** [comment]
Hello @lganzzzo ! Thank you for the hints. Indeed, I am using Postman and the problem doesn't get reproduced in a browser.
While I'm upgrading to oatpp 1.2.5, can we discuss a bit related issue with URLs? When I pass a query parameter in PascalCase, I have to call `request->getQueryParameter()` with the same PascalCase. And vice versa, if `request->getQueryParameter("BlockToken")` is used, I cannot make a request with a lowercase parameter name. Is this as designed? Is there no case-insensitive alternative routines in oatpp?

**Comment by lganzzzo** [comment]
Hello @srogatch ,

Currently, oatpp is using `StringKeyLabel` as a key for [http::QueryParams](https://github.com/oatpp/oatpp/blob/master/src/oatpp/web/protocol/http/Http.hpp#L52), thus it's case-sensitive.
To make it case-INsensitive `QueryParams` template should use `StringKeyLabelCI` or `StringKeyLabelCI_FAST` as a parameter.

While it's very easy to change this, we have to make sure that we really want this change. URL query-parameters is something that is treated pretty differently by all web-frameworks and it's impossible to satisfy all cases. Also, URL components other than domain-name are case-sensitive (by rfc).

Ideally is to come up with some simple solution, how to make this configurable.

As a workaround, you can just take all query-parameters from the request and put them to the

```cpp
std::unordered_map<oatpp::data::share::StringKeyLabelCI> map;
```

Then you can query its entries in a case-INsensitive manner.

**Comment by srogatch** [comment]
Thank you for the hints, @lganzzzo
