### ISSUE TITLE
Casting from "oatpp::data::mapping::type::String" to const char* or something like this

### ISSUE THREAD

**Issue by AIshutin** [oatpp/oatpp#37]
Hello!

Thanks for awesome framework. I'm trying to get started. By the way, without a documentation it's quite difficult. So, my problem is converting oatpp::data::mapping::type::String to something like char* for interaction with other frameworks. How can I cast oatpp::data::mapping::type::String

**Comment by lganzzzo** [comment]
Hello,

```cpp
oatpp::String a = "text";
const char* b = a->c_str();
```

Regards

**Comment by AIshutin** [comment]
Thanks a lot!

**Comment by lganzzzo** [comment]
You are welcome!
