### ISSUE TITLE
bad_function_call after calling server->run()

### ISSUE THREAD

**Issue by jose-martin-m** [oatpp/oatpp#372]
After updating to the most recent commit I'm getting a `bad_function_call` error on my project when calling `server->run()`.

Using 
```c++
std::function<bool()> condition = []{return true;};
  server->run(condition);
```
seems to fix it for now.

**Comment by bamkrs** [comment]
Nice catch, already running the tests on the fix!

In the meantime you can use `server->run(false);` and ignore the warning. It's more performant.
