### ISSUE TITLE
Does it support Https?

### ISSUE THREAD

**Issue by suvidh** [oatpp/oatpp#374]
I basically do not want my website to have "not secure" tag..

**Comment by lganzzzo** [comment]
Hey @suvidh ,

Sure, just use one of the provided SSL adaptors:
- [oatpp-openssl](https://github.com/oatpp/oatpp-openssl)
- [oatpp-libressl](https://github.com/oatpp/oatpp-libressl)
- [oatpp-mbedtls](https://github.com/oatpp/oatpp-mbedtls)
