### ISSUE TITLE
How to return an answer while continuing to process long jobs

### ISSUE THREAD

**Issue by remioukrat** [oatpp/oatpp#379]
If I want to expose endpoint to do long computations, I must pass to the service the callback url. 
But I don’t want to block the service customer and I need to return it an answer while running computations. Once computations are finished, I will post results to the callback url.
I can do computations in a detached thread managed inside a homemade ThreadPool but I would like to know if there are some solutions provided by the API able to cover this need: "the ability to return an answer while continuing to process".

**Comment by lganzzzo** [comment]
Hey @remioukrat ,

The "homemade ThreadPool" or any 3rd party thread pool is a good solution if you want to do callback URLs.

```cpp
  ENDPOINT("POST", "calc", calculate,
           BODY_DTO(Object<CalculationParams>, params))
  {
    std::thread t([params]{ //<-- use a thread pool instead of a bare thread.
      calc(params); // do calcs here
      callback(params->callbackUrl);
    });
    return createResponse(Status::CODE_200, "calculating...");
  }
```

You may also consider other approaches:
- WebSockets
- Long Polling (blocks client)

**Comment by remioukrat** [comment]
Hi @lganzzzo thank you for your answer ;).
I would like just to know if there were other solutions provided by the API. 
So I have already homemade threadpool API  that I can use to do that :). For sure, I will use Websocket for callbacks.
