### ISSUE TITLE
What is the problem with a new failure in MemoryPool?

### ISSUE THREAD

**Issue by TheBestChenQiZhen** [oatpp/oatpp#383]
```cpp
void MemoryPool::allocChunk() {
#ifdef OATPP_DISABLE_POOL_ALLOCATIONS
  // DO NOTHING
#else
  v_buff_size entryBlockSize = sizeof(EntryHeader) + m_entrySize;
  v_buff_size chunkMemSize = entryBlockSize * m_chunkSize;

  p_char8 mem = new v_char8[chunkMemSize]; // Here, if new fails, how does it affect the program
  m_chunks.push_back(mem);

  for(v_buff_size i = 0; i < m_chunkSize; i++){
    EntryHeader* entry = new (mem + i * entryBlockSize) EntryHeader(this, m_id, m_rootEntry);
    m_rootEntry = entry;
  }
#endif
```

**Comment by lganzzzo** [comment]
Hey @TheBestChenQiZhen ,

If `new` fails the program will crash, and there is no recovery mechanism here.

The `MemoryPool::allocChunk()` is called when the pool is required to grow, and if it fails to grow - it's fatal.

**Comment by TheBestChenQiZhen** [comment]
> Hey @TheBestChenQiZhen ,
> 
> If `new` fails the program will crash, and there is no recovery mechanism here.
> 
> The `MemoryPool::allocChunk()` is called when the pool is required to grow, and if it fails to grow - it's fatal.

**Comment by lganzzzo** [comment]
Hey @TheBestChenQiZhen ,

I'm closing this one.
If you have more questions, please feel free to create another issue
