### ISSUE TITLE
Where can I find a sample code for a minimal HTTP-server?

### ISSUE THREAD

**Issue by ababo** [oatpp/oatpp#391]
I have found a dozen of fancy example apps, but I'm rather interested in a **minimal** server sample. Just to start a HTTP server on a given IP address and port having a single handler. Without environment variables, ORM, Swagger and other cool stuff. Can you share a link?

**UPDATE**: Also would be nice to know the way to stop it gracefully.

**Comment by lganzzzo** [comment]
Hello @ababo ,

Please find:
- [oatpp-starter](https://github.com/oatpp/oatpp-starter)
- [step-by-step guide](https://oatpp.io/docs/start/step-by-step/)

Regards,
Leonid

**Comment by ababo** [comment]
@lganzzzo Thank you, the second link is indeed close to what I need. The only question that remains is about graceful closing. Can you suggest a method to close the server?

**Comment by lganzzzo** [comment]
@ababo ,

Please find this example of stopping server by a signal - https://github.com/lganzzzo/oatpp-sig-int-example/blob/master/src/App.cpp

**Comment by ababo** [comment]
Thank you! Closing as resolved.
