### ISSUE TITLE
Can I Intercept all requests  to auth them?

### ISSUE THREAD

**Issue by fanties** [oatpp/oatpp#392]
Because all requests use the same auth logic ,so I want auth them just once. What should I do? Thanks.

**Comment by lganzzzo** [comment]
Hello @fanties ,

Sure, you have to implement a `RequestInterceptor`.

```cpp
#include "oatpp/web/server/interceptor/RequestInterceptor.hpp"

class AuthInterceptor : public oatpp::web::server::interceptor::RequestInterceptor {
public:
  std::shared_ptr<OutgoingResponse> intercept(const std::shared_ptr<IncomingRequest>& request) override {
    
    // TODO - your auth logic
    
    if(<authorized>) {
      return nullptr; // return null to continue with this request
    } 

    throw oatpp::web::protocol::http::HttpError(oatpp::web::protocol::http::Status::CODE_401, "Unauthorized", {});

  }
};
```

Then add this request interceptor to your connection handler

```cpp
connectionHandler->addRequestInterceptor(std::make_shared<AuthInterceptor>());
```

**Comment by fanties** [comment]
@lganzzzo Thank you very much,
Now, I want know if can I user the RequestInterceptor  and AuthorizationHandler together.
example:
`class MyController : public oatpp::web::server::api::ApiController {
public:

  MyController(OATPP_COMPONENT(std::shared_ptr<ObjectMapper>, objectMapper) /* Inject object mapper */)
    : oatpp::web::server::api::ApiController(objectMapper) 
  {
    setDefaultAuthorizationHandler(std::make_shared<MyBearerAuthorizationHandler>());
  }

  ENDPOINT("GET", "/my/secret/resource", getResource,
           AUTHORIZATION(std::shared_ptr<MyAuthorizationObject>, authObject)) 
  {
    OATPP_ASSERT_HTTP(authObject->userId == "uid-admin", Status::CODE_401, "Unauthorized");
    return createResponse(Status::CODE_200, "OK");
  }

};`
like the code above,
' OATPP_ASSERT_HTTP(authObject->userId == "uid-admin", Status::CODE_401, "Unauthorized");'
OATPP_ASSERT_HTTP is in the Endpoint, can I use it in the Interceptor  .

Or is there another way?

**Comment by lganzzzo** [comment]
Yes, you can use them together.
You can filter by a request path in the interceptor - which requests to intercept.
