### ISSUE TITLE
Question about streaming possibility

### ISSUE THREAD

**Issue by elgatito** [oatpp/oatpp#397]
Hello, 

I'm investigating this library and can't find the way how to implement file streaming with it.

Let's assume huge file is stored in another storage, so I want to use own implementation of file stream, that implements (open/seek/read/write), which then can be used by a framework to get/send chunks of bytes to requestor of this file.

Is this possible with the current state?

**Comment by lganzzzo** [comment]
Hey @elgatito ,

Streaming is one of the main features of oatpp.

Example streaming a file:

```cpp
ENDPOINT("GET", "/download", download) {

  auto body = std::make_shared<oatpp::web::protocol::http::outgoing::StreamingBody>(
    std::make_shared<oatpp::data::stream::FileInputStream>("path/to/file")
  );

  return OutgoingResponse::createShared(Status::CODE_200, body);

}
```

And if you want completely custom streaming, then you extend `oatpp::data::stream::ReadCallback`:

```cpp

class MyReadCallback : public oatpp::data::stream::ReadCallback {
public:

  v_io_size read(void *buffer, v_buff_size bufferSize, async::Action& action) override {

    (void) action; // ignore action when using SimpleAPI

    if(<I have more to stream>) {
      // TODO - fill-in buffer with your data
      return <amount of bytes written to buffer>
    }

    return 0; // I don't have anything more to stream. Return 0.

  }

};

ENDPOINT("GET", "/download", download) {

  auto body = std::make_shared<oatpp::web::protocol::http::outgoing::StreamingBody>(
    std::make_shared<MyReadCallback>()
  );

  return OutgoingResponse::createShared(Status::CODE_200, body);

}
```

Regards,
Leonid

**Comment by elgatito** [comment]
@lganzzzo Does oatpp then properly deal with `Range` headers, that usually come when requesting to continue the stream?

Also there are usually `HEAD` calls to the same url to validate the file and it's length, without getting the body. 
It should be placed here?
```
void StreamingBody::declareHeaders(Headers& headers) {}
```

**Comment by lganzzzo** [comment]
@elgatito ,

Head will be in the separate endpoint:

```cpp
ENDPOINT("HEAD", "/download", download) {
  auto response = OutgoingResponse::createShared(Status::CODE_200, "");
  // set response headers
  return response;
}
```

Range - you will have to deal with it on your own.
There are some helpers though:

```cpp
ENDPOINT("HEAD", "/download", download, 
         HEADER(String, rangeHeader, Header::RANGE)) 
{

  auto range = oatpp::web::protocol::http::Range::parse(rangeHeader);
  OATPP_LOGD("Range", "start=%d, end=%d", range.start, range.end);

  auto body = std::make_shared<oatpp::web::protocol::http::outgoing::StreamingBody>(
    std::make_shared<MyReadCallback>(range) //<-- pass range to your callback
  );

  auto response = OutgoingResponse::createShared(Status::CODE_200, body);

  oatpp::web::protocol::http::ContentRange contentRange(oatpp::web::protocol::http::ContentRange::UNIT_BYTES,
                                                        range.start, range.end, <full-size>, true);

  response->putHeader(Header::CONTENT_RANGE, contentRange.toString());

  return response;
}
```

**Comment by elgatito** [comment]
Hm.. Looks interesting. I will try to use this approach.
Thanks!

**Comment by lganzzzo** [comment]
Hey @elgatito ,
I have just edited my answer fixing a typo. The second endpoint should be `GET`.

**Comment by elgatito** [comment]
@lganzzzo I am now implementing streaming. Noticed buffer is 2kb. Is that changeable? Thanks

**Comment by lganzzzo** [comment]
Hey @elgatito ,

Do you mean buffer that in in the `ReadCallback`?

The good answer is that it's not configurable at the moment... 

But you can take advantage of the current implementation.- Currently, oatpp reuses headers output buffer for streaming,
so if you increase [headersOutBufferInitial](https://github.com/oatpp/oatpp/blob/master/src/oatpp/web/server/HttpProcessor.hpp#L71) then you should get a larger buffer in the `ReadCallback`

```cpp
OATPP_CREATE_COMPONENT(std::shared_ptr<oatpp::network::ConnectionHandler>, serverConnectionHandler)([] {
  OATPP_COMPONENT(std::shared_ptr<oatpp::web::server::HttpRouter>, router); // get Router component

  auto config = std::make_shared<oatpp::web::server::HttpProcessor::Config>();
  config->headersOutBufferInitial = 16 * 1024;

  return std::make_shared<oatpp::web::server::HttpConnectionHandler>(router, config);
}());
```

**Comment by elgatito** [comment]
@lganzzzo Awesome! Perfectly working! 

```
    OATPP_CREATE_COMPONENT(std::shared_ptr<oatpp::network::ConnectionHandler>, serverConnectionHandler)([] {
        OATPP_COMPONENT(std::shared_ptr<oatpp::web::server::HttpRouter>, router);
        OATPP_COMPONENT(std::shared_ptr<oatpp::data::mapping::ObjectMapper>, objectMapper);

        auto config = std::make_shared<oatpp::web::server::HttpProcessor::Config>();
        config->headersOutBufferInitial = 16 * 1024;

        auto connectionHandler = std::make_shared<oatpp::web::server::HttpConnectionHandler>(router, config);
        connectionHandler->setErrorHandler(std::make_shared<lh::ErrorHandler>(objectMapper));
        return connectionHandler;
    }());
```

**Comment by elgatito** [comment]
@lganzzzo it is easier to track the issue on github, so I will move here.

If we look here: https://github.com/oatpp/oatpp/blob/master/src/oatpp/web/protocol/http/outgoing/Response.cpp#L102

```
      if (bodySize >= 0) {
        m_headers.put_LockFree(Header::CONTENT_LENGTH, utils::conversion::int64ToStr(bodySize));
      } else {
        m_headers.put_LockFree(Header::TRANSFER_ENCODING, Header::Value::TRANSFER_ENCODING_CHUNKED);
      }
```

To avoid having `Transfer-encoding` header I need to set body size.

But later: https://github.com/oatpp/oatpp/blob/master/src/oatpp/web/protocol/http/outgoing/Response.cpp#L133

```
if (bodySize >= 0) {

        if (bodySize + headersWriteBuffer->getCurrentPosition() < headersWriteBuffer->getCapacity()) {
          headersWriteBuffer->writeSimple(m_body->getKnownData(), bodySize);
          headersWriteBuffer->flushToStream(stream);
        } else {
          headersWriteBuffer->flushToStream(stream);
          stream->writeExactSizeDataSimple(m_body->getKnownData(), bodySize);
        }

      } else {

        headersWriteBuffer->flushToStream(stream);

        http::encoding::EncoderChunked chunkedEncoder;

        /* Reuse headers buffer */
        data::stream::transfer(m_body, stream, 0, headersWriteBuffer->getData(), headersWriteBuffer->getCapacity(), &chunkedEncoder);

      }
```

If I set body size - then I will not get to `data::stream::transfer` and response is calling `getKnownData`, which does not use read callback.

Sadly, the way with `StreamingBody` works perfectly for all the cases, but adds additional header, which I cannot remove from `Headers` after it's there, right?

**Comment by elgatito** [comment]
What if we change this line: https://github.com/oatpp/oatpp/blob/d6521d2178f0cbc661a4b6ef6c0c4893557837aa/src/oatpp/web/protocol/http/outgoing/Response.cpp#L133

```
      if (bodySize >= 0) {
```

To this:
```
if (bodySize >= 0 && m_status != Status::CODE_206) {
```

It will then add header `Content-length` if length is known. But then use streaming callbacks for status 206.

**Comment by lganzzzo** [comment]
Hey @elgatito ,

Thanks for the detailed description of the issue, and sorry for the late reply.

I think it might be better to do the following (to be more flexible with the response statuses):

```cpp
      if (bodySize >= 0) {

        if(m_body->getKnownData() == nullptr) { //<-- add this check
  
          headersWriteBuffer->flushToStream(stream);
          /* Reuse headers buffer */
          /* Transfer without chunked encoder */
          data::stream::transfer(m_body, stream, 0, headersWriteBuffer->getData(), headersWriteBuffer->getCapacity());

        } else { 

          if (bodySize + headersWriteBuffer->getCurrentPosition() < headersWriteBuffer->getCapacity()) {
            headersWriteBuffer->writeSimple(m_body->getKnownData(), bodySize);
            headersWriteBuffer->flushToStream(stream);
          } else {
            headersWriteBuffer->flushToStream(stream);
            stream->writeExactSizeDataSimple(m_body->getKnownData(), bodySize);
          }

        }

      } else {

        headersWriteBuffer->flushToStream(stream);

        http::encoding::EncoderChunked chunkedEncoder;

        /* Reuse headers buffer */
        data::stream::transfer(m_body, stream, 0, headersWriteBuffer->getData(), headersWriteBuffer->getCapacity(), &chunkedEncoder);

      }
```

Thus we are able to do streaming without `EncoderChunked` applied to our stream.

**Comment by elgatito** [comment]
@lganzzzo That looks better than by modification. I wanted to avoid calling KnownData, did not realize it is just a pointer, not a data itself...

It would be still great to avoid printing body for HEAD requests from the server side, maybe in future, it will make life a little easier.

**Comment by elgatito** [comment]
@lganzzzo Awesome! It is working! My approach was somehow modifying the body and it was corrupted, your approach works perfectly. But I had to make own `StreamingBody` with positive size and `EmptyBody` for `HEAD` responses.

**Comment by lganzzzo** [comment]
Nice, thanks for the update!

Yes, `data::stream::transfer()` should've been called without encoder.

**Comment by elgatito** [comment]
@lganzzzo Definitely not the good coding, but for reference, here is my code:
https://github.com/ElementumOrg/lt2http/blob/master/src/web/stream.h#L73

I would like to see a second constructor in `StreamingBody` to take `Content-Length` as a second parameter, to return it for `getKnownSize`.

**Comment by elgatito** [comment]
Closing this as streaming is correctly working. Will wait for next releases with a fix regarding `Transfer-Encoding`, hopefully.
Thanks
