### ISSUE TITLE
Unit Testing Multipart Upload

### ISSUE THREAD

**Issue by electronstorm** [oatpp/oatpp#398]
Hi,

I have implemented a multipart file upload according to the documentation. The code works fine when I test it in a browser or curl.

Having unit test for the route in question is very deseriable from a maintenance point of view. However, I am unable to find an example for creating a corresponding API_CALL for an API_CLIENT to actually trigger the route in a unit test environment. This works just fine for regular GET/POST-Requests with just a BODY_STRING. 

Below is an example for a regular POST route:

```
class ApiTestClient: public oatpp::web::client::ApiClient
{
    API_CLIENT_INIT(ApiTestClient)

    API_CALL("POST", ""/example, exampleOperation);

};

```

**Comment by lganzzzo** [comment]
Hello @electronstorm ,

To send multipart via `ApiClient` just declare `API_CALL` as follows:

```cpp
API_CALL("POST", "/multipart", multipartTest, BODY(std::shared_ptr<MultipartBody>, body))
```

An example of using such API call you can find in oatpp tests - https://github.com/oatpp/oatpp/blob/master/test/oatpp/web/FullTest.cpp#L456

**Comment by electronstorm** [comment]
Thanks for the quick response @lganzzzo. I was able to get the unit tests working correctly with that.
