### ISSUE TITLE
Question about curl usage

### ISSUE THREAD

**Issue by elgatito** [oatpp/oatpp#399]
Hello,

I have noticed that there Curl classes in oatpp. 

I need to download user-defined files from the internet Nothing special, no SNI, certificate validation and so on, just try to download small file. 
I was thinking to use existing functionality in oatpp for that to avoid getting more dependencies.

Is that possible?

**Comment by lganzzzo** [comment]
Hey @elgatito ,

Sure just use the native oatpp client.
Curl classes are presented in the client exaple just to show that you can use both.

Regards,
Leonid

**Comment by elgatito** [comment]
@lganzzzo 
I believe I do that in a wrong way:
```
                OATPP_COMPONENT(std::shared_ptr<oatpp::network::ClientConnectionProvider>, clientConnectionProvider);
                auto retryPolicy = std::make_shared<oatpp::web::client::SimpleRetryPolicy>(-1, std::chrono::seconds(1));
                auto requestExecutor = oatpp::web::client::HttpRequestExecutor::createShared(clientConnectionProvider, retryPolicy);
                
                auto headers = oatpp::web::protocol::http::Headers();
                oatpp::String bodyBuffer("");
                auto body = std::make_shared<oatpp::web::protocol::http::outgoing::BufferBody>(oatpp::web::protocol::http::outgoing::BufferBody(bodyBuffer, "text/plain"));
                auto connection = requestExecutor->getConnection();
                auto resp = requestExecutor->executeOnce("GET", oatpp::String(uri.c_str()), headers, body, connection);

                auto resp_body = resp->readBodyToString();
```

It does send the request to my running server, not to the internet, url is surely `http://...`.

**Comment by lganzzzo** [comment]
Hey @elgatito ,

The client connection provider is already initialized with the domain name.
The `executeOnce` method doesn't accept URL, it accepts path.

So instead of `http://domain.com/path/to/endpoint` it should be path only - `path/to/endpoint`

Please let me know if it worked.

Regards,
Leonid

**Comment by elgatito** [comment]
@lganzzzo In my case I need to download files from the internet, not from my server.

**Comment by lganzzzo** [comment]
@elgatito ,

if you want to make request to ex.: `http://httpbin.org/get`:

```cpp
auto connectionProvider = oatpp::network::tcp::client::ConnectionProvider::createShared({"httpbin.org", 80});
auto httpExecutor = oatpp::web::client::HttpRequestExecutor::createShared(connectionProvider);

auto response = httpExecutor->execute("GET" /* method */, 
                                      "get" /* path */,
                                       {} /* headers */,
                                       nullptr /* body */);
```

if you want to make a `HTTPS` request to ex.: `https://httpbin.org/get`:

```cpp
auto connectionProvider = oatpp::openssl::client::ConnectionProvider::createShared({"httpbin.org", 443});
auto httpExecutor = oatpp::web::client::HttpRequestExecutor::createShared(connectionProvider);

auto response = httpExecutor->execute("GET" /* method */, 
                                      "get" /* path */,
                                       {} /* headers */,
                                       nullptr /* body */);
```

**Comment by elgatito** [comment]
@lganzzzo Thanks, that is much easier.
I almost finished with that, but then one of test cases was giving a 301 response, so a proper follow redirect should be also there.
So I will skip this for the moment.
Thanks for helping.

**Comment by lganzzzo** [comment]
Hey @elgatito ,

FYI.

> I almost finished with that, but then one of test cases was giving a 301 response

Oat++ client won't follow redirect automatically. You'll have to implement it on your own.
