### ISSUE TITLE
Feature request: Add timers to measure handlers execution

### ISSUE THREAD

**Issue by elgatito** [oatpp/oatpp#400]
Hello,

It is helpful often to have information about execution times for each handler.
It can be enabled/disabled by some setting, or when running with debug profile, or any other method of turning on and off.

It can log execution times to a log file, for example.

In a perfect case it would be great to have a report like this:
```
description                                                                             total          count  min           mean          max
SampleController::newItem                                                               14.517443127s  551    8.439112ms    26.347446ms   98.417725ms
SampleController::items                                                                 8.325929056s   1      8.325929056s  8.325929056s  8.325929056s
AnotherController::handler                                                              8.318403705s   277    2.527119ms    30.030338ms   381.661601ms
```

If you feel that is a bad idea - you can close the issue.

**Comment by JeremyGuinn** [comment]
IMO I don't think it is within the scope of oatpp itself. If an interface was necessary for ease of use, I could see a module being added, however this could be accomplished using a metrics library. OpenCensus is popular and offers a c++ library, and you should be able to drop a metrics library right into your controllers and services without any finagling.

**Comment by lganzzzo** [comment]
I would agree with @JeremyGuinn ,
Profiling endpoints is out of the scope of the main oatpp module.
It can be accomplished with 3rd party libs.
