### ISSUE TITLE
[offtopic] How should one compare C++ frameworks?

### ISSUE THREAD

**Issue by SamuelMarks** [oatpp/oatpp#401]
For the database layer, I am currently weighing up [ODB](https://www.codesynthesis.com/products/odb), [Oat++](https://oatpp.io), [SOCI](http://soci.sourceforge.net), [cppdb](http://cppcms.com/sql/cppdb), and [sqlpp11](https://github.com/rbock/sqlpp11) [if sqlpp adds support for `CREATE TABLE`]. Also [drogon](https://github.com/an-tao/drogon) seem to have its own [ORM](https://en.wikipedia.org/wiki/Object%E2%80%93relational_mapping) layer, but with only [PostgreSQL](https://www.postgresql.org) and [MySQL](https://www.mysql.com) support I'm a little worried from a testing and server-less perspective (really would be nice to see support for an embedded database like [SQLite](https://www.sqlite.org)).

For the [REST API](https://en.wikipedia.org/wiki/REST_API) layer I haven't started investigating, although I do remember [actix](https://actix.rs) being dethroned and the [drogon C++ framework taking its place](https://github.com/an-tao/drogon).

---

I am planning to use [LLVM](https://llvm.org) ([clang](https://clang.llvm.org), [libclang](https://clang.llvm.org/doxygen/group__CINDEX.html), [libtooling](https://clang.llvm.org/docs/LibTooling.html)) to synchronise [bidirectionally] [OpenAPI](https://en.wikipedia.org/wiki/OpenAPI_Specification) with C++ code. I've done the same in Python, and WiP for Rust, Swift, Java, Kotlin, and TypeScript.

With my compiler driven approach, I expect people to be able to rapidly produce REST API + db backends with full test and doc coverage, and be able to immediately translate the interfaces across language boundaries (e.g., to frontends, or to rewrite a slow-performing Python backend in C++ or Rust).

Currently focussing on the non-[Turing-complete](https://en.wikipedia.org/wiki/Turing_complete) as aspect of this, translating just the interfaces, tests, docs, defaults, and types.

---

I am writing tools to allow engineers to develop faster, and with higher quality. Will only target one ORM and one REST API layer for C++, at least in the short-term.

So my question is, and I understand that posting here will provide a heavily biased answer, how do I decide between the various C++ frameworks?

Thanks

**Comment by bamkrs** [comment]
Keeping it short an simple without bias, as I'm writing this on my mobile with sleepy eyes.

In your case I would search for two mayor things. Modularity and active development. 
With a highly modular framework, you can change parts of it to perfectly fit your tool(s) and needs without touching/forking or ugly hacks in the codebase. Active development is helping as well. From support to new features that might be useful to you (and might be mainlined).
The next minor thing would be the ease of use in a tooling perspective: How easy is it to generate the code with simple Code-Generators. How powerful are these etc. 

I won't brag about it how good Oat++ accomplishes these things and why I decided to go Oat++ everywhere. That's something you should explore for yourself and make up your own mind. 

However we are happy to help you in any regard and answer all your questions. 
And trust me, Sqlite3 support should not be a showstopper ;)

**Comment by SamuelMarks** [comment]
@bamkrs Certainly Oat++ is the closest of all the solutions I've found to having what I need, as it actually considers the benefit of OpenAPI and has built-in table schemas:
https://github.com/oatpp/example-crud/blob/c234830/src/dto/UserDto.hpp#L14-L22

But there still seems to be a bunch of expected knowledge throughout, non standard eccentricities.

However without reflection (C++23?) I don't know how to do this properly. I mean, I suppose one could write an external tool (with libtooling or libclang) to handle the changes, or use the old `m4` solution. But yeah, possibly what Oat++ has done is best available.

**Comment by lganzzzo** [comment]
@SamuelMarks ,

> So my question is, and I understand that posting here will provide a heavily biased answer, how do I decide between the various C++ frameworks?

The best way to get a non-biased answer is to ask Oat++ users.
Oat++ is used pretty extensively both in commercial projects and open-source.

For use-cases, you can try to catch guys in the [Oat++ devs chat on Gitter](https://gitter.im/oatpp-framework/Lobby).
And Oat++ in other open-source projects:

- https://github.com/milvus-io/milvus
- https://github.com/jolibrain/deepdetect
- https://github.com/Yadoms/yadoms-swagger

**Comment by SamuelMarks** [comment]
deepdetect looks pretty cool. Tempted not to use Oat++ because of them, so I can rewrite it in something else 😝
Also Oat++ is the only framework I found that actually takes a stab at OpenAPI.

Not an easy decision to make!
