### ISSUE TITLE
Allow duplicate keys in QueryParams

### ISSUE THREAD

**Issue by n-sakai0313** [oatpp/oatpp#402]
### brief.
Currently, query-params are stored as LazyStringMap which doesn't allow duplicate keys.
LazyStringMultimap instead,- to allow duplicate keys.

### gitter QA.
Q:
Hello.
I have a question about QueryParams. Could you tell me how to get query parameters with the same key? for instance, "http://localhost/objects/images?param=hoge&param=piyo".
A:
Hello @n-sakai0313 ,
Currently, query-params are stored as LazyStringMap which doesn't allow duplicate keys.
I think we should change that to use LazyStringMultimap instead,- to allow duplicate keys.
@n-sakai0313 please create an issue on github for that

**Comment by bamkrs** [comment]
Thats indeed a nice and needed feature!
However, isn't the convention to write it like "http://localhost/objects/images?param[]=hoge&param[]=piyo"? AFAIK this is the PHP-Style for this?

**Comment by lganzzzo** [comment]
Unfortunately, there is no convention. All web-frameworks do it differently.
So we have to think of a most flexible and hopefully most convenient way of reading query-params with duplicate keys - 
Ideally preserving the order of entries.

**Comment by jjmcwill** [comment]
is there a release target for this?

**Comment by lganzzzo** [comment]
Implemented in `1.3.0` see the [changelog](https://github.com/oatpp/oatpp/blob/master/changelog/1.3.0.md#queryparameters-stored-in-unordered_multimap)
