### ISSUE TITLE
[Feature Request] Add a timeout to Pool::get()

### ISSUE THREAD

**Issue by jmml97** [oatpp/oatpp#408]
In [`Pool::get()`](https://github.com/oatpp/oatpp/blob/d6521d2178f0cbc661a4b6ef6c0c4893557837aa/src/oatpp/core/provider/Pool.hpp#L234) when there are no available connections and the maximum number of connections has been reached there is a [wait](https://github.com/oatpp/oatpp/blob/d6521d2178f0cbc661a4b6ef6c0c4893557837aa/src/oatpp/core/provider/Pool.hpp#L241) for a connection to be available. 

There should be an optional timeout so that it is possible to halt that wait after some time has passed. Sometimes that waiting time could be unacceptably long and Oat++ should be able to respond to the petition that generated that wait with an error.

**Comment by MHaselmaier** [comment]
@lganzzzo I suppose this issue can be closed now, with the PR merged.

**Comment by lganzzzo** [comment]
Yes, this one is implemented and will be available starting from oatpp `1.3.0`
