### ISSUE TITLE
Parsing json from postgresql

### ISSUE THREAD

**Issue by Maximsiv1410** [oatpp/oatpp#409]
Hello again!
As far as I know, Json type isn't supported yet in oatpp-postgresql module.
But still I want to ask you if there is some proper way to solve the following problem:
Consider having table with name "example" where 'config' column has 'json' type.

id | config | text
------------ | ------------- | ---------------
1 | {"someParam":12, "anotherParam":"value"} | "first"
2 | {"someParam":15, "newParam":true} | "second"

and the corresponding DTO
```
class ExampleDto : public oatpp::DTO {
    DTO_INIT(ExampleDto, DTO)

    DTO_FIELD(Int32, id);
    DTO_FIELD(??, config);    // <----- the problem
    DTO_FIELD(String, text);
};
```
the query 
`QUERY(getExample, "SELECT id, config, text FROM example WHERE id=:id", PARAM(oatpp::Int32, id))`
and finally fetching code(query executing code is omitted due to it's stable success)
`auto result = dbResult->fetch<oatpp::Vector<oatpp::Object<ExampleDto>>>();`

Also, I've tried to use` DTO_FIELD(oatpp::Any, config);` , but it have caused the following error:
> "oatpp::postgresql::mapping::Deserializer::deserializeAny()]: Error. Unknown OID."

 I don't know the structure of 'config' to describe it in DTO at compile time(the structure is little bit dynamic), but I still want to return response with body of json type.
Actually, I have some ideas, but it will be great if you help me to solve it in the most natural way of this framework

**Comment by lganzzzo** [comment]
Hey @Maximsiv1410 ,

You right, the JSON and JSONB are not supported yet with `oatpp-postgresql`.
The known workaround is to cast (on DB side) JSON to string. 
Thus you'll be able to read value as string and later manually parse it as JSON.

```cpp
class ExampleDto : public oatpp::DTO {
    DTO_INIT(ExampleDto, DTO)

    DTO_FIELD(Int32, id);
    DTO_FIELD(oatpp::String, config); 
    DTO_FIELD(String, text);
};

...

QUERY(getExample, "SELECT <!! id, config::TEXT, text !!> FROM example WHERE id=:id", PARAM(oatpp::Int32, id))
```

**Comment by Maximsiv1410** [comment]
Thanks for your reply, I thought about exactly the same solution!

**Comment by gaoyonghero** [comment]
@lganzzzo   
 Dear author, I hope you can answer my doubts and help me solve the problem.
