### ISSUE TITLE
Server side QUERY maco

### ISSUE THREAD

**Issue by sauntor** [oatpp/oatpp#41]
I see that there is a macro named `QUERY` in `oatpp/codegen/codegen_define_ApiClient_.hpp`, why not in the 'oatpp/codegen/codegen_define_ApiController_.hpp'? I think it's a **necessary** feature. Thanks.

**Comment by lganzzzo** [comment]
Hello @sauntor ,
Thank you for your interest in the project and for a feature request!

I plan to work on this feature sometime in future.
Meanwhile please note that you can get query params of the request using `oatpp::network::Url` class. More details here https://github.com/oatpp/oatpp/issues/20

Regards,
Leonid

**Comment by lganzzzo** [comment]
Query parameters mapping functionality is added in https://github.com/oatpp/oatpp/pull/46
