### ISSUE TITLE
Save headers to file

### ISSUE THREAD

**Issue by nikpx** [oatpp/oatpp#416]
Hello,

Apologies in advance if my question is silly.

I was reading the provided examples ( https://oatpp.io/docs/start/step-by-step/#simplest-project ) and I would like to ask if the library supports a safe way to store the headers of a received request into a file on disk. Does the library offer an implementation or this should be taken care by the developer (e.g. by using 'ofstream' in a safe way?)

**Comment by lganzzzo** [comment]
Hey @nikpx ,

The most straightforward way would be to iterate through the headers map and save them all to file.
You can do it on the ENDPOINT or inside the request interceptor.

Something like this:
```cpp
auto headers = request->getHeaders().getAll();
for(auto& h : headers) {
  stream << h.first->c_str() << ": " h.second->c_str() << "\r\n";
}
// TODO dump string stream to file
```

**Comment by mochechan** [comment]
Unfortunately, the following code cannot be compiled due to "h.first->c_str()" meets "error: base operand of '->' has non-pointer type 'oatpp::data::share::StringKeyLabel'".
```
auto headers = request->getHeaders().getAll();
for(auto& h : headers) {
  stream << h.first->c_str() << ": " h.second->c_str() << "\r\n";
}
// TODO dump string stream to file
```
