### ISSUE TITLE
[Swagger] Add functionality to declare DTO fields as required 

### ISSUE THREAD

**Issue by LaurentBergeron** [oatpp/oatpp#417]
Currently we can declare path variables and query parameters of an endpoint as required, but not DTO fields. Can we add that functionality?

If I were to add such functionality how would I go about doing it?

**Comment by lganzzzo** [comment]
Hello @LaurentBergeron ,

I think we can add this in `1.3.0`.

> If I were to add such functionality how would I go about doing it?

It should be fairly simple:

First - add `bool required` to [Property::Info](https://github.com/oatpp/oatpp/blob/master/src/oatpp/core/data/mapping/type/Object.hpp#L61) thus it will be possible to specify if the field is required:

```cpp
class MyDto : public oatpp::DTO {
  
  DTO_INIT(MyDto, DTO)

  DTO_FIELD_INFO(myRequiredField) {
    info.required = true; // mark field as required
  }
  DTO_FIELD(String, myRequiredField)

};
```

And second, we have to mark corresponding fields as required in the swagger schema.
For this, we have to put the names of all the required fields on the "required" list.
Here is the corresponding [method in the Swagger generator](https://github.com/oatpp/oatpp-swagger/blob/master/src/oatpp-swagger/Generator.cpp#L105).

And here is how the correct swagger schema should look like : https://stackoverflow.com/a/40113571/5664910

**Comment by LaurentBergeron** [comment]
Hi @lganzzzo,

I implemented those changes, they're ready for review. I need some permissions to create a PR. Thanks!

**Comment by bamkrs** [comment]
@LaurentBergeron why do you need those permissions? Just do a fork, push it to another branch in your fork and create a pull-request :)

**Comment by LaurentBergeron** [comment]
Thanks @bamkrs! This is my first contribution. I created PRs for https://github.com/oatpp/oatpp-swagger and for https://github.com/oatpp/oatpp.
