### ISSUE TITLE
Async client doesn't work

### ISSUE THREAD

**Issue by inver8** [oatpp/oatpp#434]
The second day I am trying to implement an asynchronous client, and while sync works as expected, async doesn't. After trying everything I decided to build [example-api-client](https://github.com/oatpp/example-api-client) and there the same thing, Coroutine every time throw an error:

`←[41;0m E ←[0m|2021-05-31 22:37:06 1622475426965775| AsyncExample:[Error] message='[oatpp::network::tcp::client::ConnectionProvider::getConnectionAsync()]: Error. Can't connect.`

      class SendDtoCoroutine : public oatpp::async::Coroutine<SendDtoCoroutine> {
          private:
              std::shared_ptr<DemoApiClient> m_client;
              oatpp::String m_message;
              v_int32 m_code;
          public:

        SendDtoCoroutine(const std::shared_ptr<DemoApiClient> client,
                         const oatpp::String &message,
                         v_int32 code)
            : m_client(client)
            , m_message(message)
            , m_code(code)     {}

        /**
         * Create DTO and send it via doPostWithDtoAsync method
         */
        Action act() override {
            auto dto = MyRequestDto::createShared();
            dto->message = m_message;
            dto->code = m_code;
            return m_client->doPostWithDtoAsync(dto).callbackTo(&SendDtoCoroutine::onResponse);
        }

        /**
         * Receive response and read body asynchronously
         */
        Action onResponse(const std::shared_ptr<Response> &response) {
            OATPP_LOGD(TAG, "[onResponse]");
            return response->readBodyToStringAsync().callbackTo(&SendDtoCoroutine::onBody);
        }

        /**
         * Print read body from the stream and finish
         */
        Action onBody(const oatpp::String &body) {
            OATPP_LOGD(TAG, "[doPostWithDtoAsync] data='%s'", body->c_str());
            return finish();
        }

        Action handleError(Error *error) override {
            OATPP_LOGE(TAG, "[Error] message='%s", error->what());
            return error;
        }

    };

All this I compile on Windows 10 and MSVC 2019

**Comment by lganzzzo** [comment]
Hey @inver8 ,

Make sure you have set the correct `host`/`port` in the connection provider.

The above error `Can't connect` means that for some reason client can't connect to the server.

Please post your `host`/`port` here (if it's public)

**Comment by inver8** [comment]
I tried different hosts, both http and https with the openssl module, 80 and 443 ports, build an example-api-client project with default `oatpp::network::tcp::client::ConnectionProvider::createShared({ "httpbin.org", 80 });`  sync requests working fine, problem is in async only, everywhere I get this error with async requests only, meantime sync requests have no problem. 
Don't know problem is in project settings or latest msvc compiler...
Guess error occurs somewhere in Corutines, in debug mode step by step after pass some iterations in `Processor.cpp` request execute without error 😕

**Comment by lganzzzo** [comment]
Ok, I think it's oatpp's issue.
Oat++ doesn't have at the moment a proper networking event interface like it has for Linux and BSD.
On Windows, it uses a naive implementation in order to provide compatibility with oatpp coroutines.

I think it might be an issue in this case. 
However, even this "naive" implementation was supposed to work on windows, it just won't provide the same performance as on Linux/BSD.

Thanks for reporting it.
We will have to look at this.

**Comment by lganzzzo** [comment]
Fixed in `1.3.0` see https://github.com/oatpp/oatpp/commit/5e9ae5796f45384ffb1c57cadc7eadf5a2072fa9 
Thanks to @NickPak
