### ISSUE TITLE
swagger codegen

### ISSUE THREAD

**Issue by XunChangqing** [oatpp/oatpp#438]
Hi,
  Can I generate server stub and client library from swagger doc?

BTW:
why is the GO SDK not based on rest api, rather then gRPC?

THANKS for you work!

**Comment by lganzzzo** [comment]
Hello @XunChangqing ,

Thanks for the questions.

> Can I generate server stub and client library from swagger doc?

This functionality is not ready yet. 
For details please follow this issue - https://github.com/oatpp/oatpp/issues/331

> why is the GO SDK not based on rest api, rather then gRPC?

As far as I know, you can easily create REST APIs in go. Ex.: see [net/http](https://golang.org/pkg/net/http/)
