### ISSUE TITLE
How to document parameter descriptions?

### ISSUE THREAD

**Issue by cgrantcal** [oatpp/oatpp#44]
Hey, 

Does anyone know how to add a description to the endpoint parameters. ~~inside of a DTO object~~. 

Currently on all examples i see the parameter descriptions empty.

![no_description](https://user-images.githubusercontent.com/48085845/53554683-354da880-3b38-11e9-8379-5b81acf34e1c.png)

Is this a limitation or is there a way to add the description?

Thanks

**Comment by lganzzzo** [comment]
Hello @cgrantcal ,
Thank you for the question!

I am currently working on this feature, so please wait for the update:).

I'll update this ticket once done.

Best Regards,
Leonid

**Comment by cgrantcal** [comment]
Hey @lganzzzo, 

Thanks for the prompt response ! I am researching the possibility of using oatpp in a project. Do you have a rough timeline when you think this would be available.

Many Thanks

Conor

**Comment by lganzzzo** [comment]
@cgrantcal

Tomorrow morning(european time) this feature should be available.

Regards,
Leonid

**Comment by lganzzzo** [comment]
@cgrantcal 

### additional param info:
- `info->pathParams["<param-name>"].description = "<text>"`  - path params
- `info->queryParams["<param-name>"].description = "<text>"` - query params
- `info->headers["<param-name>"].description = "<text>"` - headers

### add param not mentioned in the mapping:
*for add() method API may be changed to template*
- `info->pathParams.add("<param-name>", "<param-type>").description = "<text>"`  - path params
- `info->queryParams.add("<param-name>", "<param-type>").description = "<text>"` - query params
- `info->headers.add("<param-name>", "<param-type>").description = "<text>"` - headers

Example:
```cpp
ENDPOINT_INFO(putUser) {
    // general
    info->summary = "Update User by userId";
    info->addConsumes<UserDto::ObjectWrapper>("application/json");
    info->addResponse<UserDto::ObjectWrapper>(Status::CODE_200, "application/json");
    info->addResponse<String>(Status::CODE_404, "text/plain");
    // params specific
    info->pathParams["userId"].description = "User Identifier";
  }
  ENDPOINT("PUT", "demo/api/users/{userId}", putUser,
           PATH(Int32, userId),
           BODY_DTO(UserDto::ObjectWrapper, userDto)) {
    userDto->id = userId;
    return createDtoResponse(Status::CODE_200, m_database->updateUser(userDto));
  }
```

You need to get latest changes for `oatpp` and `oatpp-swagger` modules.

Regards,
Leonid
