### ISSUE TITLE
File upload

### ISSUE THREAD

**Issue by crisclacerda** [oatpp/oatpp#442]
Hi there I am getting started with oatpp and want to use to receive files from the web.
On the frontend I am using Quasar which have a neat uploader componet (https://quasar.dev/vue-components/uploader#quploader-api)
I have tried to use it with the first example in https://oatpp.io/docs/features/upload-file/
The problem is that is copies the "header" of the request to the file as well...
When opening the saved file I get the following:
`------WebKitFormBoundaryiNqjHTHMHDF2LIRS`
`Content-Disposition: form-data; name="undefined"; filename="00c8db16-2f12-4e56-b249-adb46ab5b300.jpg"`
`Content-Type: image/jpeg`
`...
binary data
...`
`------WebKitFormBoundaryiNqjHTHMHDF2LIRS--`

How do I save only the binary data on the file?
Do I need to create a custom dto or something?

**Comment by lganzzzo** [comment]
Hello @crisclacerda ,

It looks that you are uploading data as Multipart. 
So you have to parse the multipart data.

Please find an exaple how to parse multipart in oatpp tests - https://github.com/oatpp/oatpp/blob/master/test/oatpp/web/app/Controller.hpp#L252

Please let me know in case you have more questions.

Regards,
Leonid

**Comment by crisclacerda** [comment]
Awesome thanks so much for the quick reply.
You were exctaly right, managed to get it working. 
Is there any standart way to get the content type and filename of each part?

**Comment by lganzzzo** [comment]
Yes,

in case you are using the `PartList` - you can iterate available parts - https://github.com/oatpp/oatpp/blob/master/src/oatpp/web/mime/multipart/PartList.hpp#L87

Also, for the specific information about the part - you get the part headers - https://github.com/oatpp/oatpp/blob/master/src/oatpp/web/mime/multipart/Part.hpp#L110
