### ISSUE TITLE
Response with 'Transfer-Encoding: chunked'

### ISSUE THREAD

**Issue by lenikur** [oatpp/oatpp#446]
Hi there!
Absolutely great framework! Thanks a lot for this!
Getting started description is very clean.
Just one thing that I couldn't find how to implement. Here it is:
One endpoint should "stream" endless data. It should be implemented via chunk by chunk responses. Thus, I need to set 'Transfer-Encoding: chunked' to the response header, write data to the body and repeat it every time as new streamed data coming (business logic event). 
Could you help me to find out how this task could be implemented on your framework?
Thanks,
Nikita

**Comment by lganzzzo** [comment]
Hello @lenikur ,

What you need is the `oatpp::web::protocol::http::outgoing::StreamingBody`

```cpp

  class MyReadCallback : public oatpp::data::stream::ReadCallback {
  public:

    v_io_size read(void *buffer, v_buff_size count, async::Action& action) override {

      // ignote action for simpleAPI

      // TODO - fill 'buffer' of size 'count' with your data. Return the number of byes written to 'buffer'
      // Once done - return 0 to stop the stream

    }

  };

  ENDPOINT("GET", "chunked", chunked) {
    auto body = std::make_shared<oatpp::web::protocol::http::outgoing::StreamingBody(std::make_shared<MyReadCallback();
    return OutgoingResponse::createShared(Status::CODE_200, body);
  }
```

**Comment by lenikur** [comment]
Bravo, Leonid! It's a new world record for the question answering speed )

Please, tell me, is it possible to fill in the buffer using DTO object?
I mean something similar to this:
```
class MyData : public oatpp::DTO
{
 ...
};

  class MyReadCallback : public oatpp::data::stream::ReadCallback {
  public:

    v_io_size read(void *buffer, v_buff_size count, async::Action& action) override {

      // ignote action for simpleAPI
      auto myData = MyData::createShared();
      // fill myData
      // serialize myData to the buffer - is it doable?

    }

  };
```

**Comment by lganzzzo** [comment]
Sure, 

You have to use `oatpp::parser::json::mapping::ObjectMapper` to serialize DTO to string. Then just copy that string to buffer.

I'll post a code snippet later today if still needed

**Comment by lenikur** [comment]
It would be great if you post it.
From my side, I'd be happy to contribute to your [step-by-step](https://oatpp.io/docs/start/step-by-step/) manual as soon as I complete the task. Please write if you need it.
Thank you so much, Leonid.

**Comment by lenikur** [comment]
Hi again, Leonid!
It seems that the task is almost completed.. but I still have a serious showstopper.
I use postman for testing but it doesn't receive the response from this "streaming" endpoint, and I guess why..
here is the endless loop, as I never return 0 in MyReadCallback::read
```cpp
v_io_size transfer(const base::ObjectHandle<ReadCallback>& readCallback,
                         const base::ObjectHandle<WriteCallback>& writeCallback,
                         v_io_size transferSize,
                         void* buffer,
                         v_buff_size bufferSize,
                         const base::ObjectHandle<data::buffer::Processor>& processor)
{

  //...

  while(procRes != data::buffer::Processor::Error::FINISHED) { // <- never exit

    if(procRes == data::buffer::Processor::Error::PROVIDE_DATA_IN && inData.bytesLeft == 0) {

```
here is MyReadCallback::read
```cpp
class MyReadCallback : public oatpp::data::stream::ReadCallback
{
public:
    oatpp::v_io_size read(void* buffer, v_buff_size count, oatpp::async::Action& action) override 
    {
        auto quote = Quote::createShared();
        quote->t = 1234;
        quote->ap = 1.0002;
        quote->bp = 1.0000;

        oatpp::parser::json::mapping::ObjectMapper mapper;
        auto serializedQuote = mapper.writeToString(quote);
        if (serializedQuote->getSize() < count)
        {
            // it's not production code, but the point is that I need to wait here for new data coming 
            // and add it as another chunk to the initial request's response.
            std::memcpy(buffer, serializedQuote->getData(), serializedQuote->getSize());
            return serializedQuote->getSize();
        }

        return 0; // <- never want to stop
    }
};
```
I wrongly expected that the method above is called in a special thread (or task - it doesn't matter) which forms a chunk from the buffer, sends the chunk and calls "read" again until it returns 0. Well.. I was wrong.. 
Leonid could you help me to find out what is the correct way to resolve my issue? 
Thank you )

**Comment by lganzzzo** [comment]
Hello @lenikur ,

Your code looks good.
And yes, each connection is handled in a separate thread. 

What's seems to be wrong here is Postman. 
I assume it just won't show the result until the stream is completed.

Please do not use postman, use `Curl`!!! :)

**Comment by lenikur** [comment]
Thanks a lot!
It really works :)
