### ISSUE TITLE
Build different configurations

### ISSUE THREAD

**Issue by lenikur** [oatpp/oatpp#447]
Hi Leonid,

Could you please explain how to build oatpp for Windows?
I have read this [instruction](https://oatpp.io/docs/installation/windows/), but I cannot find the way how to apply variables from "Installation CMake options" table. In particular, I'd like to disable build test.
Also, I don't need installation, just wanna build libs in different configurations. Is it possible to skip this step?
I'm using the following approach now:
```
mkdir build.x64
cd build.x64
cmake .. -A x64 -T v142 -DCMAKE_CXX_STANDARD=17
cmake --build . --target INSTALL --config Debug
cmake --build . --target INSTALL --config Release
```
But it doesn't allow me to disable build tests. Could you also approve, that this approach is acceptable?

Thank you,
Nikita

**Comment by bamkrs** [comment]
Hey Nikita,

while oatpp-test (the testing-framework) is an non-deactivateable featureset of Oat++, you can still opt out of building the tests with `-DOATPP_BUILD_TESTS=OFF` when generating the build-config.

Further, if you only want to build oatpp.lib all you need to do is change the target appropriately:

```
mkdir build.x64
cd build.x64
cmake .. -A x64 -T v142 -DCMAKE_CXX_STANDARD=17 -DOATPP_BUILD_TESTS=OFF
cmake --build . --target oatpp --config Debug
cmake --build . --target oatpp --config Release
```

**Comment by lenikur** [comment]
Got it. Thank you!
Will check it tomorrow. 
By the way, do you know if someone has already built a NuGet package for OatPP?
