### ISSUE TITLE
ask for help: multiclients for a long time consume  service

### ISSUE THREAD

**Issue by hhuxianghao** [oatpp/oatpp#451]
Hi all, I'm newer for oatpp, I want to use it to create a time consume caculation service,. I have learned some samples, and create a simple caculation service. when one client connects to service, it works well, but if more clients connect, they must excute one by one.  on client excutes when another finished. How can I create a service that lost of clients can excute simultaneously. Thanks a lot.

**Comment by lganzzzo** [comment]
Hey @hhuxianghao ,

Thanks for the question.

> How can I create a service that lost of clients can excute simultaneously. Thanks a lot.

What is the approximate expected number of clients?

In most cases you can get away with the simple API, and you don't have to do anything special since oatpp allocates a separate thread for each client. Thus all clients are served simultaneously.

**Comment by hhuxianghao** [comment]
Hey @lganzzzo ,
Thanks for reply. Perhaps I have do something wrong, my clients  can't excute simultaneously, I don't known how to solve it. Can you give me some suggestion? The attachment is the main code for server and client, but it can't run because lake of real caculation process.  when the server run, I start two client, they run one by one in queue， can't connect the server simultaneously.
[server & client.zip](https://github.com/oatpp/oatpp/files/6920156/server.client.zip)

**Comment by lganzzzo** [comment]
Hello @hhuxianghao ,

Please don't post the whole project - post short blocks of issue-related code instead.

> The "RunModel" function in server is a time consume function, so the first client is blocked here, the other client even can't excute "client->CreateModel" function

The `RunModel` and `CreateModel` functions in your code are guarded with `std::lock_guard<oatpp::concurrency::SpinLock> lock(m_lock);` - no surprise they won't execute in parallel.

Apart from that,- it's not a good idea to guard time-consuming operations with `SpinLock`, it's better to use a regular `std::mutex` for that.

**Comment by hhuxianghao** [comment]
@lganzzzo,
 Thank you very much, I will try right away. Your suggestion is very important to me.
