### ISSUE TITLE
[Question] Create a dynamic key / value DTO

### ISSUE THREAD

**Issue by CapitaineJSparrow** [oatpp/oatpp#452]
Hello,

I apologize in advance if the question has already been answered. I looked at [DTO doc on oatpp.io](https://oatpp.io/docs/components/dto/) and [DTO examples](https://github.com/oatpp/oatpp-consul/blob/master/src/oatpp-consul/rest/DTOs.hpp) but cannot find a solution

## The need

Create a JSON similar to that :

```
{
  "key1": 10,
  "key2": 42,
  ... 
}
```

You don't know the keys in advance, nor their count.

## Use case

List files in directory and returns key/value json with key as filename and value as length in bytes

## What I tried

I guess I can create a `DTO_FIELD(Fields<Int32>, keyName);` but what if I want key/value pairs at root and not in subfield ?

Regards

**Comment by lganzzzo** [comment]
Hello @CapitaineJSparrow ,

The `createDtoResponse()` accepts all mapping-enabled types, not only DTO:

```cpp
  ENDPOINT("GET", "files", getFiles) {
    oatpp::Fields<oatpp::UInt64> dirs = {
      {"img1.png", 343100},
      {"img2.png", 1234343}
    };
    return createDtoResponse(Status::CODE_200, dirs);
  }
```

Output:

```json
{
  "img1.png": 343100,
  "img2.png": 1234343
}
```

**Comment by CapitaineJSparrow** [comment]
As always @lganzzzo thanks for your response or your time. I don't know if I should close the issue is someone is looking for something similar so I let you manage 💪
