### ISSUE TITLE
Transactions always "succeed", even with failing queries

### ISSUE THREAD

**Issue by breboulet** [oatpp/oatpp#459]
In file: oatpp/orm/DbClient.hpp

# Question

When using the transaction model as described in the documentation (with oatpp v1.2.5 + sqlite db):
```cpp
  auto transaction = client.beginTransaction();
  
  client.insertUser(user1, transaction.getConnection()); // failing query
  client.insertUser(user2, transaction.getConnection()); // successful query

  auto dbResult = transaction.commit();
  // dbResult->isSuccess() == true,  when it should be false
```
The first query (intentionally) fails, second query succeeds, once this is done, I'm getting "success" for the whole transaction. Nothing is rolled back, and we're left with a partial insert with no way of knowing something went wrong (the sqlite file includes the successful query data).

Even when there's a single failing query, I'm noticing the same behavior (dbResult->isSuccess() == true instead of false, when done via transaction.commit()).

Everything works as expected when using independent query statements (isSuccess == false on bad queries).

Are you able to reproduce the issue? Or maybe I'm not using the API as it should be?

Kinds Regards,
Bastien

**Comment by lganzzzo** [comment]
Hello @breboulet ,

It looks that SQLite won't automatically roll back failed inserts inside the transaction.

You can test it running the following SQL:

```sql
BEGIN;

INSERT INTO AppUser
(username, email, password, role) VALUES ('test-user-2', 'test-user-2@domain.com', 'admin', 'ROLE_ADMIN');

INSERT INTO AppUser
(username, email, password, role) VALUES ('test-user-2', 'test-user-2@domain.com', 'admin', 'ROLE_ADMIN');

COMMIT;
```

Assuming that `username` and `email` are `UNIQUE` fields (see DDL in [example-crud project](https://github.com/oatpp/example-crud/blob/master/sql/001_init.sql)).
After running the whole block you will find that `test-user-2` was successfully inserted even though the second insert in the transaction failed.


So you have to manually roll back in case of the failed insert:

```cpp

std::shared_ptr<oatpp::orm::QueryResult> testTransaction() {

  auto transaction = client.beginTransaction();
    
  {
    auto res = client.insertUser(user1, transaction.getConnection());
    if(!res-> isSuccess()) return res;
  }
  
  {
    auto res = client.insertUser(user1, transaction.getConnection());
    if(!res-> isSuccess()) return res;
  }
  
  return transaction.commit();

}
```

---

Call to `transaction.commit();` returns just status for the `COMMIT` operation.

**Comment by breboulet** [comment]
Oh I see, that's a nice way to deal with it! IIUC: given we never reach the commit() in case of error, transaction's destructor would auto-rollback for us, cool.
Hopefully the behavior would be consistent if we swapped the DB for postgres...
In any event, thank you so much for your help!

**Comment by breboulet** [comment]
I just noticed a related issue, here's how to reproduce:
```cpp
auto transaction = client.beginTransaction();
auto res = client.insertUser(user1, transaction.getConnection()); // failing (intentionally)
// res->isSuccess() == false && res->getErrorMessage()->c_str() == "Unique constraint failed blah blah"
transaction.rollback();
// res->isSuccess() == false && res->getErrorMessage()->c_str() == "not an error"
```
It looks like "getErrorMessage()" string is reset somehow after the rollback, even though it's NOT the result of the rollback query, but the initial db result.

**Comment by lganzzzo** [comment]
Hey @breboulet ,

Thanks for pointing this out. It's because [getErrorMessage()](https://github.com/oatpp/oatpp-sqlite/blob/master/src/oatpp-sqlite/QueryResult.cpp#L54) returns the last error on connection.

I guess we have to read and save the error message right away once DB responded.

**Comment by lganzzzo** [comment]
Fixed here - https://github.com/oatpp/oatpp-sqlite/pull/12
@breboulet  please verify

**Comment by breboulet** [comment]
Works beautifully! Thank you so much :)
