### ISSUE TITLE
Pg query issue with oatpp::String parameter

### ISSUE THREAD

**Issue by keithglassford** [oatpp/oatpp#467]
Hi and thanks for a great framework!!

I am having a bit of difficulty with a test I am running using the PostgreSQL extension … my dbClient query is as follows:

```
QUERY(test, "SELECT symbol FROM test WHERE date > DATE(:start_date) - INTEGER :period;",
         PREPARE(true),
         PARAM(oatpp::String, start_date),
         PARAM(oatpp::String, period)   
)
```

where the controller endpoint is:
```
ENDPOINT("GET", "test/startDate/{start_date}/period/{period}",
             test,
             PATH(String, start_date),
             PATH(String, period) )
{
      auto test = m_analyticsService.test(start_date, period);
      return createDtoResponse(Status::CODE_200, test);
}
```
and corresponding service:
```
oatpp::Vector<oatpp::Object<SymbolDto>>
AnalyticsService::test(const oatpp::String &start_date, const oatpp::Int8 &period)
{
   auto dbResult = m_database->test(start_date, period);
   OATPP_ASSERT_HTTP(dbResult->isSuccess(), Status::CODE_500, dbResult->getErrorMessage());
   OATPP_ASSERT_HTTP(dbResult->hasMoreToFetch(), Status::CODE_404, "Symbol not found");
   auto result = dbResult->fetch<oatpp::Vector<oatpp::Object<SymbolDto>>>();
   return result;
}
```
The above results in the following endpoint error:

message: "ERROR: syntax error at or near "$2" LINE 1: SELECT symbol FROM test WHERE date > DATE($1) - INTEGER $2; ^ "

I was expecting the period parameter to be converted to a string but is getting mangled somehow.  If I run this query in PostgreSQL directly: 
```
SELECT symbol, date FROM test WHERE date > DATE('2021-06-1') - INTEGER '7';
```
it works as expected. I tried putting ' around the period parameter, but it results in ':period' instead of '$2' as Oat++ is already taking care of the type translations. Also, If I manually add the period value in quotes as follows:
```
"SELECT symbol FROM test WHERE date > DATE(:start_date) - INTEGER '7';",
```
it works as expected. Any help would be greatly appreciated as I must be overlooking something simple!

Thanks -- Keith

**Comment by lganzzzo** [comment]
Hello @keithglassford ,

Thanks for the issue.

I have a reproduce and it looks like PostgreSQL for some reason doesn't allow a string parameter at the place of `period`
`INTEGER $2` ($2 can't be a string param).

I have fixed that by directly providing period as an integer value:

```cpp
  QUERY(test,
        "SELECT symbol FROM test WHERE date > DATE(:start_date) - :period;",
        PREPARE(true),
        PARAM(oatpp::String, start_date),
        PARAM(oatpp::Int32, period)) //<--- integer period
```

And your endpoint will look like this:

```cpp
  ENDPOINT("GET", "test/startDate/{start_date}/period/{period}",
           test,
           PATH(String, start_date),
           PATH(Int32, period)) //<--- integer period
```

You can pass the period directly from the endpoint to QUERY.

Regards,
Leonid

**Comment by keithglassford** [comment]
Hi Leonid,

Thanks so much for getting back so quickly! I have implemented your solution and it works perfectly ... thanks so much for your assistance and for a great framework!!!

Best wishes,
Keith
