### ISSUE TITLE
How to upload and access a file.

### ISSUE THREAD

**Issue by cgrantcal** [oatpp/oatpp#47]
Hey, 

Do you have an example of how to add a file upload as part of the endpoint?

Thanks

Conor

**Comment by lganzzzo** [comment]
Hey,

```cpp

  ENDPOINT_INFO(postFile) {
    info->summary = "Upload file";
    info->addConsumes<oatpp::swagger::Binary>("application/octet-stream");
  }
  ENDPOINT("POST", "/file", postFile,
           BODY_STRING(String, body)) {

     // body contains the file
     // use for ex. body.saveToFile("my_file.png");
    
      return createResponse(Status::CODE_200, "OK");
    }
    
  }

```

Regards,
Leonid

**Comment by cgrantcal** [comment]
Hey, 

Thanks for that ! 

Could you point me to where Binary is defined:

```error: ‘Binary’ is not a member of ‘oatpp::swagger’```

Thanks

Conor

**Comment by lganzzzo** [comment]
Sure,

`#include "oatpp-swagger/Types.hpp"`

Regards,
Leonid

**Comment by cgrantcal** [comment]
Hey, 

Got that working now thank you !

Regards

Conor

**Comment by lganzzzo** [comment]
You are welcome!
Please let me know in case you have more questions.

Best Regards,
Leonid

**Comment by zero-awei** [comment]
How can I carry the Body_DTO parameter while uploading the file?
