### ISSUE TITLE
Memory usage

### ISSUE THREAD

**Issue by cgrantcal** [oatpp/oatpp#48]
Hey, 

I am running some tests and i notice that with more requests more memory is allocated as is expected. However i see that this memory is never de-allocated. 

My question is that is there was a way for this memory to be de-allocated once the requests have been serviced and queuing reduced. I appreciate that this would not be the best for optimal performance. The host this is running on has limited resources, having a way to limit memory usage during low traffic periods would be helpful.

Any ideas you think could help are appreciated. 

Regards

Conor

**Comment by cgrantcal** [comment]
Note :
I have tested adding -D OATPP_DISABLE_POOL_ALLOCATIONS.
```
 * Define this to disable memory-pool allocations.
 * This will make oatpp::base::memory::MemoryPool, method obtain and free call new and delete directly
```
I see no change to the memory  behaviour

Thanks

Conor

**Comment by lganzzzo** [comment]
Hello @cgrantcal, 

`OATPP_DISABLE_POOL_ALLOCATIONS` is the right guess.

Note that you have to rebuild `oatpp` module `liboatpp` in order for this to work.

Please let me know how is your progress.

Regards,
Leonid

**Comment by lganzzzo** [comment]
@cgrantcal 
Update.

I've added a fix for disabling pool allocations. See https://github.com/oatpp/oatpp/pull/49.
Also I made it possible to configure oatpp compiler options from cmake.

So to build oatpp with `OATPP_DISABLE_POOL_ALLOCATIONS`:
*(from oatpp dir)*
```bash
$ cd build/
$ cmake -DOATPP_DISABLE_POOL_ALLOCATIONS=ON ..
$ make
$ make install
```
So now it should deallocate more memory once load is dropped and connections are closed.

Please let me know if you have more questions.

Best Regards,
Leonid

**Comment by cgrantcal** [comment]
Hey, 

I can see that with that flag enabled:

```
############################################################################
## oatpp module compilation config:

OATPP_DISABLE_ENV_OBJECT_COUNTERS=OFF
OATPP_DISABLE_POOL_ALLOCATIONS=ON
OATPP_THREAD_HARDWARE_CONCURRENCY=AUTO
OATPP_THREAD_DISTRIBUTED_MEM_POOL_SHARDS_COUNT=10
OATPP_ASYNC_EXECUTOR_THREAD_NUM_DEFAULT=2
```

I can still see that the memory usage never decreases 
![memory](https://user-images.githubusercontent.com/48085845/53799858-4f6df900-3f33-11e9-8f25-001e936224d2.png)

In your tests how long does it take before the memory is de allocated?

Thanks

Conor

**Comment by lganzzzo** [comment]
Hey @cgrantcal ,

Looks like not all pools are disabled. I think it might be a bug.

Can you please specify what load you are running against your service:
- type of request
- concurrency level
- requests per second

Thanks,
Leonid

**Comment by cgrantcal** [comment]
Hey, 

I am making simple post and get requests.
There are about 5 clients hooked up. making about 100 requests a second each for 10 seconds. 

Hope that helps.

Thanks

Conor

**Comment by lganzzzo** [comment]
Hey @cgrantcal ,

I've conducted some tests and results are as follows:

Currently the best results in terms of memory you are able to get with oatpp being built as:

```
cmake -DOATPP_DISABLE_POOL_ALLOCATIONS=ON -DOATPP_THREAD_DISTRIBUTED_MEM_POOL_SHARDS_COUNT=1 -DCMAKE_BUILD_TYPE=Release ..
```

In this setup I get:
- 352 KB on service start.
- 13.2 MB during the load `wrk -t1 -c500 -d10s "http://127.0.0.1:8000/"`
- 5.4 MB when load is dropped

Also memory consumption will grow a bit as the load repeated till some point (due to memory fragmentation). 

I'll try to make some memory optimization in future, but for now it is what it is

Best Regards,
Leonid
