### ISSUE TITLE
Issue cross-compiling for rpi/synology

### ISSUE THREAD

**Issue by sgallou** [oatpp/oatpp#480]
Hi,

I experienced an issue trying to cross-compile from Windows for Raspberry or Synology (with GCC).
I found the problem and provided [this pull request](https://github.com/oatpp/oatpp/pull/479), but checks failed because build timeout. They probably just need to be restarted, but I'm not able to do that.

Can you restart the checks job ? Or maybe I need to do another commit (by adding a space somewhere) ?

Thanks

**Comment by lganzzzo** [comment]
Hey @sgallou ,

Build restarted.
Also, I think it's possible to restart pipelines by just writing the comment:

```cpp
/AzurePipelines run
```

or

```cpp
/azp run
```
