### ISSUE TITLE
Overriding default Content-Type header results in duplicate values

### ISSUE THREAD

**Issue by DaftMountain** [oatpp/oatpp#481]
I would like to override the default Content-Type header in the response.
I added putHeader, but the response has an extra "application/json". 

```
auto dto = TestDto::createShared(); 
dto->msg = "Hello World!";
auto response = createDtoResponse(Status::CODE_200, dto);
response->putHeader(Header::CONTENT_TYPE, "application/json;version=2");
return response;
```

Actual Response:
`content-type: application/json;version=2,application/json`

Expected Response:
`content-type: application/json;version=2`

**Comment by bamkrs** [comment]
Hey @DaftMountain sorry for the late reply.
This is a very nice feature, I agree. We try to implement it asap
