### ISSUE TITLE
Feature Request: Add operator*() to ObjectWrapper

### ISSUE THREAD

**Issue by ipizhenko** [oatpp/oatpp#487]
A bit of "syntactic sugar". Instead of writing `*wrapper->get()` it will make possible to write just `*wrapper`.

**Comment by lganzzzo** [comment]
We can't add `operator *` on the base-most `ObjectWrapper` class, since we have a derived `oatpp::Void`.
However, `operator *` is present for `oatpp::String` and all other primitives.
