### ISSUE TITLE
DTO subclassing limit

### ISSUE THREAD

**Issue by IvanRibakov** [oatpp/oatpp#506]
is there some sort of limit to how many subclassing levels a DTO can have?

I have a following setup at the moment:

- `Model : public DTO`
- `ModelA : public Model`
- `ModelB : public ModelA`

`Model` has `DTO_FIELD(String, id);`. `ModelA` and `ModelB` have their own respective fields. I'm expecting `ModelB` to be a combination of all the fields in `Model`, `ModelA` and `ModelB`.

When I create instance of `ModelB`, set the `id` field and serialise it with ObjectMapper, resulting JSON does not include the `id` field:

```
auto objectMapper = oatpp::parser::json::mapping::ObjectMapper::createShared();
auto dto = ModelB::createShared();
dto->id = "testId"; // defined in Model
dto->description = "testDescription"; // defined in ModelA
dto->type = "testType"; // defined in ModelB
const oatpp::String &json = objectMapper->writeToString(dto);
return json->c_str();

// returns  {"description":"testDescription","type":"testType"}
```

If I instead create instance of `ModelA`, then resulting JSON includes the `id` field:
```
auto objectMapper = oatpp::parser::json::mapping::ObjectMapper::createShared();
auto dto = ModelA::createShared();
dto->id = "testId"; // defined in Model
dto->description = "testDescription"; // defined in ModelA
// dto->type = "testType"; // defined in ModelB
const oatpp::String &json = objectMapper->writeToString(dto);
return json->c_str();

// returns  {"id":"testId","description":"testDescription"}
```

Is that an expected behaviour? In the [`DTO_INIT` documentation page](https://oatpp.io/api/latest/oatpp/codegen/dto/base_define/#dto-init) I see no mention of any sort of subclassing limitations. In this https://github.com/oatpp/oatpp/issues/256#issuecomment-640216611 here you say
> you have only one DTO fields inheritance vertical

but again, no mention of the limited depth of that inheritance vertical.

**Comment by lganzzzo** [comment]
Hello @IvanRibakov ,

There is no limit on the depth of inheritance.

Make sure to properly define the DTO:

```cpp

class Model : public oatpp::DTO {

  DTO_INIT(Model, DTO /*<extends> */)  <--- make sure you explicitly define the super-class here

};

class ModelA : public Model {

  DTO_INIT(ModelA, Model /*<extends> */)  <--- now it extends Model

}

...

```

**Comment by IvanRibakov** [comment]
@lganzzzo I believe I've been already defining DTOs in the way that you prescribed.

Here's a minimal working example:

```
#include OATPP_CODEGEN_BEGIN(DTO)
class Model : public oatpp::DTO {
    DTO_INIT(Model, DTO)
    DTO_FIELD(String, id);
};

class ModelA : public Model {
    DTO_INIT(ModelA, Model)
    DTO_FIELD(String, description);
};

class ModelB : public ModelA {
    DTO_INIT(ModelB, ModelA)
    DTO_FIELD(String, type);
};
#include OATPP_CODEGEN_END(DTO)

SCENARIO("Oatpp DTO inheritance test") {
    GIVEN("DTO instance") {
        auto objectMapper = oatpp::parser::json::mapping::ObjectMapper::createShared();
        auto dto = ModelB::createShared();
        dto->id = "testId";
        dto->description = "testDescription";
        dto->type = "testType"; 
        WHEN("Serialising it") {
            std::string jsonStr = objectMapper->writeToString(dto)->c_str();
            THEN("All fields are present in JSON") {
                CHECK(R"({"id":"testId","description":"testDescription","type":"testType"})" == jsonStr);
            }
        }
    }
}
```

Above unit-test fails with following message:

```
oatpp_test.cpp:51: FAILED:
  CHECK( R"({"id":"testId","description":"testDescription","type":"testType"})" == jsonStr )
with expansion:
  "{"id":"testId","description":"testDescription","type":"testType"}"
  ==
  "{"description":"testDescription","type":"testType"}"

===============================================================================
test cases: 1 | 1 failed
assertions: 1 | 1 failed

```

**Comment by lganzzzo** [comment]
Hey @IvanRibakov ,

Thanks for pointing this out!

Fixed in - https://github.com/oatpp/oatpp/commit/40e33f6bae947cf97b8050d93684d0bdd9976459

Regards,
Leonid
