### ISSUE TITLE
How to return a std::vector data back to caller?

### ISSUE THREAD

**Issue by relaxtheo** [oatpp/oatpp#513]
I have set a DTO like:
DTO_FIELD(Vector, MatrixData, "MatrixData");

In application, how can I set a std::vector value to the MatrixData? The example seems uses orm, but I have no database and I think there should be some way to use C++ data straightly.

**Comment by lganzzzo** [comment]
Hello @relaxtheo ,

This page should help you - https://oatpp.io/docs/components/dto/

If your `MatrixData` is DTO then it should be

```cpp
DTO_FIELD(Vector<Object<MatrixData>>, matrixData);
```

**Comment by relaxtheo** [comment]
Sorry for my faults, my DTO definition is:

DTO_FIELD(Vector<Float32>, MatrixData, "MatrixData");

I hope the MatrixData is a vector of Float32 in oat++, and the original data is a array of float in C++, and I can convert it to std::vector, and I tried to set the std::vector variable back to MatrixData. 

However, in compiling, I always get errors like:
no match for ‘operator=’ (operand types are ‘oatpp::data::mapping::type::DTO::Vector<oatpp::data::mapping::type::Primitive<float, oatpp::data::mapping::type::__class::Float32> > {aka oatpp::data::mapping::type::VectorObjectWrapper<oatpp::data::mapping::type::Primitive<float, oatpp::data::mapping::type::__class::Float32>, oatpp::data::mapping::type::__class::Vector<oatpp::data::mapping::type::Primitive<float, oatpp::data::mapping::type::__class::Float32> > >}’ and ‘std::__cxx11::list<float>’)

So, how can I transfer my std::vector data back to the callers by DTO?

**Comment by lganzzzo** [comment]
Hello @relaxtheo ,

If you have `oatpp::Vector<oatpp::Float32>` and `std::vector<float>` then as for Oat++ `1.3.0` you have to manually fill in elements in `oatpp::Vector<oatpp::Float32>`

```cpp
auto tempMatrix = TempMatrixDto::createShared();
tempMatrix->MatrixData = {}; // init empty vector. Otherwise it will be null

std::vector<float> values({1.0, 2.0, 3.0});

for(auto& v : values) {
  tempMatrix->MatrixData->push_back(v);
}
```

You have to do a similar operation to convert back from `oatpp::Vector<oatpp::Float32>` to `std::vector<float>`

**Comment by relaxtheo** [comment]
OK, got it, thank you!

**Comment by relaxtheo** [comment]
It's fine now, thank you for your support!

It is not very efficient for large scale data.

Is there some better solution to return a big data chunk from webservice to caller?

**Comment by lganzzzo** [comment]
Another solution would be to create your custom type and add your serializer/deserializer method to
Serializer/Deserializer for that type - https://github.com/oatpp/oatpp/blob/master/src/oatpp/parser/json/mapping/Serializer.hpp#L183


```cpp
namespace __class {

  class MyType {
  public:
    static const ClassId CLASS_ID;
  
    static Type* getType(){
      static Type type(CLASS_ID);
      return &type;
    }
  
  };

}

/* define your custom type */
typedef Primitive<std::vector<float>, __class::MyType> MyType;

... 

DTO_FIELD(MyType, matrixData);
```

**Comment by relaxtheo** [comment]
Thank you, I will try it
