### ISSUE TITLE
Segmentation fault when comparing field with `null`

### ISSUE THREAD

**Issue by league55** [oatpp/oatpp#518]
This strange issue popped up in the testing environment when we started to increase load - application crashes with segmentation fault, and backtrace leads to `oatpp` sources, in particular, to the place where we check that field is not null:
`Primitive.hpp`
```
  inline bool operator == (T) const {
    return m_ptr.get() == nullptr;
                   ^~~~~~ m_prt is null
```

Something is wrong in our code, because those fields must not be null, but what is bugging me, is that we get segm fault basically when comparing with `nullptr` to avoid this sort of problems.
Similar code that leads to crash:
```
std::string getId() const { return id == "" ? "" : id->c_str(); }
                                                        ^ ~~~~ calls operator and crashes
```

Primitive.hpp
```
  inline bool operator != (T) const {
    return m_ptr.get() != nullptr;
                  ^~~~~ no check here
  }
...
  inline bool operator == (const T* str) const {
    if(!m_ptr) return str == nullptr;
        ^~~~ checked here, so technically CAN be null?
    if(str == nullptr) return false;
    return *m_ptr == str;
  }
```
I would be thankful to know your opinion about:
1. Should there be null checks in Primitive.hpp in operators like `inline bool operator != (T) `?
2. Any idea how this could happen? So far, I can't reproduce it by manually creating DTOs and assigning nulls in unit tests. 

Thank you for your time.

**Comment by lganzzzo** [comment]
Hello @league55 ,

This doesn't look right. Those are totally valid `nullptr` checks.

```cpp
return m_ptr.get() == nullptr; // this is a totally valid nullptr check. 
                               // if m_ptr stores nullptr condition will return true.
                               // m_ptr itself can't be null
```

It looks more like some sort of memory corruption.

> Should there be null checks in Primitive.hpp in operators like inline bool operator != (T) ?

Those are valid null checks. You can get more info on this matter by getting acquainted with the `std::shared_ptr`

I would suggest starting from deleting all oatpp modules that are in use and reinstalling them from scratch (deleting also the CMake cache).

If the problem persists - check your program for mem-leaks/mem-corruption and concurrency issues.
At this moment this issue looks like you'll have a long debugging session :)

Best Regards,
Leonid

**Comment by league55** [comment]
Thank you for your reply. 
Yes, I agree with you on this. 

Just wanted to make sure that `m_ptr` can't be null, because in some cases there are such checks in `oatpp`, like, for example, in the `inline bool operator == (const T* str) const {` operator that I put as example in my first comment.

I think we can close this issue for now.
Best regards,
