### ISSUE TITLE
Repurpose web server

### ISSUE THREAD

**Issue by c-lgrant** [oatpp/oatpp#52]
Hey, 

Im wondering if it is possible to re-use the http webserver that is used for the swagger UI.

I can edit the index.html to load what i want but when i want it to run javascript it cant find the files correctly although they are located in the same directory. 

Thanks

Conor

**Comment by lganzzzo** [comment]
Hey @c-lgrant ,

When you integrate oatpp-swagger (swagger-ui) to oatpp application, you may add whatever functionality to you server. Swagger-UI goes as complementary functionality.

You may add multiple controllers to your server.
Each controller is responsible for some functionality to serve.

Example In App.cpp:
```cpp
  /* create ApiControllers and add endpoints to router */
  
  auto router = components.httpRouter.getObject(); 
  auto docEndpoints = oatpp::swagger::Controller::Endpoints::createShared(); // list of endpoints to document with swagger-ui
  
  auto userController = UserController::createShared(); // Controller with your custom functionality.
  userController->addEndpointsToRouter(router); // Add your controller to router.
  
  docEndpoints->pushBackAll(userController->getEndpoints()); // Add your controller's endpoints to documented endpoints list.
  
  auto swaggerController = oatpp::swagger::Controller::createShared(docEndpoints); // Create swagger-ui controller.
  swaggerController->addEndpointsToRouter(router); // Add swagger-ui controller to router.
```

## Serve Files.

For additional files you want to serve you have to define corresponding functionality.

### Add file serving endpoint

Rough example:

```cpp
oatpp::String loadFileOrGetFromCache(const oatpp::String& filepath) {
	// TODO load from cache or from file.
	// TODO load file ex.: return oatpp::base::StrBuffer::loadFromFile(filepath);
	// TODO return file bytes.
}

ENDPOINT("GET", "*", files, REQUEST(std::shared_ptr<IncomingRequest>, request)) {
    auto filePath = request->getPathTail();
    OATPP_ASSERT_HTTP(filePath, Status::CODE_400, "Empty filename");
    oatpp::String buffer = loadFileOrGetFromCache(filePath);
    return createResponse(Status::CODE_200, buffer);
}
```

**NOTE:** Endpoint with `"*"` mapping should be added as a bottom list endpoint. In order not to intercept other mappings.

Best Regards,
Leonid

**Comment by c-lgrant** [comment]
Hey, 

I added this as your mentioned. But for some reason it cannot load the associated scripts

for example the index.html is served correctly but when it references:

```
<script type="text/javascript" src="runtime.0f8b38d12916507d0f42.js"></script>
```
it doesnt load at all.

do you know what could be the cause of this?

Thanks

Conor

**Comment by c-lgrant** [comment]
Got this working perfectly thank you.

**Comment by lganzzzo** [comment]
You are welcome!

**Comment by XDinEuro** [comment]
@c-lgrant 

Hi, may I ask that how u manage to serve static files ?

I had a web pack built from Vuejs project, the content of index.html looks similar to yours.

But I have those errors when loading the page 

```
Uncaught SyntaxError: expected expression, got '<'
[chunk-vendors.80bc871e.js:1](http://localhost:8000/js/chunk-vendors.80bc871e.js)
Uncaught SyntaxError: expected expression, got '<'
[app.50011e50.js:1](http://localhost:8000/js/app.50011e50.js)
```

Could u provide some inforamtion if u know some insides ?
