### ISSUE TITLE
ResponseInterceptor HTTP and std exceptions are not passed as such

### ISSUE THREAD

**Issue by JeremyGuinn** [oatpp/oatpp#521]
If a RequestInterceptor has an HTTP or std exception thrown, it is directed to the ErrorHandler. However, such an exception thrown in ResponseInterceptors don't do this. I think it should have the same behavior to have HTTP and std exceptions to also be passed in the ErrorHandler.

It looks like here is where the request interceptors HTTP and std exception is passed along to the error handler:
https://github.com/oatpp/oatpp/blob/05405fff862cb838473f4cccfb03103b54030389/src/oatpp/web/server/HttpProcessor.cpp#L117-L126

And here is where it is not being passed along for response interceptors:
https://github.com/oatpp/oatpp/blob/05405fff862cb838473f4cccfb03103b54030389/src/oatpp/web/server/HttpProcessor.cpp#L171-L177

This change could most likely be lumped in with the change of providing the entire Error to the ErrorHandler, mentioned in this comment https://github.com/oatpp/oatpp/issues/277#issuecomment-660387536.

**Comment by lganzzzo** [comment]
@JeremyGuinn 
I agree the proposed behavior is more consistent.
