### ISSUE TITLE
Host header does not contain port

### ISSUE THREAD

**Issue by ArnaudGallardo** [oatpp/oatpp#525]
Currently the "Host" header added to any HTTP request only contains the `host` parameter and ignores the `port` parameter.

https://github.com/oatpp/oatpp/blob/4a40edc0c38feb04d9b3d73bde02ef91e5878fb2/src/oatpp/web/client/HttpRequestExecutor.cpp#L201

The [HTTP/1.1 specification](https://httpwg.org/specs/rfc7230.html#header.host) implies that if the port is not defined, the default HTTP or HTTPS port should be used.

I'm sending a request on a service running on port 8080 and it refuses my request as the Host header does not match.

Is this behavior wanted on your side for any reason or can I make a PR to fix this?

Thanks!

**Comment by lganzzzo** [comment]
Hey @ArnaudGallardo ,

Thanks for finding this. This is a bug for sure, so the PR with the fix is 💯  welcome.
