### ISSUE TITLE
About lock in oatpp 1.3.0

### ISSUE THREAD

**Issue by xingyun86** [oatpp/oatpp#530]
I use before latest version. 
Now newer version add too many lock. Please consider it.

**Comment by lganzzzo** [comment]
Hey @xingyun86 ,

Please give us more details.
About which locks and where are you concerned about?

**Comment by xingyun86** [comment]
> Hey @xingyun86 ,
> 
> Please give us more details. About which locks and where are you concerned about?

I compare version 1.3.0 with 1.2.5. In different files you can discover it。

**Comment by lganzzzo** [comment]
@xingyun86 ,

Locks/Mutexes in oatpp isn't a matter of preference. 
They serve their purpose and provide synchronization where it's necessary.

If you have any suggestions on how to implement some exact parts of oatpp without using Locks - contributions are very welcome.

**Comment by xingyun86** [comment]
> @xingyun86 ,
> 
> Locks/Mutexes in oatpp isn't a matter of preference. They serve their purpose and provide synchronization where it's necessary.
> 
> If you have any suggestions on how to implement some exact parts of oatpp without using Locks - contributions are very welcome.

I will design one library with no locks by myself.
