### ISSUE TITLE
Unexpected behavior when receiving `Connection: close` header

### ISSUE THREAD

**Issue by danielmartinezruiz** [oatpp/oatpp#531]
When we receive a request that contains a `Connection: close` header, the server doesn't answer a response. This is happening in our project, but I checked that it is also happening in the https://github.com/oatpp/example-crud.

To reproduce in the example, just build and run the docker. A normal request will work without problems:

```
$ curl -v -X POST http://localhost:8000/users
*   Trying ::1:8000...
* Connected to localhost (::1) port 8000 (#0)
> POST /users HTTP/1.1
> Host: localhost:8000
> User-Agent: curl/7.74.0
> Accept: */*
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 500 Internal Server Error
< Content-Length: 134
< Content-Type: application/json
< Connection: close
< Server: oatpp/1.3.0
< 
* Closing connection 0
{"status":"ERROR","code":500,"message":"[oatpp::web::protocol::http::incoming::SimpleBodyDecoder::decode()]: Error. Invalid Request."}
$
```

Sending the `Connection: close` header makes the server not responding and `curl` is waiting until Ctrl-C:

```
$ curl -v -X POST --header 'Connection: close' http://localhost:8000/users
*   Trying ::1:8000...
* Connected to localhost (::1) port 8000 (#0)
> POST /users HTTP/1.1
> Host: localhost:8000
> User-Agent: curl/7.74.0
> Accept: */*
> Connection: close
> 
^C
$
```

This is only when sending the `Connection: close` header. Sending the` Connection: keep-alive` header doesn't make it fail.

During researching in our project, I found that the call that stop the normal process is `oatpp::web::protocol::http::incoming::Request>::readBodyToString()`. It looks like the library is expecting to receive more data in the body, so I also checked that sending a `Content-Length: X` header makes it works:

```
$ curl -v -X POST --header 'Connection: close' --header 'Content-Length: 0' http://localhost:8000/users
*   Trying ::1:8000...
* Connected to localhost (::1) port 8000 (#0)
> POST /users HTTP/1.1
> Host: localhost:8000
> User-Agent: curl/7.74.0
> Accept: */*
> Connection: close
> Content-Length: 0
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 500 Internal Server Error
< Content-Length: 123
< Content-Type: application/json
< Connection: close
< Server: oatpp/1.3.0
< 
* Closing connection 0
{"status":"ERROR","code":500,"message":"[oatpp::parser::json::mapping::Deserializer::readObject()]: Error. '{' - expected"}
$
```

**Comment by lganzzzo** [comment]
Hello @danielmartinezruiz ,

As far as I remember this is expected behavior.
When a client sends request without `content-length` and without `transfer-encoding: chunked` headers (meaning there is no info on how a server should read the body) and with `connection: close` header - then
the server should read the body until there is an error (client closes write side of the connection)

In your example you are sending a request to an endpoint that expects a body to be present - so for me, everything looks correct at the moment.

**Comment by danielmartinezruiz** [comment]
Hi, Iganzzzo. Thanks for the quick response.

I started yesterday to research deeper in your answer, and I found some references in the RFC7230.
- [Section 6.3](https://datatracker.ietf.org/doc/html/rfc7230#section-6.3) indicates that the messages must be fully read before closing the connections that are not to be persisted.
- [Section 3.3](https://datatracker.ietf.org/doc/html/rfc7230#section-3.3) indicates that message bodies must be signaled by a Content-Length or Transfer-Encoding header. Transfer-Encoding is part of HTTP/1.1, so it is preferred the use of Content-Length for signaling.

So I understand this is the reason it is mandatory to indicate the size of the message body if the Connection: close header is present, preferably with the Content-Length header. It is pretty strange, mainly when a GET is sent and, even it can have a body, it used to be empty.

Thanks again for your time. I'm going to close this issue.

**Comment by Alberto-Izquierdo** [comment]
Sorry to bother you @lganzzzo, I have noticed that this behavior also happens with requests to endpoints that do not expect a body, is this intended? Should some manual checks be done before calling `readBodyToString()`?

Thank you in advance.
