### ISSUE TITLE
Does oatpp support big-endian architecture

### ISSUE THREAD

**Issue by doufu3344** [oatpp/oatpp#537]
I want to build and use oatpp on the **IBM Power System S822** CPU(Big Endian), the installed operating system is **AIX 7.2**. Does it support it?

**Comment by lganzzzo** [comment]
Hello @doufu3344 ,

Oat++ works fine on Big Endian CPUs.
I'm not familiar with **AIX 7.2** and don't know what possible issues may be there, but definitely, Big Endianness isn't an issue.

**Comment by doufu3344** [comment]
Thanks, I will have a try.

**Comment by doufu3344** [comment]
Update: I have successfully build _oatpp/oatpp-ws/oatpp-openssl_(1.2.5) on the AIX system and my service works fine as of now.

It should be noted that due to [a feature of GCC on AIX](https://gcc.gnu.org/onlinedocs/cpp/System-Headers.html#System-Headers): 
> On some targets, such as RS/6000 AIX, GCC implicitly surrounds all system headers with an ‘extern "C"’ block when compiling as C++.

_**-DCMAKE_NO_SYSTEM_FROM_IMPORTED=ON**_ option is added to _cmake_ according to [this question on stackoverflow](https://stackoverflow.com/questions/54820379/needed-clarity-on-cmake-no-system-from-imported-property). 

_**-DDCMAKE_CXX_FLAGS="-pthread"**_  is also added, otherwise you may compile failed when thread in C++11 is used such as _std::thread_ and _std::mutex_. 

---

The compiler used is _c++8_, all compilation tools used are installed online from [IBM Aix Toolbox](https://www.ibm.com/support/pages/aix-toolbox-open-source-software-downloads-alpha) by _dnf_.
```
# /opt/freeware/bin/c++ -v
Using built-in specs.
COLLECT_GCC=/opt/freeware/bin/c++
COLLECT_LTO_WRAPPER=/opt/freeware/libexec/gcc/powerpc-ibm-aix7.2.0.0/8/lto-wrapper
Target: powerpc-ibm-aix7.2.0.0
Configured with: ../gcc-8.3.0/configure --prefix=/opt/freeware --mandir=/opt/freeware/man --infodir=/opt/freeware/info --with-local-prefix=/opt/freeware --with-as=/usr/bin/as --with-ld=/usr/bin/ld --enable-languages=c,c++,fortran,go --enable-version-specific-runtime-libs --disable-nls --enable-decimal-float=dpd --disable-libstdcxx-pch --enable-__cxa_atexit --disable-werror --enable-libstdcxx-filesystem-ts --with-gcc-major-version-only --program-suffix=-8 --disable-rpath --host=powerpc-ibm-aix7.2.0.0
Thread model: aix
gcc version 8.3.0 (GCC)
```
The following is some configuration of my server: 
```
# oslevel -s
7200-02-03-1845
# prtconf
System Model: IBM,9009-22G
Machine Serial Number: *******
Processor Type: PowerPC_POWER9
Processor Implementation Mode: POWER 9
Processor Version: PV_9_Compat
Number Of Processors: 8
Processor Clock Speed: 3000 MHz
CPU Type: 64-bit
Kernel Type: 64-bit
LPAR Info: 1 78-D9960
Memory Size: 124160 MB
Good Memory Size: 124160 MB
Platform Firmware level: IL950_075
Firmware Version: IBM,FW950.11 (IL950_075)
Console Login: enable
Auto Restart: true
Full Core: false
NX Crypto Acceleration: Capable and Enabled
...
...
```
