### ISSUE TITLE
Hook point to handle custom exceptions

### ISSUE THREAD

**Issue by ZizhengTai** [oatpp/oatpp#552]
Can we add a hook point in `ApiController` to customize the behavior of the controller when there is an exception? Specifically, currently when a generic `std::exception` is thrown, the default implementation seems to just return a 500 response with `ex.what()` as the message. This is undesirable in production environment as we don't want the exception details to be visible to the end user.

I also noticed that `ApiController::handleError` is not recommended to be used yet. How about adding a customization point that looks something like this:
```cpp
class ApiController {
protected:
    // Called by endpoint when an exception is thrown during request handling
    virtual std::shared_ptr<OutgoingResponse> handleError(std::exception_ptr eptr)
    {
        // Default implementation that can be overwritten by child classes
        try {
            std::rethrow_exception(etpr);
        } catch (const oatpp::web::protocol::http::HttpError& error) {
            return m_errorHandler->handleError(error.getInfo().status, error.getMessage(), error.getHeaders());
        } catch (...) {
            return m_errorHandler->handleError(protocol::http::Status::CODE_500, "Unknown error");
        }
    }
};
```
And in a concrete controller:
```cpp
class MyController : public ApiController {
protected:
    std::shared_ptr<OutgoingResponse> handleError(std::exception_ptr eptr) override
    {
        try {
            std::rethrow_exception(etpr);
        } catch (const MyDomainException& ex) {
            return m_errorHandler->handleError(Status::CODE_500, "My domain error message");
        } catch (...) {
            // For errors we don't care, fall back to the default implementation
            return ApiController::handleError(std::current_exception());
        }
    }
};
```

**Comment by lganzzzo** [comment]
Hello @ZizhengTai ,

At the moment Controller-level error handling isn't recommended to use because we are planning to change it (and it doesn't work the way it should)

What you can do - is to use global (ConnectionHandler - level) error handler to customize errors. You can find an example in the `example-crud` project here - https://github.com/oatpp/example-crud/blob/master/src/AppComponent.hpp#L67

For more information on how we are planning to improve controller-level error handling see - 
https://github.com/oatpp/oatpp/issues/277

**Comment by lganzzzo** [comment]
> I guess as a workaround I'll have to just change the error message inside the error handler when the status code is Status::CODE_500...?

Yes, as of now, this workaround will be the easiest thing to do
