### ISSUE TITLE
API question

### ISSUE THREAD

**Issue by wangcancan1900** [oatpp/oatpp#553]
In file: oatpp/web/mime/multipart/FileProvider.hpp

# Question

How do I parse the files in the request

**Comment by lganzzzo** [comment]
Hello @wangcancan1900 ,

You can find example here - https://github.com/oatpp/oatpp/blob/master/changelog/1.3.0.md#better-multipart

**Comment by wangcancan1900** [comment]
Hello @lganzzzo 
Thank you for reply,Solve problems by giving links
