### ISSUE TITLE
PairList.hpp:136:5: warning: operation on ‘info.oatpp::data::mapping::type::Type::Info::polymorphicDispatcher’ may be undefined [-Wsequence-point]

### ISSUE THREAD

**Issue by yikenan** [oatpp/oatpp#554]
/oatpp/core/data/mapping/type/./PairList.hpp:136 
the code is shown below，is there any special purpose of writing like this ?

    info.polymorphicDispatcher = info.polymorphicDispatcher =
      new typename __class::StandardMap<std::list<std::pair<Key, Value>>, Key, Value, PairList>::PolymorphicDispatcher();

my compiler is gcc version 9.3.0

Thanks!

**Comment by lganzzzo** [comment]
Hello @yikenan ,

Please clarify, what is exactly your question :)?
Or do you have any suggestions on how to improve this code?

Regards,
Leonid

**Comment by yikenan** [comment]
Thanks for your reply.

Whenever I compile my project, I will receive a large number of compiler warnings, as follows:

PairList.hpp:136:5: warning: operation on ‘info.oatpp::data::mapping::type::Type::Info::polymorphicDispatcher’ may be undefined [-Wsequence-point] 

Then I checked the code as follows. I don't quite understand it. Did you accidentally write **two "info. Polymorphicdispatcher ="**, or have any other special purpose?

info.polymorphicDispatcher = info.polymorphicDispatcher =
  new typename __class::StandardMap<std::list<std::pair<Key, Value>>, Key, Value, PairList>::PolymorphicDispatcher();

Best regards！

**Comment by lganzzzo** [comment]
Hey @yikenan ,

It is definitely a typo!
I didn't even notice there were two assignments `info.polymorphicDispatcher = info.polymorphicDispatcher =`

Please feel free to create a PR removing that.
I appreciate the code review!

Regards,
Leonid
