### ISSUE TITLE
Compile error when using QUERY like in documentaion described

### ISSUE THREAD

**Issue by bitgenerator** [oatpp/oatpp#556]
Hi,

I'm following the documentation and got an error during compilation following example: 
https://oatpp.io/docs/components/api-controller/#query-parameters-mapping 

Visual Studio 2017 is complaining about 
**error C2839: invalid return type 'type' for overloaded 'operator ->' 
error C2232:  '->' : left operand has 'class-key' type, use '.'**
when I try to use age like mentioned in the example.
What's wrong with the usage/example?

Thanks and Best
Mario

**Comment by lganzzzo** [comment]
Hello @bitgenerator ,

Please post your code

**Comment by bitgenerator** [comment]
`#ifndef MyController_hpp
#define MyController_hpp

#include "DTOs.hpp"

#include "oatpp/web/server/api/ApiController.hpp"
#include "oatpp/core/macro/codegen.hpp"
#include "oatpp/core/macro/component.hpp"

#include OATPP_CODEGEN_BEGIN(ApiController) ///< Begin Codegen

/**
 * Sample Api Controller.
 */
class MyController : public oatpp::web::server::api::ApiController {
public:
	/**
	 * Constructor with object mapper.
	 * @param objectMapper - default object mapper used to serialize/deserialize DTOs.
	 */
	MyController(OATPP_COMPONENT(std::shared_ptr<ObjectMapper>, objectMapper))
		: oatpp::web::server::api::ApiController(objectMapper)
	{}
public:

	ENDPOINT("GET", "/users", getUsers,
		QUERY(Int32, age))
	{
		OATPP_LOGD("Test", "age=%d", age->getValue());
		return createResponse(Status::CODE_200, "OK");
	}


	// TODO Insert Your endpoints here !!!

};

#include OATPP_CODEGEN_END(ApiController) ///< End Codegen

#endif /* MyController_hpp */
`

**Comment by bitgenerator** [comment]
Yes, this will work. Thx a lot for you quick answer. So, it is wrong in documentaion?

**Comment by lganzzzo** [comment]
Yes, documentation may be outdated from place to place

**Comment by bitgenerator** [comment]
Ok, thanks a lot and thanks for your fast response.
