### ISSUE TITLE
ClassId are euqal, but Type::extends() return false

### ISSUE THREAD

**Issue by yikenan** [oatpp/oatpp#557]
Hello, I have a question about oatpp::Any.
My test code is as follows，see the comments for my questions, thank you.

```
#include OATPP_CODEGEN_BEGIN( DTO )

class DtoTest : public oatpp::DTO
{
    DTO_INIT( DtoTest, DTO )
    DTO_FIELD( Any, test );
};

#include OATPP_CODEGEN_END( DTO )

const char *szJson = "{\"test\" : 123}";

int main()
{
    oatpp::parser::json::mapping::ObjectMapper objMapper;
    auto spDto = objMapper.readFromString<oatpp::Object<DtoTest>>( szJson );

    auto pClassType = spDto->test.getStoredType();
    if ( pClassType->classId == oatpp::Float64::Class::getType()->classId )
    {
        std::cout << "classId are equal, classId.id = " << pClassType->classId.id
                  << ", classId.name = " << pClassType->classId.name << std::endl;
    }

    if ( !pClassType->extends( oatpp::Float64::Class::getType()))
    {
        // My expectation is true. Should it be true? Is it a bug?
        // Therefore, the retrieve() function cannot be used and an exception will be thrown
        // spDto->test.retrieve<oatpp::Float64>();
        std::cout << "extends() return false" << std::endl;
    }

    if ( pClassType != oatpp::Float64::Class::getType())
    {
        // extends() return false because the pointers are not equal
        // Shouldn't they be equal?
        std::cout << "Pointers are not equal" << std::endl;
    }

    return 0;
}
```

Run the code, output is as follows

```
classId are equal, classId.id = 15, classId.name = Float64
extends() return false
Pointers are not equal

```

**Comment by yikenan** [comment]
My environment:
Oatpp 1.3.0
gcc 9.3.0

**Comment by yikenan** [comment]
I ran the oatpp test program oatpp alltests, which has the same code, but there is no problem:

```
 I |2022-02-03 18:37:55 1643884675074373| TEST[parser::json::mapping::DeserializerTest]:START...
 D |2022-02-03 18:37:55 1643884675074458| TEST[parser::json::mapping::DeserializerTest]:Any: String
 D |2022-02-03 18:37:55 1643884675074484| TEST[parser::json::mapping::DeserializerTest]:Any: Boolean
 D |2022-02-03 18:37:55 1643884675074500| TEST[parser::json::mapping::DeserializerTest]:Any: Negative Float
 D |2022-02-03 18:37:55 1643884675074525| TEST[parser::json::mapping::DeserializerTest]:Any: Positive Float
 D |2022-02-03 18:37:55 1643884675074540| TEST[parser::json::mapping::DeserializerTest]:Any: Negative exponential Float
 D |2022-02-03 18:37:55 1643884675074555| TEST[parser::json::mapping::DeserializerTest]:Any: Positive exponential Float
 D |2022-02-03 18:37:55 1643884675074569| TEST[parser::json::mapping::DeserializerTest]:Any: Unsigned Integer
 D |2022-02-03 18:37:55 1643884675074586| TEST[parser::json::mapping::DeserializerTest]:Any: Signed Integer
 I |2022-02-03 18:37:55 1643884675074605| TEST[parser::json::mapping::DeserializerTest]:FINISHED - success!
 I |2022-02-03 18:37:55 1643884675074617| TEST[parser::json::mapping::DeserializerTest]:221(micro), 42(objs)
```

But when the above code is compiled into an executable program separately, problems always appear.
They all use oatpp dynamic library under Linux.

**Comment by yikenan** [comment]
It may be caused by the compilation parameters of my project, which needs further research to confirm

**Comment by lganzzzo** [comment]
Hello @yikenan ,

This is a strange bug, `oatpp 1.3.0` should deserialize test in this json `"{\"test\" : 123}"` to `Int64` - NOT `Float64`.

My best guess is that it's because you have oatpp linked as a dynamic library.
oatpp meant to be used as a static library (most probably that's why oatpp tests work correctly - because they link oatpp statically).
oatpp as a dynamic lib is not guaranteed to work correctly.

Another thing that I suggest checking - is whether you have some old headers left from prev oatpp installations.
Try to delete the oatpp installation completely and then install the latest oatpp `1.3.0`.

Regards,
Leonid

**Comment by yikenan** [comment]
> Hello @yikenan ,
> 
> This is a strange bug, `oatpp 1.3.0` should deserialize test in this json `"{\"test\" : 123}"` to `Int64` - NOT `Float64`.
> 
> My best guess is that it's because you have oatpp linked as a dynamic library. oatpp meant to be used as a static library (most probably that's why oatpp tests work correctly - because they link oatpp statically). oatpp as a dynamic lib is not guaranteed to work correctly.
> 
> Another thing that I suggest checking - is whether you have some old headers left from prev oatpp installations. Try to delete the oatpp installation completely and then install the latest oatpp `1.3.0`.
> 
> Regards, Leonid

**Comment by yikenan** [comment]
Hello,@lganzzzo, thanks for your reply!

Reason found:
1. Oatpp is compiled to dynamic library
2. The compiler option "- fvisibility = hidden" is set in my project, which changes the visibility of symbols to hidden. If need to export symbols, use__ attribute__ ((visibility ("default")) modify the visibility, similar to that under MSVC__ declspec(dllexport)

The above reasons are indispensable. If only use dynamic library, there is no problem.
Of course, there is no problem using static libraries.

**Comment by lganzzzo** [comment]
Hey @yikenan ,
Thanks for posting the solution!

**Comment by yikenan** [comment]
The reason for this problem is that the function implementation in the header file produces symbols in the dynamic library and executable file respectively.
For example, in oatpp/core/data/mapping/type/Primitive.hpp file:

```
  class Int64 {
  public:
    static const ClassId CLASS_ID;

    static Type* getType(){
      static Type type(CLASS_ID);
      return &type;
    }

  };
```
The "static Type type" in getType()  produces symbols in the dynamic library and executable file respectively.

**This problem can be avoided by moving the getType() function implementation from hpp file to cpp file.**

I suggest modifying the code. What's your opinion @lganzzzo
