### ISSUE TITLE
How can I send data from the channel to download the client?

### ISSUE THREAD

**Issue by Vadim6446** [oatpp/oatpp#564]
Hello!

Could you suggest such a moment - somehow you can give the client to download the file that is generated by ffmpeg via pipe? So far, I have only written writing to pipe and reading. I can't figure out how to send data to a client...

`ENDPOINT("GET", "/download", download, QUERIES(QueryParams, queryParams), REQUEST(std::shared_ptr<IncomingRequest>, request)) {
    char buffer[128];
    FILE* pipe = popen(ffmpegCommand.c_str(), "r");
    
    if (!pipe) throw std::runtime_error("popen() failed!");
    try {
        while (fgets(buffer, sizeof buffer, pipe) != NULL) {
            std::cout<<buffer<<endl;
        }
    } catch (...) {
        pclose(pipe);
        throw;
    }
    pclose(pipe);

    return createResponse(Status::CODE_200, "");
}`

**Comment by lganzzzo** [comment]
Hello @Vadim6446 ,

You can use streaming body for this:

```cpp
#include "oatpp/web/protocol/http/outgoing/StreamingBody.hpp"

...

class ReadCallback : public oatpp::data::stream::ReadCallback {
private:
  FILE* m_pipe;
public:

  ReadCallback() {
    // TODO init pipe
  }

  ~ReadCallback() {
    // TODO delete pipe
  }

  v_io_size read(void *buffer, v_buff_size size, async::Action& action) override {
    (void) action;
    return std::fread(buffer, 1, size /* size of the buffer*/, m_pipe);
    // NOTE - if read returns 0 - stream stops
  }

};

ENDPOINT("GET", "/download", download, 
         QUERIES(QueryParams, queryParams), 
         REQUEST(std::shared_ptr<IncomingRequest>, request)) 
{
  auto body = std::make_shared<oatpp::web::protocol::http::outgoing::StreamingBody>
    (std::make_shared<ReadCallback>());
  return OutgoingResponse::createShared(Status::CODE_200, body);
}

```

**Comment by Vadim6446** [comment]
Hey @lganzzzo  ! thanks a lot, it works!
