### ISSUE TITLE
multipart application question

### ISSUE THREAD

**Issue by Augustus-demon** [oatpp/oatpp#568]
my upload file post body are like this :
```
 --boundary_.oOo._MjU2NTA=NzAyMjUzMjc=
Content-Disposition: form-data; name="file"; filename="20220301-124345.log"

2022/03/01 12:50:28.188, DEBUG, 15464, SSLoading start
2022/03/01 12:50:28.189, DEBUG, 15464, Version=Ver 2.5.0
2022/03/01 12:50:28.190, WARNING, 15464, Led fill light is disconnect!
//log information.....
```
How could I gain the value of param ```filename``` inside ```ENDPOINT``` besides parse the request body myself ?
I tried the multipart which can only get the value of ```name```.

**Comment by leopicis** [comment]
Maybe this can work for you.  I've just got the example from https://oatpp.io/docs/features/upload-file/ and added this.
```
/* Get the multipart 'file'*/
auto myfilePart = multipart->getNamedPart("file");

/* Get part data input stream */
auto filenameStream = myfilePart->getFilename();

/* Print value of "filename" */
OATPP_LOGD("Multipart", "FileName='%s'", filenameStream->c_str());
```

**Comment by Augustus-demon** [comment]
@leopicis Thanks for the reply. Last time I've noticed the func getFilename and tried, which is not work for me. That's why I start a issue here, I've tried again just now and successfully got the filename. It's pretty weird, Thanks anyway.

**Comment by Augustus-demon** [comment]
@leopicis Thanks for the reply. Last time I've noticed the func getFilename and tried, which is not work for me. That's why I start a issue here, I've tried again just now and successfully got the filename. It's pretty weird, Thanks anyway.
