### ISSUE TITLE
How to serve static files?

### ISSUE THREAD

**Issue by hhashoww** [oatpp/oatpp#569]
Hi,

I'd like to use oatpp to serve web service in my project

I follow the example to declare a "StaticFilesManager"
```

class StaticFilesManager {
 private:
  oatpp::String m_basePath;
  oatpp::concurrency::SpinLock m_lock;
  std::unordered_map<oatpp::String, oatpp::String> m_cache;

 public:
  StaticFilesManager(const oatpp::String& basePath) : m_basePath(basePath) {}
  oatpp::String getFile(const oatpp::String& path) {
    if (!path) {
      return nullptr;
    }
    std::lock_guard<oatpp::concurrency::SpinLock> lock(m_lock);
    auto& file = m_cache[path];
    if (file) {
      return file;
    }
    oatpp::String filename = m_basePath + "/" + path;
    file = oatpp::String::loadFromFile(filename->c_str());
    return file;
  }
};
```
And I declare the URL like this to serve my root URL:
```
  ENDPOINT("GET", "/", Root) {
    auto file = staticFileManager->getFile("index.html");
    auto response = createResponse(Status::CODE_200, file);
    return response;
  }
```

The "index.html" ask for several static files, such as:
* styles.026259045da9c6d2a1d9.css <= ("GET", https://localhost:8443/styles.026259045da9c6d2a1d9.css)
* polyfills.86f12ab7eee2205c7c28.js
* runtime.0acc8b1248276b2ac4a6.js
* main.f8f8b4ffb2a055c9b80b.js
* scripts.6352bf846293ccd4c8b0.js
* assets/i18n/en-US.json
* assets/img/logo_w.png
* ...

So that, I try to use the declaration to serve those requests:
```
  ENDPOINT("GET", "*", GetStaticFiles, REQUEST(std::shared_ptr<IncomingRequest>, request)) {
    // Get the target file
    auto tail = request->getPathTail();
    auto file = staticFileManager->getFile(request->getPathTail());
    OATPP_ASSERT_HTTP(file.get() != nullptr, Status::CODE_404, "File not found");
    return createResponse(Status::CODE_200, file);
  }
```

But the other URL will be ignored by the above declaration, like this
```
  ENDPOINT("GET", "/test", test) {
    return createResponse(Status::CODE_200, "OK");
  }
```

How should I design the correct declaration??

Thanks for help

**Comment by hhashoww** [comment]
I solved the problem
```
Endpoint with "*" mapping should be added as a bottom list endpoint. In order not to intercept other mappings.
```

Reference:
https://github.com/oatpp/oatpp/issues/52#issuecomment-475598229

**Comment by XDinEuro** [comment]
@hhashoww Hi, may I ask that how u manage to serve static files ?

I had a web pack built from Vuejs project, the content of index.html looks similar to yours.

But I have those errors when loading the page 

```
Uncaught SyntaxError: expected expression, got '<'
[chunk-vendors.80bc871e.js:1](http://localhost:8000/js/chunk-vendors.80bc871e.js)
Uncaught SyntaxError: expected expression, got '<'
[app.50011e50.js:1](http://localhost:8000/js/app.50011e50.js)
```

Could u provide some inforamtion if u know some insides ?
