### ISSUE TITLE
When oatpp can support MQTT client？

### ISSUE THREAD

**Issue by YuaXan** [oatpp/oatpp#586]
When oatpp can support the MQTT client？
Now iot device used MQTT,  the oatpp if will support MQTT?

**Comment by bamkrs** [comment]
MQTT is out of scope of Oat++. But you are invited to contribute a MQTT-Module anytime.

**Comment by YuaXan** [comment]
> MQTT is out of scope of Oat++. But you are invited to contribute a MQTT-Module anytime.

@bamkrs 
No problem, but I need some time to know about Oat++

**Comment by bamkrs** [comment]
We have a big portfolio of examples and starter-modules that will get your project up an running in no time. If you have any questions feel free to ask them via Gitter.
