### ISSUE TITLE
Store the DTO objects in map

### ISSUE THREAD

**Issue by hrnozel** [oatpp/oatpp#611]
I need to store DTO objects in a std::map and already I have done. But during unit tests running, oatpp is giving an error that leaks objects. When I comment out part of storing the DTO objects, oatpp stopped giving up complaining about leaked objects.

I guess there is something wrong with my code or already DTOs can not be stored in containers.

I added some code snippets.

```
/* Default configuration For serial interfaces*/
  auto myDTO =
      mydto::createShared();

  m_map.insert({"my_dto", myDTO.getPtr()});
```

**Comment by lganzzzo** [comment]
Hello @thirtyninekilovolts ,

You can use oatpp objects where ever you want. 
Just make sure that you:

1. Create oatpp objects **after** call to `oatpp::base::Environment::create()`
2. Delete all oatpp object **before** call to `oatpp::base::Environment::destroy()`

```c++

void run() {

  std::unordered_map<oatpp::String, oatpp::Object<MyDto>> map;

  auto myDTO = MyDto::createShared();

  map.insert({"my_dto", myDTO});

  map.clear(); // <-- clear map to delete all oatpp objects

}

int main(int argc, const char * argv[]) {

  oatpp::base::Environment::init();
  run();
  oatpp::base::Environment::destroy();

  return 0;
}
```

**Comment by thirtyninekilovolts** [comment]
Hello @lganzzzo,

Thank you so much for your answer.

Actually, I already wrote it the way you wrote it. There is a small change, I store DTO objects with shared_ptr. You stored it as oatpp object. If this is causing leaking I will be changing my code.
