### ISSUE TITLE
Looking for POST examples that use ENDPOINT instead of API_CALL

### ISSUE THREAD

**Issue by Deoxys0** [oatpp/oatpp#615]
Hello, 

I've been learning Oat++ after coming from Drogon and I'm trying to make a simple ENDPOINT that is a POST instead of a GET, but I can't find any examples of this anywhere, not even in the documentation. I did find one POST example but it didn't do anything with the data you'd get from a POST. I'm looking for an example that does/has the following:

1) Is an ENDPOINT in a controller file that is POST
2) READS data received from the front end and clearly shows HOW TO GET THAT DATA (in this case, a json sent from a web gui)
3) READS header data received from the front end, including getting cookies (if this isn't possible in the same ENDPOINT then having it in another is fine)
EXAMPLE:
1) Web gui sends a json containing { "animal" : "cat" } to path /Pet; additionally, the frontend attaches a cookie called "TEST" to the headers of the call
2) The backend Oat++ grabs the json in an ENDPOINT call and then logs the contents of said json, so the console should show "animal: cat" or something like that.
3)  The backend Oat++ logs the cookie it got in the header, which is named "TEST"

I do NOT need code for an entire project, just the ENDPOINT because that's the part I can't seem to get working.

I would also like to see a version of GET that reads header data if possible.

I've been messing with this all day and am about to rip my hair out over it. I'd really appreciate some help, even if it's just a simple code snippet.

**Comment by lganzzzo** [comment]
Hello @Deoxys0 ,


Endpoint:

```c++
  ENDPOINT("POST", "Pet", postPet,
           HEADER(String, cookie),
           BODY_DTO(Object<PetDto>, pet))
  {

    if(pet->animal) {
      OATPP_LOGD("data", "animal='%s', cookie='%s'", pet->animal->c_str(), cookie->c_str())
    }

    return createResponse(Status::CODE_200, "OK");
  }
```

DTO:

```c++
class PetDto : public oatpp::DTO {

  DTO_INIT(PetDto, DTO)

  DTO_FIELD(String, animal);

};
```
