### ISSUE TITLE
Remove unnecessary null pointer checks

### ISSUE THREAD

**Issue by elfring** [oatpp/oatpp#62]
[An extra null pointer check is not needed in functions](https://isocpp.org/wiki/faq/freestore-mgmt#delete-handles-null "Do I need to check for null before delete p?") like the following.
- [Action](https://github.com/oatpp/oatpp/blob/b0fa7aff34937265c5aebaff952e44e8a02af7cc/src/oatpp/core/async/Coroutine.cpp#L62 "Destructor for Action")
- [Environment::setLogger](https://github.com/oatpp/oatpp/blob/606e0550721acbff81eafc882baecffaece71384/src/oatpp/core/base/Environment.cpp#L110 "Environment::setLogger function")

**Comment by lganzzzo** [comment]
Hey @elfring ,
Nice tip!

Those extra nullptr checks are redundant and should be removed.

Regards,
Leonid

**Comment by lganzzzo** [comment]
Fixed

**Comment by elfring** [comment]
Thanks for [your small source code improvement](https://github.com/oatpp/oatpp/commit/1fcdcc2fe0ec76481aec126579ba0003589c97a2 "Remove a redundant check").
[Another update candidate was left over](https://github.com/oatpp/oatpp/blob/d353593adf93dbfa82243ef985315b330743ddf7/src/oatpp/core/async/worker/IOEventWorker_common.cpp#L48 "Destructor for IOEventWorker").

**Comment by lganzzzo** [comment]
Hey @elfring ,
Thanks for your attention!

> Thanks for your small source code improvement.
> Another update candidate was left over.

Fixed in https://github.com/oatpp/oatpp/commit/a85073f7f0ba0b0c802a77e93fea6be20137ee35

**Comment by elfring** [comment]
Thanks for [another small source code improvement](https://github.com/oatpp/oatpp/commit/b7d305780ac98315a855a6c4bc5ff3893d9c8ca0 "Remove redundant checks").
