### ISSUE TITLE
Can you send a response and then continue execution?

### ISSUE THREAD

**Issue by MarkosKon** [oatpp/oatpp#620]
Is it possible, in an endpoint, to send a response back to the client and then continue executing code inside the endpoint? 

For example:

- Validate the data and send a quick response back to the client.
- Proceed with a slow API call to an external service (or something that takes time in general).
- Notify a server with the result.

**Comment by lganzzzo** [comment]
Hello @MarkosKon ,

You can delegate processing to a different thread and return response to the client immediately.

**Comment by MarkosKon** [comment]
Thanks @lganzzzo, I will try that. Probably with a task queue that will be shared between threads.
