### ISSUE TITLE
Improve exception safety with smart pointers

### ISSUE THREAD

**Issue by elfring** [oatpp/oatpp#63]
Would you like to [wrap any pointer data members](https://github.com/oatpp/oatpp/blob/57e2879dc0e7a50534b4ad174394d6c734b1b9bd/src/oatpp/core/async/Executor.cpp#L84 "Update candidate: Executor class") with the class template “[std::unique_ptr](https://en.wikipedia.org/wiki/Smart_pointer#unique_ptr "Description for the usage of smart pointers")”?

**Comment by lganzzzo** [comment]
Hey @elfring ,

I believe, that extra `std::unique_ptr` wrapper is not needed here.
Since m_threads, and m_processors arrays are enclosed in Executor .
Both m_threads, and m_processors and will be deleted in Executor's destructor.

Regards,
Leonid

**Comment by elfring** [comment]
The proper deletion of these objects will depend on the validity of the passed pointers.
How will the software situation look there if an exception like std::bad_alloc was thrown?

**Comment by lganzzzo** [comment]
Here, in case of `exception like std::bad_alloc` program should fail. In this case further execution of the program has no sense without properly constructed Executor.

**Comment by elfring** [comment]
The handling of C++ exceptions could become safer at such source code places, couldn't it?

**Comment by lganzzzo** [comment]
Agree, this may be improved.
It makes code more robust.

Regards,
Leonid

**Comment by lganzzzo** [comment]
Fixed

**Comment by elfring** [comment]
Thanks for [your source code improvement](https://github.com/oatpp/oatpp/commit/acc719957acb8481b6642523ec386212b7ed3bc4 "Refactor oatpp::async::worker::Worker interface").
