### ISSUE TITLE
ApiClient transmits binary content of image file through response body in ARMV7 Linux environment problem

### ISSUE THREAD

**Issue by corner4world** [oatpp/oatpp#636]
ApiClient transmits binary content of image file through response body in ARMV7 Linux environment, and the returned body content size is 0. In ubuntu x86_ 64 No problems in the environment
CODE:

String httpfmp4_url = "http://127.0.0.1:8080/live/ch" + channelDto->videoChannelId + ".live.mp4";
            auto data = zlmClient->getSnap("application/octet-stream","035c73f7-bb6b-4889-a715-d9eb2d1925cc",5,2,httpfmp4_url)->readBodyToString();
            OATPP_LOGD("VideoChannelController", "Test.............. %s", data->size());

LOG:
 D |2022-09-29 20:20:31 1664454031184574| VideoChannelController:Test.............. 0

**Comment by lganzzzo** [comment]
Hello @corner4world ,

Please check the response status code.
Most probably the response isn't `200` when run from a different env.

**Comment by lganzzzo** [comment]
Hello @corner4world ,

Obviously `response` is `null`.
Most probably it couldn't connect to server.

Please make sure that your remote server is accessible from your arm linux box.

**Comment by corner4world** [comment]
The two programs are on the same arm machine. I changed the getSnap response body content to the snap file name, API_ CALL is working properly. The original body contains jpeg image content, API_ CALL returns null. It's strange why this happens.

**Comment by lganzzzo** [comment]
Hello @corner4world ,

Did you find what was the cause or why closing this ticket?

**Comment by turnarond** [comment]
response->getStatusCode() return v_int32, use %d not %s
