### ISSUE TITLE
Hello, I want to ask about websocket disconnection

### ISSUE THREAD

**Issue by redoriental** [oatpp/oatpp#646]
When I use websocket to transmit video streams, websocket will be disconnected. I think this is related to the transmission size limit of websocket. I modified the cache size of config.h file, but this problem still occurs.

**Comment by lganzzzo** [comment]
Hello @redoriental ,

We need some more context from you...

- What is `config.h` is this question about oatpp? oatpp has no `.h` files - it uses `.hpp` extension for headers.
- What is `cache size of config.h file`? please post a link.

How long are you able to transmit video before stream breaks?
Please share some code of yours.

Regards,
Leonid

**Comment by lganzzzo** [comment]
This issue looks irrelevant. Closing...
