### ISSUE TITLE
How loadFromFile deal with `\0`?

### ISSUE THREAD

**Issue by csyJoy** [oatpp/oatpp#648]
when I use `oatpp::String::loadFromFile()`，a question comes to my mind: How `loadFromFile` deal with `\0`?

I look up the source code and find `loadFromFile` read file in binary mod, and then cast the file data into char and build a oatpp::String object return.

if there is occasionally 8bit 0 in the file and loadFromFile cast it into char and build oatpp::String from it, the content of file may be cut since it contain a \0 in string body.

```cpp
auto s = oatpp::String::loadFromFile(FILEPATH)
createResponse(Status::CODE_200, s)
```

I would like to know if the above scenario will happen, If so, Is there any good way to fill response body with byte stream directly?

**Comment by lganzzzo** [comment]
Hello @csyJoy ,

There is nothing to worry about. `oatpp::String` can store binary data with no problems.
