### ISSUE TITLE
An error. Ambiguous component reference

### ISSUE THREAD

**Issue by Vadim6446** [oatpp/oatpp#649]
Error appears from time to time:
: terminate called after throwing an instance of 'std::runtime_error'
	what(): [oatpp::base::Environment::getComponent()]: Error. Ambiguous component reference. Multiple components exist for a given type: type='St10shared_ptrIN5oatpp7network24ServerConnectionProviderEE'

In what cases does it appear? and how to deal with it?

**Comment by lganzzzo** [comment]
Hello @Vadim6446 ,

It happens when you have multiple components of the same type:

```cpp
  OATPP_CREATE_COMPONENT(std::shared_ptr<ServerConnectionProvider>, connectionProvider_1)("provider-1", [] {
    return tcp::server::ConnectionProvider::createShared({"0.0.0.0", 8000, Address::IP_4});
  }());

  OATPP_CREATE_COMPONENT(std::shared_ptr<ServerConnectionProvider>, connectionProvider_2)("provider-2", [] {
    return tcp::server::ConnectionProvider::createShared({"0.0.0.0", 8001, Address::IP_4});
  }());
```

Both are `ServerConnectionProvider` so oatpp can't resolve component by only it's type:

```cpp
OATPP_COMPONENT(std::shared_ptr<ServerConnectionProvider>, connectionProvider); //<--- Error is here
```

In such case you have to provide its qualifier also:

```cpp
OATPP_COMPONENT(std::shared_ptr<ServerConnectionProvider>, connectionProvider, "provider-1"); //<--- Success
```

**Comment by Vadim6446** [comment]
Hey, @lganzzzo  Thank you very much for the quick answer, I made changes in the code, I'll be watching!
