### ISSUE TITLE
How do I disable swagger in my production environment?

### ISSUE THREAD

**Issue by speedster** [oatpp/oatpp#650]
I need to disable swagger in my living environment. But I can't find the relevant documentation.
I use the demo is it: https://github.com/oatpp/example-crud

**Comment by lganzzzo** [comment]
Hello @speedster ,

> I need to disable swagger

Just don't add `swagger::Controller` to `Router`
https://github.com/oatpp/example-crud/blob/master/src/App.cpp#L24

**Comment by speedster** [comment]
Okay!
