### ISSUE TITLE
request parameter is body json then post request is not supported

### ISSUE THREAD

**Issue by cyang-catalogicsoftware** [oatpp/oatpp#651]
Hi ,   The request method is post, the request parameter is json, and the parameter is passed through the body, but the queryParameter() method cannot obtain any parameter

can you help  me

**Comment by lganzzzo** [comment]
Hello @cyang-catalogicsoftware ,

Please post your endpoint code, and your request

**Comment by cyang-catalogicsoftware** [comment]
![image](https://user-images.githubusercontent.com/101167617/200990347-e76df1c6-d6c6-4164-8d1e-330fd95c949c.png)
![image](https://user-images.githubusercontent.com/101167617/200990607-e3688a0a-c422-4f3b-922a-22c908753985.png)
![image](https://user-images.githubusercontent.com/101167617/200990672-4b2d15ab-7e29-4a45-a32e-44cee81f5c51.png)
![image](https://user-images.githubusercontent.com/101167617/200990769-763eb60f-7ec8-4791-b7e8-c20ced26034c.png)

Unable to get parameters from body

**Comment by XXOO9** [comment]
老表，我刚解决这个问题，可能还有其他的写法，我这样写也可以把请求体里面的参数解出来
![image](https://user-images.githubusercontent.com/75569891/234811620-3e263326-aa6a-4f62-a105-6d749a181bf7.png)
![image](https://user-images.githubusercontent.com/75569891/234811976-cf4725f2-1e12-4fcf-b461-ac9a73aecd35.png)
