### ISSUE TITLE
SSL error

### ISSUE THREAD

**Issue by Vadim6446** [oatpp/oatpp#654]
Hello @lganzzzo 
Error appears from time to time:
what():  [oatpp::openssl::configurer::PrivateKeyFile::configure()]: Error. Call to 'SSL_CTX_use_PrivateKey_file' failed.
In what cases does it appear? and how to deal with it?

**Comment by lganzzzo** [comment]
Hello @Vadim6446 ,

It means that openssl failed to read PK file for some reason.
For more info search for `SSL_CTX_use_PrivateKey_file` errors
Example - https://stackoverflow.com/questions/19029647/ssl-ctx-use-privatekey-file-failed

**Comment by Vadim6446** [comment]
No questions. Thank you very much for the information!
