### ISSUE TITLE
queryParams.get() crashes for ARM with particular input

### ISSUE THREAD

**Issue by aeschbacher** [oatpp/oatpp#655]
Following code makes the server crash :

```c++
ADD_CORS(example)
  ENDPOINT("GET", "/api/v1/example", example,
    QUERIES(QueryParams, queryParams),
    REQUEST(std::shared_ptr<IncomingRequest>, request))
  {
    std::string message = "";

    message = queryParams.get("message");               // <-- crash happens here
    OATPP_LOGD(TAG, "message = %s", message.c_str());   // <-- this line is never reached
    ...

```

with following input:

```
http://localhost:8000/api/v1/example?message=test'\''%22%600%26nslookup%20-q%3Dcname%20google.com.%26%60'\''
```

> Note: the crash only happens when cross-compiled for ARM , but not when compiled for x86.

I tried another way instead of `queryParams.get()` , and got similar result:

```C++
    for(auto& param : queryParams.getAll()) {
      OATPP_LOGD(TAG, "param %s=%s", param.first.getData(), param.second.getData());  // <-- crash here
      OATPP_LOGD(TAG, "debug");   // <-- never reach this line
    }

```

> Note: with more conventional input (e.g. `message=test-xx-yy-something`) both methods work fine, the application does not crash.

**Comment by lganzzzo** [comment]
@aeschbacher ,

Interesting the above code works fine for me.
Can you please post your stack-trace

Also, a minor comment:
Since you are using query-params your ENDPOINT path should be - `"/api/v1/example/*"`
