### ISSUE TITLE
readFromStreamAndWrite  

### ISSUE THREAD

**Issue by cyang-catalogicsoftware** [oatpp/oatpp#658]
How not to block

![image](https://user-images.githubusercontent.com/101167617/201295396-9831be23-be73-41d6-ab6f-8584e9a9df14.png)

**Comment by lganzzzo** [comment]
Hello @cyang-catalogicsoftware ,
Your stream has to be in the `Async` mode in order not to block

**Comment by cyang-catalogicsoftware** [comment]
thanks ,  I'd like to ask you another question,

ResponseFactory::createResponse(Status::CODE_200, str);

Can the returned results support Chinese ?  The returned data is  garbled code
