### ISSUE TITLE
how can ApiController ENDPOINT route indefinite length URL?

### ISSUE THREAD

**Issue by csyJoy** [oatpp/oatpp#663]
I have two request url:

`/foo/file1/bar/foobar`
`/foo/dir1/file2/bar/foobar`

I generate a ENDPOINT in ApiController using
```cpp
ENDPOINT(METHOD, "/foo/{file}/bar/foobar", FooBar)
```
but when I send the second request to the oatpp server, It response 404 not found, It seems that oatpp didn't match the url.
The `file` may contain a directory information, how can I route both of two url into one handler?

PS: I know that I can generate two different ENDPOINT to solve this problem, But the depth of directories is undecidable I wonder whether there exist a better solution in oatpp, maybe regex?

**Comment by Peibohao** [comment]
Same question +1
 
I also encountered this problem when developing a project using OATPP, and I sincerely hope the author can answer the question. Thanks a lot!

**Comment by doufu3344** [comment]
It doesn't seem to support regex, maybe you can try this:
```c++
ENDPOINT("GET", "foo/*", FooBar
    , REQUEST(std::shared_ptr<IncomingRequest>, request)
) {
    // path is "/foo/file1/bar/foobar"or "/foo/dir1/file2/bar/foobar"
    auto path = request->getStartingLine().path.toString();
    //TODO Process the request path
    ... ...
}
```
Note that the `*` will match **all subsequent string** in the path. That is to say, If you have two two endpoints as `/foo/{file}/bar/foobar1` and `/foo/{file}/bar/foobar2`, they will relate to the same endpoint. You can't identify different suffixes with macros `ENDPOINT`. I don't know if there is a better implementation.

**Comment by csyJoy** [comment]
> It doesn't seem to support regex, maybe you can try this:
> 
> ```c++
> ENDPOINT("GET", "foo/*", FooBar
>     , REQUEST(std::shared_ptr<IncomingRequest>, request)
> ) {
>     // path is "/foo/file1/bar/foobar"or "/foo/dir1/file2/bar/foobar"
>     auto path = request->getStartingLine().path.toString();
>     //TODO Process the request path
>     ... ...
> }
> ```
> 
> Note that the `*` will match **all subsequent string** in the path. That is to say, If you have two two endpoints as `/foo/{file}/bar/foobar1` and `/foo/{file}/bar/foobar2`, they will relate to the same endpoint. You can't identify different suffixes with macros `ENDPOINT`. I don't know if there is a better implementation.

It a better solution than mine, I just add additional http service with fixed directory information, But this approach may gather all GET service together in my project.
