### ISSUE TITLE
Error when parsing a Boolean

### ISSUE THREAD

**Issue by Inujel** [oatpp/oatpp#673]
I think there might be a bug in `ObjectMapper<Boolean>::readFromString`:
https://github.com/oatpp/oatpp/blob/6063b57b250bfa9bdf02c47351a4a4ce1a969079/src/oatpp/core/data/mapping/ObjectMapper.hpp#L124-L133

When the given string is `"false"`, it is correctly parsed, but the `bool` conversion operator of `Boolean`
https://github.com/oatpp/oatpp/blob/6063b57b250bfa9bdf02c47351a4a4ce1a969079/src/oatpp/core/data/mapping/type/Primitive.hpp#L431-L436

gets invoked at line 129 and an error is raised. The program then crashes because `caret.getErrorMessage()` is null.

Reproduction:
```cpp
#include "oatpp/parser/json/mapping/ObjectMapper.hpp"
#include "gtest/gtest.h"

using namespace oatpp::parser::json::mapping;

TEST(oatpp, parse_true)
{
   ObjectMapper json_mapper(Serializer::Config::createShared(),
                            Deserializer::Config::createShared());
   ASSERT_TRUE(json_mapper.readFromString<oatpp::Boolean>("true"));
}

TEST(oatpp, parse_false)
{
   ObjectMapper json_mapper(Serializer::Config::createShared(),
                            Deserializer::Config::createShared());
   ASSERT_FALSE(json_mapper.readFromString<oatpp::Boolean>("false")); // <- crash
}
```

**Comment by lganzzzo** [comment]
Hello @Inujel ,

Nice catch!

It should be an explicit `nullptr` check

```cpp
   auto result = read(caret, type).template cast<Wrapper>(); 
   if(result == nullptr) { 
     throw oatpp::parser::ParsingError(caret.getErrorMessage(), caret.getErrorCode(), caret.getPosition()); 
   } 
```

Please feel free to send a PR!
