### ISSUE TITLE
Monitor API question

### ISSUE THREAD

**Issue by WillHJChen** [oatpp/oatpp#677]
In file: oatpp/network/monitor/ConnectionMonitor.hpp

# Question

Hi, I try to use the monitor at the client.

I use the "ConnectionMonitor" to the "connectionProvider", which would let the request headers "Host" values empty.

If I remove this monitoring everything works. Why is this happening?

I wrote this in the code:
```
  API_CALL("POST", "api/login", DoPostLogin, BODY_DTO(Object<LoginRequestDto>, body))
```

```
  auto objectMapper = oatpp::parser::json::mapping::ObjectMapper::createShared();      
  
  std::shared_ptr<oatpp::web::client::RequestExecutor> requestExecutor;
      
  auto connectionProvider = oatpp::network::tcp::client::ConnectionProvider::createShared({device_ip_.toStdString(), port_, 
  oatpp::network::Address::IP_4});
  // device_ip_.toStdString() -> 192.168.127.253
  // port_ -> 80

  auto monitor = std::make_shared<oatpp::network::monitor::ConnectionMonitor>(connectionProvider);

  requestExecutor = oatpp::web::client::HttpRequestExecutor::createShared(monitor);
  client_ = Client::createShared(requestExecutor, objectMapper);
```

[
![monitor_question_wireshark](https://user-images.githubusercontent.com/93573669/206534733-adc179cf-4322-4d4c-9473-c46108ac4b1b.jpg)
](url)

**Comment by lganzzzo** [comment]
Helllo @WillHJChen ,

Thanks for the issue, it's a bug!
Monitor has to forward host property of the connection provider.

**Comment by WillHJChen** [comment]
OK! Thanks for your help.
Currently, I use the API_CALL_HEADERS to append the host property.

**Comment by ilkeroku** [comment]
> OK! Thanks for your help. Currently, I use the API_CALL_HEADERS to append the host property.

Hi, I'm having the same problem you mentioned in the question. How do you use API_CALL_HEADERS here?
