### ISSUE TITLE
Prettify CMake

### ISSUE THREAD

**Issue by DanielHerchenbach** [oatpp/oatpp#681]
Hi,
modern CMake can scan files in a folder recursively and mirror the folder structure in the project hierarchy.
So if you add/rename/remove source files you don't need to touch the includes in Cmake :-)
Also, the code can be browsed much more easily. I am using Visual Studio and for me it is pretty much a relief with these changes.
All we need is CMake >= 3.8 which has been out for more than five years now.

**Comment by DanielHerchenbach** [comment]
Hi Leonid,
could you please grant me write access so I can push these changes to a new branch?

**Comment by lganzzzo** [comment]
Done
