### ISSUE TITLE
Is there any way to handle both path and parameters values?

### ISSUE THREAD

**Issue by kiskit** [oatpp/oatpp#693]
Hello,

admitting that I have an endpoint like this _/users/{userid}_ that accepts query parameters, like _/users/123?role=admin_, is there a way to express that with the ENDPOINT macro?

**Comment by kiskit** [comment]
So answering my own question, yes, you can combine macros like this:
```cpp
ENDPOINT("GET", "entities/{userId}", getEntity,
             PATH(String, userId),
             QUERIES(QueryParams , params))
```
I guess it's not possible to name optional parameters though.

**Comment by papaj-na-wrotkach** [comment]
I think that you can do it by using `ENDPOINT_INFO` macro and setting `info->queryParams["<optional parameter name>"].required = false;`

**Comment by kiskit** [comment]
thanks mate
