### ISSUE TITLE
code 1002 means ?

### ISSUE THREAD

**Issue by XDinEuro** [oatpp/oatpp#697]
Hi, I am using oatpp-websocket.

With wifi I connect to websocket server and keep sending messages.

I randomly lost connect and log:
```
 D |2023-01-02 16:05:54 1672671954582227| Server_WSListener:onClose code=1002
 D |2023-01-02 16:05:54 1672671954582371| Server_WSInstanceListener:Connection closed. Connection count=0
```

I wonder what does 1002 mean? I didn't find documentation about this.

**Comment by doufu3344** [comment]
Refer to the WebSocket Protocol: https://www.rfc-editor.org/rfc/rfc6455#section-7.4

**Comment by XDinEuro** [comment]
Thanks a lot!
