### ISSUE TITLE
Bug in documentation about custom types

### ISSUE THREAD

**Issue by malem-robotiq** [oatpp/oatpp#716]
here is the fixed version

```
struct VPoint {
   v_int32 x;
   v_int32 y;
   v_int32 z;
};

namespace __class {
   class PointClass;
}

/* Declare ObjectWrapper for your type */
/* Mapping-Enabled Point */
typedef oatpp::data::mapping::type::Primitive<VPoint, __class::PointClass> Point;

namespace __class {

/**
   * Type info
 */
class PointClass {
private:

   /**
     * Type interpretation
    */
   class Inter : public oatpp::Type::Interpretation<Point, oatpp::UnorderedFields<oatpp::Int32>>  {
   public:

      oatpp::UnorderedFields<oatpp::Int32> interpret(const Point& value) const override {
         return {{"x", value->x}, {"y", value->y}, {"z", value->z}};
      }

      Point reproduce(const oatpp::UnorderedFields<oatpp::Int32>& map) const override {
         return Point({map["x"], map["y"], map["z"]});
      }

   };

public:

   static const oatpp::ClassId CLASS_ID;

   static oatpp::Type* getType(){
      oatpp::Type::Info info;
      info.interpretationMap = {{"my-types", new Inter()}};
      static oatpp::Type type(CLASS_ID, info /* <-- Add type interpretation */ );
      return &type;
   }

};

const oatpp::ClassId PointClass::CLASS_ID("my-types::Point");

}
```

**Comment by Jithu-08** [comment]
If I have multiple datatypes in struct, how to Interpret all of them in same class, if i write mutiple classes as below for each type, i am finally going to have 3 serialise json strings and 3  Deserialise objects in this case.

I want to avoid this multiple classes and multiple serialise and deserialise steps, is there a way to to fix this or to have a single deserialise objects for all the data types mentioned in the struct.

struct VPoint {
   v_int32 x;
   v_int32 y;
   v_int32 z;
   oatpp::String str;
   Boolean        val;
};
class Inter : public oatpp::Type::Interpretation<Point, oatpp::UnorderedFields<oatpp::Int32>>  {
}
class Inter : public oatpp::Type::Interpretation<Point, oatpp::UnorderedFields<oatpp::String>>  {
}
class Inter : public oatpp::Type::Interpretation<Point, oatpp::UnorderedFields<oatpp::Boolean>>  {
}

**Comment by lganzzzo** [comment]
Hello @Jithu-08 ,

You can use any oatpp type including DTO

```cpp
struct VPoint {
  v_int32 x;
  v_int32 y;
  v_int32 z;
  std::string str;
  bool val;
};

class PointDto : public oatpp::DTO {
  ...
};

class Inter : public oatpp::Type::Interpretation<Point, oatpp::Object<PointDto>> {
  ...
}
```

**Comment by lganzzzo** [comment]
Hello @Jithu-08 ,

All oatpp mapping-enabled typed are nullable. 
If you don't initialize them - they are null.

> Not sure what is wrong in my code, please review my test code and comment.

Sorry no code review. I can answer a question if you have one.
Please create a new issue with a clear question and clean and short and working code example.

I'm closing this one.
