### ISSUE TITLE
Release Owsianka 1.3.0 was over 1 year ago

### ISSUE THREAD

**Issue by Ultra-KVL** [oatpp/oatpp#732]
Reviewing the  release history it looks like a release was being cut every few months but stopped with 1.3.0.  Is there any plan to continue cutting release?  If no, consider having adding a stable branch.

Any information you have on when when code is stable would be greatly appreciated.

**Comment by lganzzzo** [comment]
Hello @Ultra-KVL ,

The latest `master` is stable.

> Is there any plan to continue cutting release?

Yes, please follow [1.4.0 changelog](https://github.com/oatpp/oatpp/blob/master/changelog/1.4.0.md)
At this point there is no strict timeline for `1.4.0`. Hopefully it will be released by July/August 


Regards,
Leonid

**Comment by Ultra-KVL** [comment]
Thank you for the information!
