### ISSUE TITLE
"String LazyStringMapTemplate::get(const Key& key) const" have somthing wrong

### ISSUE THREAD

**Issue by ColdeZhang** [oatpp/oatpp#736]
```
  String get(const Key& key) const {

    std::lock_guard<concurrency::SpinLock> lock(m_lock);

    auto it = m_map.find(key);

    if(it != m_map.end()) {
      it->second.captureToOwnMemory();
      return it->second.getMemoryHandle();
    }

    return nullptr;

  }
```

This method supposed to get value by key from map, when the key doesnt exisit return a empty string.
However oatpp::String seems doesnt receive a nullptr as its constructor. So when I use QUERYS to receive optional prarms, oatpp throws `[oatpp::data::mapping::type::String::operator std::string() const]: Error. Null pointer.` error.

So in my project I changed `nullptr` to '""', it works fine.

Im not sure if this is a bug or intended to be, so I issued it instead of commit a MR.

**Comment by lganzzzo** [comment]
Hello @ColdeZhang ,

If key doesn't exist in the map LazyStringMap will return `nullptr` - this is an expected behavior.

You may use `getValue` method to get with default value:

```cpp
auto str = myMap.get(key).getValue("" /*default value*/);
```

thus if `get(key)` returns null the default value will be assign to `str` var.

**Comment by ColdeZhang** [comment]
That's really helpful, THX!
