### ISSUE TITLE
custom installation makes an extra subfolder

### ISSUE THREAD

**Issue by Saadharta** [oatpp/oatpp#744]
Hello Oatpp mainainers;

Having decided to tidy up  my current workspace, i decided to use the cmake --install command to regroup oatpp's (and extensions) headers and libraries in one place.

My issue is (kinda) trivial and reproductible as the steps to replicate it are as follow:
(i am on Windows, using git for windows bash)

```
$ cd /c/
$ git clone -b 1.3.0 --single-branch https://github.com/oatpp/oatppgit
$ cd oatpp
$ cmake -B build -S. -G "Visual Studio 14 2015" -A Win32 - DOATPP_BUILD_TEST=OFF
# note here: it still builds oatpp-test from the oatpp/src folder.. is it expected as i turned off test building?
$ cmake --build build --config Release -j4
$ cmake --install build --prefix "C:\test_install" --strip
```

I was expecting to only have to add `C:\test_install\include\oatpp_1.3.0` to my project's solution (Visual studio, yaay.) and get the required headers.
However i noticed that instead of having the `C:\test_install\include\oatpp-1.3.0\oatpp\<headers>` folder's structure i end up with `C:\test_install\include\oatpp-1.3.0\oatpp\oatpp\<headers>`... (so there is an extra subfolder which shouldn't be there)

After digging a bit, i noticed that in `module-install.cmake` there is an extra <OATPP_MODULE_NAME> in the `DESTINATION` path of the `INCLUDE` attributes of the `install` commands as follows:

```
install(
    TARGETS ${OATPP_THIS_MODULE_TARGETS}
    EXPORT "${OATPP_MODULE_NAME}Targets"
    ARCHIVE
        DESTINATION "${CMAKE_INSTALL_LIBDIR}/oatpp-${OATPP_MODULE_VERSION}"
        COMPONENT Devel
    LIBRARY
        DESTINATION "${CMAKE_INSTALL_LIBDIR}/oatpp-${OATPP_MODULE_VERSION}"
        COMPONENT Library
    RUNTIME
        DESTINATION "${CMAKE_INSTALL_BINDIR}/oatpp-${OATPP_MODULE_VERSION}"
        COMPONENT Library
    INCLUDES
        DESTINATION "${CMAKE_INSTALL_INCLUDEDIR}/oatpp-${OATPP_MODULE_VERSION}/${OATPP_MODULE_NAME}"
)

install(DIRECTORY ${OATPP_DIRS_TO_INSTALL}
        DESTINATION "${CMAKE_INSTALL_INCLUDEDIR}/oatpp-${OATPP_MODULE_VERSION}/${OATPP_MODULE_NAME}"
        COMPONENT Devel
        FILES_MATCHING PATTERN "*.hpp"
)
```
If i substitute by the following:
```
install(
    TARGETS ${OATPP_THIS_MODULE_TARGETS}
    EXPORT "${OATPP_MODULE_NAME}Targets"
    ARCHIVE
        DESTINATION "${CMAKE_INSTALL_LIBDIR}/oatpp-${OATPP_MODULE_VERSION}"
        COMPONENT Devel
    LIBRARY
        DESTINATION "${CMAKE_INSTALL_LIBDIR}/oatpp-${OATPP_MODULE_VERSION}"
        COMPONENT Library
    RUNTIME
        DESTINATION "${CMAKE_INSTALL_BINDIR}/oatpp-${OATPP_MODULE_VERSION}"
        COMPONENT Library
    INCLUDES
        DESTINATION "${CMAKE_INSTALL_INCLUDEDIR}/oatpp-${OATPP_MODULE_VERSION}"
)

install(DIRECTORY ${OATPP_DIRS_TO_INSTALL}
        DESTINATION "${CMAKE_INSTALL_INCLUDEDIR}/oatpp-${OATPP_MODULE_VERSION}"
        COMPONENT Devel
        FILES_MATCHING PATTERN "*.hpp"
)
```
Then my issue goes away and i indeed ends up with my targeted `C:\test_install\include\oatpp-1.3.0\oatpp\<headers>` folder structure.

Is it an issue or an intended feature that i am yet unable to understand?

Thanks in advance for any answer one may provide me with.

**Comment by lganzzzo** [comment]
Hello @Saadharta ,

This is the intended directory structure of all oatpp modules.

`oatpp-<version>/<module>/<library-name>/<headers>`

example:

```bash
- oatpp-1.3.0
     - oatpp                   # module
          - oatpp/             # lib-1
          - oatpp-test/        # lib-2
     
     - oatpp-openssl           # module
          - oatpp-openssl/     # lib-1

```

One module can have more the one library. It just happens so that only the main oatpp module has two libs.

Then you have includes as follows:

```cpp
#include "oatpp/..."
#include "oatpp-test/..."
#include "oatpp-openssl/..."

```

**Comment by Saadharta** [comment]
Thank you @lganzzzo for your answer.

Since only the 'main' oatpp module has several libraries i failed to notice this pattern.
