### ISSUE TITLE
CMake file globbing is a bad idea

### ISSUE THREAD

**Issue by sodevel** [oatpp/oatpp#752]
PR #682 is a huge step backward regarding Modern CMake style, file globbing should be avoided. To add source groups, file globbing is not required at all, you can query all sources of a target. I have created a CMake function that adds source groups to a target in a way that Visual Studio does by default, it even supports generated files. However, this function pushes the required CMake version to 3.20 because it uses modern functions for path processing.

If interested, i can make a PR.

**Comment by lganzzzo** [comment]
Hello @sodevel ,

Yes, please. PRs are very welcome!

**Comment by lganzzzo** [comment]
Fixed in https://github.com/oatpp/oatpp/pull/753
