### ISSUE TITLE
Wrong parsing URLs w/o scheme and w port

### ISSUE THREAD

**Issue by gruk0** [oatpp/oatpp#758]
```
oatpp::String Url="example.com:8080/path";
oatpp::network::Url pUrl = oatpp::network::Url::Parser::parseUrl(Url);
```
After that, in pUrl, scheme is "example.com", host is "8080", port is -1.
But "example.com/path" parsed correctly.

**Comment by lganzzzo** [comment]
Hello @gruk0 ,

Thanks for reporting the issue. Looks like a bug.
