### ISSUE TITLE
API question - Separating .hpp files into .h and .cpp files

### ISSUE THREAD

**Issue by datacrystals** [oatpp/oatpp#774]
In file: oatpp/core/macro/component.hpp

# Question
Hello,

I've been recently trying to learn oat++ (and it's been great!), but I have one area that I can't seem to figure out. Is it supported to separate hpp files into .h and .cpp? 

For example, how could the following hpp oat++ code (from the starter project) be split?
```cpp    
class ApplicationComponent {
public:

    /**
     *  Create ConnectionProvider component which listens on the port
     */
    OATPP_CREATE_COMPONENT(std::shared_ptr<oatpp::network::ServerConnectionProvider>, serverConnectionProvider)([] {
        return oatpp::network::tcp::server::ConnectionProvider::createShared({"0.0.0.0", 8000, oatpp::network::Address::IP_4});
    }());

...
```

Additionally, is there a version of the starter project that has been split? I cannot seem to find any documentation that shows split files (but perhaps I missed something)?

Apologies if this question is already answered somewhere and I missed it!

Thank you for your time.

**Comment by lganzzzo** [comment]
Hello @datacrystals ,

You can create oatpp components in any place you want.
Also, it's NOT required to use oatpp DI (`OATPP_CREATE_COMPONENT`, `OATPP_COMPONENT `) at all.

We don't split components and controller files in examples just because it more convenient.

Regards,
Leonid

**Comment by datacrystals** [comment]
Great, thanks for clarifying!
