### ISSUE TITLE
TCP_NODELAY

### ISSUE THREAD

**Issue by oscarthorn** [oatpp/oatpp#775]
Hi!

I'm looking to set some tcp socket options, TCP_NODELAY and maybe TCP_QUICKACK when using websockets. Is there a way to do this with oat++? I found the socket in `oatpp::network::tcp::server::ConnectionProvider` but since the variable is private the is no easy way to set these options without rewriting the class.

**Comment by lganzzzo** [comment]
Hello @oscarthorn ,

You are correct as of now this is not configurable in the `oatpp::network::tcp::server::ConnectionProvider`.

There are several options how you can do that:
- Create you own connection provider by copy-pasting the existing one
- Create PR with functionality allowing to configure socket options.

The where you want to place your code is here - https://github.com/oatpp/oatpp/blob/9ab1c2a3cbfc579be91b746d3318fa275cf05c55/src/oatpp/network/tcp/server/ConnectionProvider.cpp#L320

In case you are willing creating a PR,
I suggest something similar to [ContextConfigurer](https://github.com/oatpp/oatpp-openssl/blob/master/src/oatpp-openssl/configurer/ContextConfigurer.hpp) in oatpp-openssl

Regards,
Leonid

**Comment by oscarthorn** [comment]
Thanks for the response!
