### ISSUE TITLE
Valgrind reports leaks and unintialised values

### ISSUE THREAD

**Issue by fhuberts** [oatpp/oatpp#793]
When I run valgrind on current master (0b3a66c47ceff530b39fb287591a9768db38cd51) then it reports leaks and jumps on uninitialised values.
I'll attach the valgrind log.

**Comment by fhuberts** [comment]
[valgrind.log](https://github.com/oatpp/oatpp/files/12138314/valgrind.log)

**Comment by fhuberts** [comment]
See the following lines in the log file:
1309-1332
1438-1475
2101-16567

**Comment by fhuberts** [comment]
[valgrind.2.log](https://github.com/oatpp/oatpp/files/12138699/valgrind.2.log)
With more details.

**Comment by lganzzzo** [comment]
Hello @fhuberts ,

> 1309-1332
Thread 33:
==45316== Conditional jump or move depends on uninitialised value(s)
==45316==    at 0xAD04B9: oatpp::async::Processor::checkCoroutinesSleep() (Processor.cpp:201)

Might be a false-positive alert.
Initialization is here - https://github.com/oatpp/oatpp/blob/master/src/oatpp/core/async/Processor.hpp#L124

> 1438-1475
Thread 39:
==45316== Conditional jump or move depends on uninitialised value(s)
==45316==    at 0xAD3C90: oatpp::async::worker::IOEventWorker::waitEvents() (IOEventWorker_epoll.cpp:193)

Might be false positive.
Line - https://github.com/oatpp/oatpp/blob/master/src/oatpp/core/async/worker/IOEventWorker_epoll.cpp#L193
`m_specialization` - is initialized in Worker constructor.
`action.getIOEventCode()` - both fields checking in `Action::getIOEventCode()` initialized in Action constructor.

> 2101-16567
HEAP SUMMARY:
==45316==     in use at exit: 128,634 bytes in 1,321 blocks
==45316==   total heap usage: 46,100,754 allocs, 46,099,433 frees, 14,590,182,648 bytes allocated
==45316== 
==45316== Thread 1:
==45316== 8 bytes in 1 blocks are still reachable in loss record 1 of 957
==45316==    at 0x4841FB5: operator new(unsigned long) (vg_replace_malloc.c:472)
==45316==    by 0x9653BA: oatpp::data::mapping::type::__class::Object<oatpp::test::core::data::mapping::type::(anonymous namespace)::TestDto>::createType() (Object.hpp:296)
==45316==    by 0x965275: oatpp::data::mapping::type::__class::Object<oatpp::test::core::data::mapping::type::(anonymous namespace)::TestDto>::getType() (Object.hpp:308)

Looks like it doesn't like oatpp type system.

To store type information (like DTO names, DTO field names, ENUM field names, other types parameters)
oatpp makes one time allocation of type-info structures which are never freed.

Example is here - https://github.com/oatpp/oatpp/blob/master/src/oatpp/core/data/mapping/type/List.hpp#L120

**Comment by fhuberts** [comment]
At the end of the log there is a huge list of (potential) leaks.
I did manage to plug 1 of them, but have lost the patch.
Others I tried to plug landed me in so many macros deep inside oatpp that I quickly fled out.
