### ISSUE TITLE
Won't build for iOS 8 or older

### ISSUE THREAD

**Issue by david-novak-legrand** [oatpp/oatpp#81]
Hi @lganzzzo,

I'm working on the iOS app version of the Android app that @dmcamens-legrand discussed with you recently. The oat++ library is working well on Android now, and I'm trying to make it work on iOS as well.

Sadly, the even though the thread_local keyword was added to Xcode 8, it won't compile to devices running iOS 8 or earlier, even in the current version (Xcode 10).

Do you have any ideas for how to use this library without using the thread_local storage functionality from C++11?

Thank you!

**Comment by lganzzzo** [comment]
Hello @david-novak-legrand ,

I have to investigate possible ways to work around this problem.

Will get back to you shortly.

Best Regards,
Leonid

**Comment by david-novak-legrand** [comment]
Thank you!

**Comment by lganzzzo** [comment]
Hey @david-novak-legrand ,

Please checkout this branch https://github.com/oatpp/oatpp/tree/compat_build_no_thread_local

Just build oatpp with `-DOATPP_COMPAT_BUILD_NO_THREAD_LOCAL` flag in order to build without `thread_local`.

```bash
cmake -DOATPP_COMPAT_BUILD_NO_THREAD_LOCAL=ON ..
```

Do you also need to be able to build `oatpp-websocket` module without `thread_local` ?
What other oatpp modules you are planning to use?

Regards,
Leonid

**Comment by lganzzzo** [comment]
Hello @david-novak-legrand , @dmcamens-legrand ,

Please checkout:

- `oatpp` branch - [compat_build_no_thread_local](https://github.com/oatpp/oatpp/tree/compat_build_no_thread_local)
- `oatpp-websocket` branch [compat_build_no_thread_local](https://github.com/oatpp/oatpp-websocket/tree/compat_build_no_thread_local)

Rebuild both `oatpp` and `oatpp-websocket` modules with `-DOATPP_COMPAT_BUILD_NO_THREAD_LOCAL` flag:

```bash
cmake -DOATPP_COMPAT_BUILD_NO_THREAD_LOCAL=ON ..
```
Please let me know if it worked for you.
Branches will be merged after you confirmation.

Best Regards,
Leonid

**Comment by lganzzzo** [comment]
Hello @david-novak-legrand ,
Did you manage to build oatpp from specified branch for iOS8 ?

**Comment by david-novak-legrand** [comment]
Hi @lganzzzo ,
Thanks for your help! I believe it's close. I'm running into issues compiling some of the implicit conversions from long long to size_t.

**Comment by lganzzzo** [comment]
@david-novak-legrand. Cool, please let me know if you need some help from my side.
Also it would be cool if you prepare a PR with your "compatibility" changes!

Thank you.

**Comment by david-novak-legrand** [comment]
@lganzzzo Just got it to build! I would be very happy to prepare a PR.

Thanks!

**Comment by lganzzzo** [comment]
nice!

**Comment by david-novak-legrand** [comment]
I noticed that you removed three files under commit 71630b6 (Better Router API):
Router.cpp
Subscriber.hpp
Subscriber.cpp

I'm not sure what required them, but I had to re-add them for it to build.

Any idea what might still require those files?

**Comment by david-novak-legrand** [comment]
I don't want my PR to include them unless they are actually still required.

**Comment by lganzzzo** [comment]
@david-novak-legrand 
This files are not needed any more. 
Routing functionality was refactored, and this files were removed.

**Comment by lganzzzo** [comment]
@david-novak-legrand 
I think you may just create PR to the `compat_build_no_thread_local` branch. And if there are any problems with merging - I'll help you to resolve them.

**Comment by david-novak-legrand** [comment]
@lganzzzo Perfect. I found the references to those files in my project and removed them!

**Comment by david-novak-legrand** [comment]
I don't have permission to push to a branch. Do I need to fork? Thanks!

**Comment by david-novak-legrand** [comment]
And yes, oatpp and oatpp-websocket were the only modules that I needed, so thanks for working on both of those!

**Comment by lganzzzo** [comment]
@david-novak-legrand 

> I don't have permission to push to a branch. Do I need to fork? Thanks!

Yes, just fork it and create PR from the fork.

**Comment by lganzzzo** [comment]
> And yes, oatpp and oatpp-websocket were the only modules that I needed, so thanks for working on both of those!

Great! Happy to help!

Regards,
Leonid
