### ISSUE TITLE
On Arm64, static file not found results in SIGABRT and hangs 

### ISSUE THREAD

**Issue by vinkaga** [oatpp/oatpp#83]
It works fine on x86_64 but when I run on aarch64/arm64, file not found (the media example) results in SIGABRT and hangs. Any suggestions?

**Comment by lganzzzo** [comment]
Hello @vinkaga , 

Please give more details.

It would be helpful if you specify:
- What endpoint / Method call cases the issue.
- Is application is able to actually read the file/ does application has access to that file.
- How much RAM is available on the device you are running the Media Example.

If I understand correctly this question is about [example-hls-media-stream](https://github.com/oatpp/example-hls-media-stream).

Regards,
Leonid

**Comment by lganzzzo** [comment]
Hello @vinkaga , do you have any updates on the issue?

**Comment by vinkaga** [comment]
Sorry, just got back from Yosemite :-) 

I rebuilt oatpp and the example-hls-media-stream on the the target board (Aarch64 Nvidia Jetson Xavier). I ran all the tests and performed a similar test on example-hls-media-stream that was causing SIGABRT on my code. Everything works fine and no SIGABRT.

I'll assume that something in my code or cmake is doing it. My next goal would be to integrate into my code (with minimum changes) and repeat the tests. This issue can be closed for now.

**Comment by lganzzzo** [comment]
@vinkaga , thank you for the update! Good it works.
Yosemite - I love it :)

**Comment by vinkaga** [comment]
I rebuilt my app on the target board and it works correctly without SIGABRT. I suspect it was a cross-compilation issue.

**Comment by lganzzzo** [comment]
@vinkaga Cool! Thank you for the update!

Can you describe a bit your app, what is your use-case of the oatpp - just curious.

Thank you!

**Comment by vinkaga** [comment]
@lganzzzo, the app is an admin/debug UI for an embedded system. The hardware and software infrastructure would be similar to that of Nvidia Jetson Xavier dev board.

**Comment by lganzzzo** [comment]
@vinkaga thank you for describing your project!

I have https://oatpp.io/ website served by oatpp. And it's open source ([web-site repo](https://github.com/oatpp/website)). - I guess you may find something to reuse there, like [static files server](https://github.com/oatpp/website/tree/master/server/main).

Regards,
Leonid
