### ISSUE TITLE
“Class”:“::”The symbol on the left must be a type and "getType": not a member of "MyDto"

### ISSUE THREAD

**Issue by Mywayistheseaofstar** [oatpp/oatpp#862]
This is my code:
#include "oatpp/parser/json/mapping/ObjectMapper.hpp"
#include "oatpp/core/macro/codegen.hpp"
#include "oatpp/core/macro/component.hpp"
#include "oatpp/core/Types.hpp"

#include <iostream>

#include OATPP_CODEGEN_BEGIN(DTO) // 生成 DTO 代码

class MyDto : public oatpp::DTO {

    DTO_INIT(MyDto, oatpp::DTO)

        DTO_FIELD(Int32, statusCode); // 定义一个整数字段
    DTO_FIELD(String, message); // 定义一个字符串字

};

#include OATPP_CODEGEN_END(DTO) // 结束 DTO 代码生成

int main() {

    oatpp::base::Environment::init();

    oatpp::parser::json::mapping::ObjectMapper mapper;

    oatpp::String json = "{\"statusCode\":200,\"message\":\"Success\"}"; // 定义一个 JSON 字符串

    // 使用 ObjectMapper 将 JSON 转换为 DTO 对象
    auto dto = mapper.readFromString<MyDto>(json);

    // 输出 DTO 对象的字段值
    //std::cout << "statusCode=" << dto->statusCode
    //    << ", message=" << dto->message->std_str()
    //    << std::endl;

    oatpp::base::Environment::destroy();

    return 0;
}

This is my compilation error:
[ 50%] Building CXX object CMakeFiles/helloworld.dir/main.cpp.o
In file included from /home/moon/appLib/include/oatpp-1.3.0/oatpp/oatpp/parser/json/mapping/ObjectMapper.hpp:31,
                 from /home/moon/MyCode/testOat/main.cpp:46:
/home/moon/appLib/include/oatpp-1.3.0/oatpp/oatpp/core/data/mapping/ObjectMapper.hpp: In instantiation of ‘Wrapper oatpp::data::mapping::ObjectMapper::readFromString(const String&) const [with Wrapper = MyDto; oatpp::String = oatpp::data::mapping::type::String]’:
/home/moon/MyCode/testOat/main.cpp:75:44:   required from here
/home/moon/appLib/include/oatpp-1.3.0/oatpp/oatpp/core/data/mapping/ObjectMapper.hpp:126:40: error: no type named ‘Class’ in ‘class MyDto’
  126 |     auto type = Wrapper::Class::getType();
      |                 ~~~~~~~~~~~~~~~~~~~~~~~^~
make[2]: *** [CMakeFiles/helloworld.dir/build.make:76: CMakeFiles/helloworld.dir/main.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:83: CMakeFiles/helloworld.dir/all] Error 2
make: *** [Makefile:91: all] Error 2

**Why is this problem and how can it be solved?**
![图片](https://github.com/oatpp/oatpp/assets/73692893/c702e81e-1dc8-483e-b150-65df6987b813)

![图片](https://github.com/oatpp/oatpp/assets/73692893/fb96c042-250a-4a48-916d-a7ab12a1ad88)
![图片](https://github.com/oatpp/oatpp/assets/73692893/92331aa0-8aa6-493d-86dc-15f9f744a8f8)

**Comment by nanlour** [comment]
Try change MyDto into oatpp::Object<MyDto> in this line:
// 使用 ObjectMapper 将 JSON 转换为 DTO 对象
auto dto = mapper.readFromString<MyDto>(json);

**Comment by Mywayistheseaofstar** [comment]
I have solved this problem, thank you

**Comment by Mywayistheseaofstar** [comment]
> Try change MyDto into `oatpp::Object<MyDto>` in this line:
> 
> ```
> // 使用 ObjectMapper 将 JSON 转换为 DTO 对象
> auto dto = mapper.readFromString<MyDto>(json);
> ```

ok, thank you.
