### ISSUE TITLE
Multiple line string of DTO_FIELD(String, respText);

### ISSUE THREAD

**Issue by alex-lt-kong** [oatpp/oatpp#866]
I defined a DTO field as follows:

```C++
DTO_FIELD(String, respText, "respText");
```

The problem is, I want to show a multi-line string message (e.g., the string version of a JSON object), such as the following:
```JavaScript
{
    "ObjectName": "SomeName",
    "ObjectValue": "SomeValue",
    "RandomKey": "12345"
    // Some other key-value pairs whose schema canNOT be predicted.
}
```
to users. Currently the string will be shown in one line like this:
```
  "respText": "{\n  \"ObjectName\":\"SomeName\",\n\"ObjectValue\": \"SomeValue\",\n\"RandomKey\": \"12345\"\n}"
```
Is it possible to ask Oat++/Swagger to show my multi-line string as it is (i.e., treating `\n` as line break)?

(Or even better, is it possible to call an Oat++ function that parses my JSON string to a Oat++'s JSON object, which can handle all the details?)

**Comment by lganzzzo** [comment]
Hello @alex-lt-kong ,

If you want to have "respText" as an arbitrary JSON object - you can do that:

For that - use `oatpp::Any` type

```cpp
DTO_FIELD(Any, respText, "respText");
```

Thus it will render any other DTO-Object/String/Number/Bool etc. depending on what is assigned to respText.

Ex:

```cpp
auto respText = SomeRespTextDto::createShared();
respText-> ObjectName = "SomeName";
respText-> ObjectValue = "SomeValue";
respText-> RandomKey = ""12345;

auto response = ResponseDto::createShared();
response->respText = respText;

return createDtoResponse(Statuse::CODE_200, response);
```

Result:

```json
{
  "respText": {
     "ObjectName": "SomeName",
     "ObjectValue": "SomeValue",
     "RandomKey": "12345"
  }
}
```

And enable beautifier for formatted output.

**Comment by alex-lt-kong** [comment]
Hi @lganzzzo ,

My question is a bit different though. Actually, I am using `nlohmann::json` and what I want is to pass an arbitrary JSON object, say, `nlohmann::json myJson` and dump the entire `myJson` to an Oat++ DTO in order to present the content of `myJson` to users.

In your example:
```C++
auto respText = SomeRespTextDto::createShared();
respText->ObjectName = "SomeName";
respText->ObjectValue = "SomeValue";
respText->RandomKey = 12345;
```
if I am not mistaken, I have to know the JSON's schema in compile time, which is not the situation I am facing: `ObjectName`/`ObjectValue`/`RandomKey` are just for demonstration purpose only, in reality there could be much more arbitrary key-values and also nested ones.

Following your approach, guess I would need something like below, which I am not sure if it is supported:
```C++
DTO_FIELD(Any, respText, "respText");

auto respText = SomeRespTextDto::createShared();
respText->["/weDontKnow/theKeyInCompileTime"] = "SomeName";
respText->["/RandomKey/thatIsPassed/inRunTime"] = "12345";
respText->["/ObjectValue/nestedKey"] = "SomeValue";
```

**Comment by lganzzzo** [comment]
You can serialize your JSON to string, and then deserialize it with oatpp...
But in this case - you can just use oatpp, or pass json string directly to users.

Anyway you can do it as follows:) :


```cpp
oatpp::String json = serializeNlohmannToString(...);
auto anyObject = oatppJsonMapper->readFromString<oatpp::Any>(json);
return createDtoResponse(Statuse::CODE_200, anyObject);
```

**Comment by alex-lt-kong** [comment]
Hi @lganzzzo ,

Do you have a doc for the usage of `oatppJsonMapper`? Tried searching with [Google](https://www.google.com.hk/search?q=%22oatppJsonMapper%22+site%3Agithub.com&newwindow=1&client=firefox-b-e&sca_esv=571511976&ei=av4gZerqMPPg2roP876okAg&ved=0ahUKEwjqx-SQq-OBAxVzsFYBHXMfCoIQ4dUDCA8&uact=5&oq=%22oatppJsonMapper%22+site%3Agithub.com&gs_lp=Egxnd3Mtd2l6LXNlcnAiISJvYXRwcEpzb25NYXBwZXIiIHNpdGU6Z2l0aHViLmNvbUifEVDyC1jrD3ABeACQAQCYAQCgAQCqAQC4AQPIAQD4AQHiAwQYASBBiAYB&sclient=gws-wiz-serp) and [Github](https://github.com/search?q=repo%3Aoatpp%2Foatpp%20oatppJsonMapper&type=code), but can't find any results though.
(Or perhaps there is a typo?)
