### ISSUE TITLE
How to catch this exception

### ISSUE THREAD

**Issue by alex-lt-kong** [oatpp/oatpp#890]
I have a program that uses Oatpp+OpenSSL and the program crashes due to an `std::runtime_error` being thrown:

```
ESC[41m E ESC[0m|2023-11-16 00:14:03 1700064843875660| [oatpp::openssl::Connection::ConnectionContext::init()]:40E67F55BD7F0000:error:0A00009C:SSL routines:ssl3_get_record:http request:../ssl/record/ssl3_record.c:345:

terminate called after throwing an instance of 'std::runtime_error'
  what():  [oatpp::openssl::Connection::ConnectionContext::init()]: Error. Handshake failed.
Signal [06] caught
```

After some searching, it turns out that the error is thrown [here](https://github.com/oatpp/oatpp-openssl/blob/b1fcc6a55822f7386f5ebf1ec36236426e80883d/src/oatpp-openssl/Connection.cpp#L72)

The problem is, I am not sure which line of my code calls this and if it is possible to somehow make my program keep running, disregarding this issue. Any idea?

**Comment by lganzzzo** [comment]
Hello @alex-lt-kong ,

This throw war introduced in the latest commit - https://github.com/oatpp/oatpp-openssl/commit/55cf90bb3ab1a179c78db1b78fd2d07e9ae4d7d2#diff-154b6b83b07306666e4b4cd5ef5e173c72e54cad2432d8ee68ae39a0a1778a9cR71

Before we were just ignoring handshake failure.
Actually, I don't really think it is an error - not a fatal one for sure.

However, it's strange that your program crashes...
Is it a client program that you are running? Like you are trying to connect to remote server, handshake fails, and program crashes?

The easiest way would be to wrap this call with try-catch block.
However, I'm thinking if we need to throw and log this event at all.

**Comment by alex-lt-kong** [comment]
Hi @lganzzzo ,

My program is an http service, not client, with SSL enabled. Regarding try-catch, usually my code in controller is executed in a sort-of callback manner, I actually have no idea where to add try-catch--and thus the subject of this issue.

ICYW, [this](https://github.com/alex-lt-kong/camera-server/blob/main/src/camera-server/http_service/oatpp_entry.cpp) is the entry point of Oatpp in my program, can you tell me where I should put a try-catch to catch the above-mentioned exception?

Let me also add my two cents to the throw war: my personal preference is that, as an HTTP framework, exceptions should only be propagated up to user's code only in a few extreme cases. For example, port being occupied and memory allocation failure, where all hope to keep the service running is lost; otherwise users may prefer having the service running and let these exceptions be logged/returned to client (i.e., status code 500).

**Comment by lganzzzo** [comment]
Hello @alex-lt-kong ,

This issue was fixes. Please checkout the latest `oatpp-openssl` master.

> Let me also add my two cents to the throw war: my personal preference is that, as an HTTP framework, exceptions should only be propagated up to user's code in a few extreme cases. For example, port being occupied and memory allocation failure, where all hope to keep the service running is lost; otherwise users may prefer having the service running and let these exceptions be logged/returned to client (i.e., status code 500).

I agree 100%.
This bug was introduced by adding unnecessary throw in oatpp-openssl connection handshake.
And it appears that connection stream context initialization (handshake in case of oatpp-openssl connection) isn't protected with try-catch [here](https://github.com/oatpp/oatpp/blob/master/src/oatpp/web/server/HttpProcessor.cpp#L253)

As further steps we'll have to add a better top-level error handling inside oatpp itself.

**Comment by alex-lt-kong** [comment]
Thanks for the update. Let me mark this as closed now.
