### ISSUE TITLE
API question - Enum to string

### ISSUE THREAD

**Issue by DominikStransky** [oatpp/oatpp#891]
In file: oatpp/core/data/mapping/type/Enum.hpp

# Question

Is it possible to get the string value of an ENUM DTO FIELD like in the following example of a StatusDto.hpp definition? I want to do something like Status::OK.toString() which should give me "OK".
```
#include OATPP_CODEGEN_BEGIN(DTO)

ENUM(Status,
     v_int32,
     VALUE(OK, 1),
     VALUE(WARN, 2),
     VALUE(ERROR, 3))

std::string const statusDesc =
     "Status of the thing. One of 'OK', 'WARN', 'ERROR'."; // Use something like Status::OK.toString() here instead

class HealthDto : public oatpp::DTO
{
  DTO_INIT(HealthDto, DTO)

  DTO_FIELD_INFO(status) { info->description = statusDesc; }
  DTO_FIELD(Enum<Status>, status);
};

#include OATPP_CODEGEN_END(DTO)
```

**Comment by dfjongen** [comment]
Hi Dominik, 
I know you can use `Enum<Status>::getEntryByValue(status).name.std_str()` to dump the content of 'status'.
BR Erik

**Comment by DominikStransky** [comment]
Thanks Erik! This works very well!
BR Dominik
