### ISSUE TITLE
Build failure because of `-fcf-protection` (again)

### ISSUE THREAD

**Issue by sodevel** [oatpp/oatpp#892]
Building on CentOS 7 fails because the compiler option `-fcf-protection` is wrongfully applied. The reason for this is quite simple, the test

https://github.com/oatpp/oatpp/blob/c1d37c189e3f07db3bd28d1ee98845692e094a06/cmake/compiler-flags.cmake#L258

does actually succeed for the detected architecture `x86_64`.

However, i don't know how to properly fix that. To build for the 32 bit architecture, you have to use a toolchain file and set the architecture manually. AFAIK for CentOS (and maybe others too) the proper name is `i686`, this won't pass the quoted test. To complicate the situation even more, you have two options to build for 32 bit: a true CMake crossbuild by specifying `CMAKE_SYSTEM_NAME` or just a regular build by using the command line option `-m32`. So far i was using the latter approach without issues, but this does not update `CMAKE_SYSTEM_PROCESSOR` and keeps whatever the system reports.

**Comment by sodevel** [comment]
Apparently i misunderstood the comment about that option, it is supposed to work on any Intel architecture, not only 32 bit but also 64 bit, so the test is actually correct in that matter. The error is another one, according to https://gcc.gnu.org/gcc-8/changes.html this option is only available since GCC 8.1.

**Comment by sgallou** [comment]
Can you try replacing :
```
    add_compiler_flags(4.6 "-fcf-protection")`
```
by :
```
    add_compiler_flags(8.1 "-fcf-protection")`
```

**Comment by sodevel** [comment]
Yes, i already did before i saw your post. This fixes building for me with GCC 4.8 (for some reason i thought CentOS 7 uses 4.6, but in fact it uses 4.8, my commit message might be misleading :smile:). My build log still gets flooded with `cc1plus: warning: unrecognized command line option "-Wno-pessimizing-move" [enabled by default]` messages and i don't understand why, but i don't have the time to investigate this now.

On another note, i'm not sure if it is a good idea to always set all these flags. Package builders like `rpmbuild` set a lot of these flags automatically on their own before starting the build, this might lead to conflicting settings. But this is not the right place to discuss that matter.

**Comment by sgallou** [comment]
So issue can be closed ?

**Comment by sodevel** [comment]
After my linked PR got applied, this issue can and will get closed.
