### ISSUE TITLE
Regarding oatpp::async::CoroutineWithResult

### ISSUE THREAD

**Issue by parora610** [oatpp/oatpp#907]
Hello there,

I am trying to use oatpp::async::CoroutineWithResult but when I try to refer callbackTo, it is throwing compilation error "error: no matching member function for call to 'callbackTo'". Can you please assist with the error. A code snippet is provided below

Action onRequestBodyRead(const oatpp::Object<AdServerRequestDto>& adServerReq){
      return FetchAdsCoroutine::startForResult().callbackTo(&FetchAdsEndpoint::onResult);
}

The coroutin code is provide below
class FetchAdsCoroutine : public oatpp::async::CoroutineWithResult<FetchAdsCoroutine, oatpp::Object<AdServerResponseDto>> {
private:
    oatpp::Object<AdServerRequestDto> m_RequestDTO;

public:
    // Coroutine constructor to initialize members
    FetchAdsCoroutine(const oatpp::Object<AdServerRequestDto>& reqDTO)
          : m_RequestDTO(reqDTO) {}

    Action act() override {
        // Implement your async logic here
        // Make async calls, aggregate responses, etc.
        
        auto adServerResponse = AdServerResponseDto::createShared();
        adServerResponse->correlationId = 1;
        adServerResponse->clientTimestamp = 1234567890;
        adServerResponse->providers = oatpp::List<oatpp::Object<AdProviderResponseDto>>::createShared();
        return _return(adServerResponse);
    }
};

**Comment by linhaojun857** [comment]
Hello @parora610 
You can try changing your code to look like this
```C++
oatpp::Object ---> const oatpp::Object&
```
```C++
class FetchAdsCoroutine : public oatpp::async::CoroutineWithResult<FetchAdsCoroutine, const oatpp::Object&>
```
```C++
Action onResult(const oatpp::Object& result)
```

**Comment by parora610** [comment]
> Hello @parora610 You can try changing your code to look like this
> 
> ```c++
> oatpp::Object ---> const oatpp::Object&
> ```
> 
> ```c++
> class FetchAdsCoroutine : public oatpp::async::CoroutineWithResult<FetchAdsCoroutine, const oatpp::Object&>
> ```
> 
> ```c++
> Action onResult(const oatpp::Object& result)
> ```

Thanks **linhaojun857**. It worked.

**Comment by parora610** [comment]
Hi linhaojun857,

I am building a http server using oatpp lib and seek your expert opinion on the overall strategy. I am trying to build a http server. The high-level function of this server is to get request from client and then it makes call to multiple thirdparty vendors to get data, then aggregate the data from all vendors and respond back to client. The traffic on the http server is expected 1000 q/s. I want to make call to third party vendor in parallel. The below are high level approach I am following
1. Cloned https://github.com/oatpp/example-async-api
2. Create a coroutine as below
    class FetchAdsCoroutine : public oatpp::async::CoroutineWithResult<FetchAdsCoroutine, const oatpp::Object<AdServerResponseDto>&> {
3. In side act, I am creating Executor and submitting request to required providers as below
Action act() override {
        auto objectMapper = oatpp::parser::json::mapping::ObjectMapper::createShared();
        m_responses = std::make_shared<std::vector<oatpp::Object<AdProviderResponseDto>>>();
        
        oatpp::async::Executor executor(2, 4, 1);

        for (const auto& providerReq: *m_RequestDTO->providers) {
            std::cout << "------------------------------Provider Name: " << providerReq->name->c_str() << std::endl;
            auto providerReqExec = AdConnectionProvider::getInstance().getHttpExecutor(providerReq->host, providerReq->port);   
    
            executor.execute<AdProviderCoroutine>(AdProviderApiClient::createShared(providerReqExec, objectMapper), 
                providerReq->name, providerReq->endpoint, m_responses);
        }
        executor.waitTasksFinished();
        executor.stop();
        executor.join();
        auto finalResponse = AdServerResponseDto::createShared();
        finalResponse->correlationId = 1;
        finalResponse->clientTimestamp = 1234567890;
        finalResponse->providers = oatpp::List<oatpp::Object<AdProviderResponseDto>>::createShared();
        for (const auto& response : *m_responses) {
            finalResponse->providers->push_back(response);
        }
        // Return final response
        return _return(finalResponse);
    }

4. The controller code looks as below
ENDPOINT_ASYNC("POST", "/ads/fetchAds", FetchAdsEndpoint){
    ENDPOINT_ASYNC_INIT(FetchAdsEndpoint)
    
    Action act() override {
      return request->readBodyToDtoAsync<oatpp::Object<AdServerRequestDto>>(controller->getDefaultObjectMapper()).callbackTo(&FetchAdsEndpoint::onRequestBodyRead);
    }
    
    Action onRequestBodyRead(const oatpp::Object<AdServerRequestDto>& adServerReq){
      return FetchAdsCoroutine::startForResult(adServerReq).callbackTo(&FetchAdsEndpoint::onResult);
    }

    Action onResult(const oatpp::Object<AdServerResponseDto>& response) {
        // Send the response back to the client
        return _return(controller->createDtoResponse(Status::CODE_200, response));
    }
  }; 

can you please suggest if I am doing it right? or is there any approach I should take.

Thanks

**Comment by linhaojun857** [comment]
Hello @parora610 
When concurrency is high, you will create a large number of Executors by writing this way, my suggestion is to create an Executor and reuse it

**Comment by parora610** [comment]
Dear linhaojun857,

Thanks for the suggestion. I have two more questions.
1. If I create a one executor, how will handle the response from multiple providers for every client request.

2. I was trying to find out to put a connection timeout when I make a call to provider. I could not find it in ConnectionProvider or HttpRequestExecutor. Is there a way to set the timeout on API call.

Thanks

**Comment by linhaojun857** [comment]
@parora610 
- For the first problem, I think we can use `std::promise` to solve, after the task is delivered we can call `future.get()` to wait for the return result
- For the second question, oatpp seems unable to set timeout

**Comment by parora610** [comment]
Thanks linhaojun857. I made the change as you suggested and its working fine. I am trying to build docker image but it always throwing error that oat modules are not found. Have you encountered such error.

**Comment by parora610** [comment]
> Thanks linhaojun857. I made the change as you suggested and its working fine. I am trying to build docker image but it always throwing error that oat modules are not found. Have you encountered such error.

Never mind. I figured it out.

**Comment by parora610** [comment]
Thanks linhaojun857 for your support. I could able to build the http server with docker image. I will bug you again if encounter any issue :)
