### ISSUE TITLE
How can I use OATPP to handle web browser request download file.

### ISSUE THREAD

**Issue by yifong0** [oatpp/oatpp#912]
Hi All:
I surveyed the ticket list, and 2 tickets(#859,#638) talk about file download.
But I cannot get an answer from those tickets.
Does anyone know oatpp(web-server) how to handle remote web browser requests for a file download?
Thank you very much.
YiFong

**Comment by lganzzzo** [comment]
Hello @yifong0 ,

Here is the simplest snippet:

```cpp
  ENDPOINT("GET", "file", getFile) {
    oatpp::String fileName = "my-file.txt"; // name of the downloaded file (how browser will see it)
    oatpp::String binaryData = "<data>"; // whatever binary data
    
    auto response = createResponse(Status::CODE_200, binaryData);
    response->putHeader("Content-Type", "application/octet-stream");
    response->putHeader("Content-Disposition", "attachment; filename=\"" + fileName + "\"");
    return response;
  }
```

**Comment by yifong0** [comment]
Hi lganzzzo:

Your example is working, thank you very much.

The complete code for file download on my side.

URL = http://<your.server's ip>:<your.server's port>/<file_name>

ENDPOINT("GET", "/file/{file_name}", getFile, PATH(String, file_name)) {
    oatpp::String fileName = file_name; // name of the downloaded file (how browser will see it)
	oatpp::String fullfileName = "/usr/var/" + fileName;
    oatpp::String binaryData = oatpp::String::loadFromFile(fullfileName->c_str()); // whatever binary data
    auto response = createResponse(Status::CODE_200, binaryData);
    response->putHeader("Content-Type", "application/octet-stream");
    response->putHeader("Content-Disposition", "attachment; filename=\"" + fileName + "\"");
    return response;
  }

:D
