### ISSUE TITLE
Local header in angled brackets in version 1.3.0-latest

### ISSUE THREAD

**Issue by sjonnalagadda** [oatpp/oatpp#950]
xoatpp/web/server/handler/AuthorizationHandler.hpp, oatpp/network/tcp/ConnectionConfigurer.hpp has a local header in angled bracket and complier is erroring out. I'm using using project from a bazel proejct. Here is the place I have put temporary fix (https://github.com/sjonnalagadda/oatpp-header-fix) to unblock myself.

Here is the bazel config:

WORKSPACE file contents

http_archive(
      name = "oatpp_web_framework",
      urls = ["https://github.com/sjonnalagadda/oatpp-header-fix/archive/c6d4bd41414c2ec6560fa5b60d02c6dd8c5aa797.zip"],
      strip_prefix = "oatpp-header-fix-c6d4bd41414c2ec6560fa5b60d02c6dd8c5aa797/src",
      build_file = "@//:third-party/oatapp.BUILD",
)

BUILD.bazel  file contents

load("@rules_cc//cc:defs.bzl", "cc_library")

cc_library(
      name = "oatpp",
      srcs = glob(["oatpp/**/*.cpp"]),
      hdrs = glob(["oatpp/**/*.hpp"]),
      visibility = ["//visibility:public"],
      linkstatic = True,
)

**Comment by lganzzzo** [comment]
@sjonnalagadda ,

Thanks for the issue!
We'll fix that in `1.4.0`

Regards,
Leonid

**Comment by lganzzzo** [comment]
Fixed
