### ISSUE TITLE
https://oatpp.io website certificate expired on 5 July 2024

### ISSUE THREAD

**Issue by frankhale** [oatpp/oatpp#954]
Not sure if anyone has noticed but the certificate for https://oatpp.io expired on 5 July 2024

![image](https://github.com/oatpp/oatpp/assets/190154/2603ae87-71a5-4b13-abe6-be9475f58d59)

**Comment by lganzzzo** [comment]
Hello @frankhale ,

Renewed!
Thanks for noticing!
